### ISSUE TITLE
Add external library files (lib)

### ISSUE THREAD

**Issue by artdude543** [MinecraftForge/ForgeGradle#15]
How does one now add lib files now?

As I can't seem to find the mcp/lib folder for compiling, could someone tell me what the procedure is now so that I can compile my mod without having dependence errors.

Thanks,
artdude543

**Comment by Kaki-In** [comment]
Hello, 

Gradle does not support compile anymore... What should I do now?

**Comment by PaintNinja** [comment]
Use `compileOnly` instead, as explained in the Gradle docs when `compile` was deprecated.
