### ISSUE TITLE
ForgeGradle doesn't support multi-project builds

### ISSUE THREAD

**Issue by kenzierocks** [MinecraftForge/ForgeGradle#167]
As the title says, multi-project builds are simply not supported by ForgeGradle. Not sure what is the problem, but there are a few problems. Everything here is done with [the WorldEdit project, my fork](https://github.com/kenzierocks/WorldEdit/tree/feature/forge-1.8).

1. #166 doesn't resolve itself with multi-project builds, current workaround is to run `setupDecompWorkspace` in a single-project build, which will then allow the multi-project build to skip the troublesome `:decompile` task.
2. `:processSources` doesn't work with multi-project builds. Log at http://pastebin.com/WUCzjQh1. Command was `gradle setupDecompWorkspace build -S`.

`gradle --version`: http://pastebin.com/KdfBAPxJ

**Comment by Eurymachus** [comment]
Just adding my two pennies. I'm having issues with genIntelliJRuns http://pastebin.com/qtbfNmXP
Multiproject setup.

Let me know if you need any more info.

**Comment by Tarig0** [comment]
Eurymachus and I have figured how to properly setup multi-project gradle projects which was the issue for the runs

**Comment by Eurymachus** [comment]
Indeed, though Tarig did most of the work.

**Comment by JustGregory** [comment]
I also had problems with multiproject setup; that is, a top-level Gradle project with Gradle subproject folders. For me, the question is more a matter of what goes into the top level `build.gradle` script. Do I just `apply plugin: 'base'` or do I need most of the stuff from the minecraft forge source project download?

In my particular case, using NetBeans 8.0.2 IDE with the Gradle support plugin added, I can open my Minecraft Forge projects and build them, although with some intermittent problems. I do know that putting much of the shared build-script functionality into a `common.gradle` file will automatically apply to all sub-projects when I add this to the root build script:
    subprojects {
        apply from: rootProject.file('common.gradle')
    }
For my example mod meta-project, let's assume I'm revamping the old MobTalker mod, breaking up the entities, from the mob-talker conversation engine and item classes, to modularize things.
The root project build.gradle is http://pastebin.com/5Muu3QwU and the common.gradle is http://pastebin.com/WDJ0LntH and I also have a settings.gradle which only includes the subproject directories by name. The main subproject's build.gradle is http://pastebin.com/fU3YVmhj
but note that the two build files have some duplicate content. Is there a recommended way of doing this in a more simplified way?

**Comment by Tarig0** [comment]
Not sure if I understand your needs, but we were able to setup an environment that when we ran say WirelessRedstone it built our base project slimevoidlib. I'll see about uploading a youtube video, hopefully that will either be exactly what you need or put you on the right path

**Comment by AbrarSyed** [comment]
For future reference please dont derail an existing issue with only tangential relevant posts.

You can resolve those duplicates quite easily. Just specify ```evaluationDependsOn rootProject``` inside your sub projects to ensure that the subprojects block (AKA: the common.gradle) is evaluated before the build.gradle of the subproject itself. Then the information set in the common will be directly accessible to the sub project, and you can resolve your duplication.

https://gradle.org/docs/current/userguide/multi_project_builds.html

**Comment by Tarig0** [comment]
Back on topic @kenzierocks I would try adding a ":" to the start of each project in the settings.gradle

Think this will create the correct hierarchy.

**Comment by kenzierocks** [comment]
Fixed, turns out one of the other plugins was including Guava 10 which broke FG. Fixed in combination with another issue we were having.
