### ISSUE TITLE
Curse releaseType does not parse GString properly

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/ForgeGradle#173]
Passing, for example, "${mod_appendix}" to releaseType causes an error like: > The release type must be either 'alpha', 'beta', or 'release'! 'beta' is not a valid type!

Changing it to "${mod_appendix}".toString() resolves the issue, but this is very counter-intuitive.

Problem code is likely here: https://github.com/MinecraftForge/ForgeGradle/blob/FG_1.2/src/main/java/net/minecraftforge/gradle/curseforge/CurseUploadTask.java#L312-L318

**Comment by AbrarSyed** [comment]
888602d1308b1215f372b89ec667607443841254
