### ISSUE TITLE
Cleanup Logging

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/ForgeGradle#175]
Currently, ForgeGradle logs pretty much everything at the INFO level. This causes a lot of unneeded spam in the logs if the build is ran with `--info` (Which I like to do on my Jenkins server). I believe that things like DelayedString resolving, asset copying, These processing lines: `Processing net/minecraft/world/World.class`, and the copying lines: `Copying net/minecraftforge/common/MinecraftForge.class` could be moved to either TRACE or DEBUG levels.

**Comment by AbrarSyed** [comment]
yeah yeah im gonna close this because im gonna pull the PR real soon...
