### ISSUE TITLE
Random NullPointer

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/ForgeGradle#177]
http://puu.sh/eh6wj/8bce9ea1f6.log

After many things that FG depends on changing tonight, This NPE has started to occur sometimes. It appears to only occur when `reobf` is ran the first time after setup. The second time it is ran, the build succeeds.

**Comment by AbrarSyed** [comment]
wat... I dont even know how this is possible.. i mean,... how...  it should be 100% IMPOSSIBLE

**Comment by bdew** [comment]
> :setupDecompWorkspace
> :reobf FAILED

This looks like the same issue as #186 (which is now fixed)

**Comment by matthewprenger** [comment]
Yep looks like the same issue. Closing.
