### ISSUE TITLE
Can't find gradle.properties

### ISSUE THREAD

**Issue by Sluethen** [MinecraftForge/ForgeGradle#178]
I had a problem simalar to sag73 but I can't find gradle.properties

**Comment by AbrarSyed** [comment]
thats not worthy of an issue.
its in the user folder.
C:/users/YourUserName/.gradle/gradle.proeprties
if it doesnt exist, you have to make it. You can also make one inside the project folder.

**Comment by Sluethen** [comment]
quick question does it automaticly fill in the code and where do it put it?

**Comment by AbrarSyed** [comment]
there is no code in the gradle.properties file.
its just key value pairs.. like this..
```key=value```

**Comment by Sluethen** [comment]
ok but path plz

**Comment by AbrarSyed** [comment]
what path? there is no path...

**Comment by Sluethen** [comment]
so i can make it anywhere?

**Comment by AbrarSyed** [comment]
did you like.. not read my firest reply to you?

**Comment by Sluethen** [comment]
ok

**Comment by Sluethen** [comment]
it a dot jar or zip file?

**Comment by Sluethen** [comment]
sorry

**Comment by Sluethen** [comment]
oh nvm
