### ISSUE TITLE
Somehow passing wrong Opcode to ASM MethodVisitor

### ISSUE THREAD

**Issue by kenzierocks** [MinecraftForge/ForgeGradle#179]
It expects `Opcodes.ASM4` or `Opcodes.ASM5` and it should be getting one of those...but it doesn't.

Stacktrace + normal log: http://pastebin.com/YZneYMtX

`--debug` log (download because it's really big): https://www.dropbox.com/s/of1tx6hf8udiq35/errorlog.txt?dl=0

I have run `./gradlew setupDevWorkspace --refresh-dependencies`, and `./gradlew --version` is 
```
------------------------------------------------------------
Gradle 2.0
------------------------------------------------------------

Build time:   2014-07-01 07:45:34 UTC
Build number: none
Revision:     b6ead6fa452dfdadec484059191eb641d817226c

Groovy:       2.3.3
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0 (Oracle Corporation 25.0-b69)
OS:           Windows 7 6.1 amd64
```

**Comment by AbrarSyed** [comment]
https://github.com/MinecraftForge/ForgeGradle/blob/FG_1.2/src/main/java/net/minecraftforge/gradle/extrastuff/ReobfExceptor.java#L373

seems you have an outdated forgegradle... clean cache.. and refresh-dependencies

**Comment by kenzierocks** [comment]
It literally just updated FG when I first ran this...but okay.

**Comment by kenzierocks** [comment]
Ran `./gradlew setupDevWorkspace build --refresh-dependencies`, no change, it downloaded this:
![image](https://cloud.githubusercontent.com/assets/2093023/5693758/06d6274a-98e2-11e4-9377-196bbfd4cdc3.png)

**Comment by kenzierocks** [comment]
I opened my current FG jar, and it contains the correct Opcode. I'm going to try cleaning up ASM.

**Comment by kenzierocks** [comment]
It still wants to download ASM4 for me. Is it requesting ASM5?

**Comment by AbrarSyed** [comment]
nuke the entire .gradle/caches folder.. and then do it.  FG should be using the correct ASM and stuff then.
It should be using asm5 instead of asm4

**Comment by kenzierocks** [comment]
I did, it redownloaded ASM4 and ASM5 and proceeded to use ASM4.

**Comment by AbrarSyed** [comment]
possble, see if the forge section works alone.

**Comment by kenzierocks** [comment]
Found the culprit: the shadow plugin. I'll try forcing 5.

**Comment by kenzierocks** [comment]
Works great!
