### ISSUE TITLE
Redirect CurseUploadTask fileid to project.curse.fileid

### ISSUE THREAD

**Issue by Renkin42** [MinecraftForge/ForgeGradle#182]
This would allow users access to the file id returned by the curseforge api, potentially useful for adding download links in automated twitter or wordpress posts. I would just do a pull request, but for some reason I can't build the fork.

**Comment by AbrarSyed** [comment]
Its project.tasks.curse.fileId

**Comment by Renkin42** [comment]
Nope, doesn't work. Just tried.
```Could not find property 'fileId' on task ':curse'```
Running Forge 1180 with FG 1.2

**Comment by AbrarSyed** [comment]
Hmm, your right.. Could a sworn robotbrain made a PR for it...

**Comment by Renkin42** [comment]
So would the new syntax for the parent file id be project.tasks.curse.fileIds.get(0)?

**Comment by AbrarSyed** [comment]
Project.tasks.fileId. == parent ID
Project.tasks.fileIds == all of em.

The difference is the s at the end.
FileIds returns an array.. So do with that what you will. However I added the single version for convenience.
