### ISSUE TITLE
Minecraft 1.8 - User Properties not passing correctly

### ISSUE THREAD

**Issue by lbjdaking23** [MinecraftForge/ForgeGradle#184]
Which is resulting in the twitch auth key not getting passed correctly and just getting completely ignored. 
Took a quick look into this issue and I think I see the problem.

Based off of Minecraft 1.8 main class it is "userProperties" over "userPropertiesMap".
Code needed to be fixed -
https://github.com/MinecraftForge/ForgeGradle/blob/master/src/main/java/net/minecraftforge/gradle/tasks/CreateStartTask.java#L180

**Comment by AbrarSyed** [comment]
hmmm, gues I need to go attach my twitch account to test this...

**Comment by lbjdaking23** [comment]
In console I am seeing.
```
[net.minecraft.client.main.Main:main:59]: Completely ignored arguments: [--userPropertiesMap, [{"name":"twitch_access_token","value":"accessTokenHere"}]]
```
The access token is correct I verified just userPropertiesMap seems wrong

**Comment by AbrarSyed** [comment]
I give up on making this work... tried a bunch of things...

**Comment by AbrarSyed** [comment]
see #198
