### ISSUE TITLE
Inner class ATs are not getting applied in setupCiWorkspace but do work with setupdDecompWorkspace?

### ISSUE THREAD

**Issue by bdew** [MinecraftForge/ForgeGradle#185]
I'm trying to build [CofhLib](https://github.com/CoFH/CoFHLib) (from what it looks they are using Ant with BON, i'm trying to make it compile with gradle)

I'm running into a weird issue, if i just do a build (or setupCIWorkspace first), the following AT doesn't get applied:

> public net.minecraft.server.management.PlayerManager$PlayerInstance

And the build fails with:

> D:\mcmodding\1710\cofhlib\build\sources\java\cofh\lib\world\WorldGenMassiveTree.java:18: error: PlayerManager.PlayerInstance is not public in PlayerManager; cannot be accessed from outside package
> import net.minecraft.server.management.PlayerManager.PlayerInstance;
 
And looking at the jar in dirtyArtifacts with JD, the class is indeed package-private (no modifier). The other ATs seem to apply correctly.

But if i do setupDecompWorkspace first, it does get applied correctly and the build succeeds.

**Comment by bdew** [comment]
Here's a log of a failed build (without setupDecomp) http://jenkins.bdew.net/job/CoFHLib/4/console
And here's one of a successful build (with setupDecomp) http://jenkins.bdew.net/job/CoFHLib/6/console

Both builds are from the same exact source.

I also had another build that crashed with an NPE in robf, no idea what happened there. Possibly another bug http://jenkins.bdew.net/job/CoFHLib/5/console

**Comment by Parker8283** [comment]
This bug was fixed a while ago. Ensure you're using the latest FG 1.2.

**Comment by bdew** [comment]
It was using the latest build - http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/1.2-SNAPSHOT/ForgeGradle-1.2-20150121.195501-247.jar

**Comment by bdew** [comment]
Here's the repo with the modified script and everything if anyone wants to test it - https://github.com/bdew/CoFHLib-1

**Comment by Parker8283** [comment]
Try again, it was an issue with SpecialSource.

**Comment by AbrarSyed** [comment]
yeah was fixed with the updated SpecialSource

**Comment by AbrarSyed** [comment]
You WILL need to clean and re-setup.
As smart as gradle is, it doesnt know to redo a task when it has functionally changed.

**Comment by bdew** [comment]
Works fine now, thanks
