### ISSUE TITLE
Expand CurseForge project dependency declarations to auto-download dependency

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/ForgeGradle#190]
CurseForge provides maven access. Need to poke @ZeldoKavira about how to get to it again. We could probably use this to add a (*disableable*) feature where if the project is marked as a `requiredLibrary`, it will get auto-downloaded and added as a compile dependency.

**Comment by dmodoomsirius** [comment]
This can be closed now as https://github.com/MinecraftForge/ForgeGradle/pull/189 Fixes it @AbrarSyed

**Comment by AbrarSyed** [comment]
no.. that was for marking depndencies for uplaoding stuff to curseforge, it doesnt handle downloading dependencies from curseforge

**Comment by matthewprenger** [comment]
I know, I wrote it..... I'm saying we could expand it to use the CurseForge maven access to download the deobf/dev copy if present.

**Comment by AbrarSyed** [comment]
yeah..... dmod made a comment I was replying to...which has since been deleted.. dont mind me..
he was saying this issue could be closed.. which it cant yet.

**Comment by AbrarSyed** [comment]
as of FG2, the curseforge plugin has been removed. use mathewprengers CurseGradle instead.
