### ISSUE TITLE
IntelliJ adds wrong forgeBin jar to dependencies

### ISSUE THREAD

**Issue by Lunatrius** [MinecraftForge/ForgeGradle#191]
IntelliJ adds the wrong forgeBin jar to a module's dependencies in multi module projects with different ATs due to name collisions (the clean jar and all dirty jars have the same same).
Adding a suffix/prefix (name-version, hash of name-version, ...) should prevent that from happening.

Things still work fine as they are now, but the gradle project can't be refreshed from inside IntelliJ.

**Comment by AbrarSyed** [comment]
fixed in FG2, project cached jars now include the project name in the file name.
