### ISSUE TITLE
Dev enviroment crashes on startup with a NSME

### ISSUE THREAD

**Issue by Andre-Maartens** [MinecraftForge/ForgeGradle#192]
Every time I try to run the dev env. I get this:

 [13:54:43] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[13:54:43] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[13:54:43] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
[13:54:43] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.NoSuchMethodException: net.minecraft.client.Minecraft.main([Ljava.lang.String;)
	at java.lang.Class.getMethod(Class.java:1670) ~[?:1.7.0_75]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

How I set up my workspace:
Dl'ed latest forge src as of writing (1.7.10-10.13.2.1291)
Installed Eclipse luna sr1a-win32-x86_64
made a workspaces folder in my eclipse folder
made a forge folder in there
copied EVERYTHING from the forge src zip to the forge folder
shift+rclick run cmd here
ran with gradlew cleanCache clean setupDecompWorkspace --refresh-dependencies
failed
uninstalled all java instances
installed jdk -7u75-windows-x64
installed jre-7u75-windows-x64
appended PATH  variable with C:\Progra~1\Java\jdk1.7.0_75\bin;C:\Progra~1\Java\jre7\bin
added JAVA_HOME variable with C:\Progra~1\Java\jdk1.7.0_75;C:\Progra~1\Java\jre7
both for system and user
deleted the forge folder
copied src forge zip's contents to ..\eclipseinstalledir\workspaces\forge\
ran a cmd here with: gradlew cleanCache clean setupDecompWorkspace --refresh-dependencies
it finished
in the workspace folder made a mods folder
copied forge src zip contents to a "test" folder
edited build.gradle and changed the assetsDir to:
if (file('../run').exists()) {
	runDir = "../run/assets"
	} else {
		runDir = "assets"
	}
since i am running 1.7.10
saved
made a run folder in the mods folder
cmd'ed with gradlew cleanCache clean setupDecompWorkspace --refresh-dependencies eclipse
ran perfectly
opened eclipse and imported test
changed debug configs:
Name = test Client
Project = test
Main class = net.minecraft.launchwrapper.Launch
prog args = --version 1.0 -- tweakClass cpw.mods.fml.common.launcher.FMLTweaker --accessToken something
vm args = Dfml.ignoreInvalidMinecraftCertificates=true
working dir: other; ${workspace_loc}\run
applied and saved and hit debug and then the crash came
P.S. I have followed @LexManos 's Tutorials @youtube
https://www.youtube.com/watch?v=8VEdtQLuLO0
and
https://www.youtube.com/watch?v=xp2jmt47yTQ

**Comment by AbrarSyed** [comment]
1) you clean cache way too often
2) main class is wrong, it should he GradleStart with no extra arguments
3) the rundir should not be an assets folder. The assets folder should be inside the runDir.
4)just run setupDecompWorkspace again alone and everything should be fine.

Lex's video is outdated.

**Comment by Andre-Maartens** [comment]
Thanks
