### ISSUE TITLE
1.7.10 artifact naming change

### ISSUE THREAD

**Issue by chrixian** [MinecraftForge/ForgeGradle#194]
I use a gradle task to manage checking for new versions of forge and then optionally update if a new version is available... normally it works fine but starting with 1300 for 1.7.10 the branch listed in the artifact json you make available went from 'null' to '1.7.10' and this branch is now being appended to the artifact filenames being published ... so when I use the normal naming pattern and try to grab "forge-1.7.10-10.13.2.1307-src.jar" it fails since the file is now named "forge-1.7.10-10.13.2.1307-1.7.10-src.jar". (This has also caused the "1.7.10-Latest" displayed on the front page to remain at 1291 since it only displays the main branch promotions)

Mainly I was just wanting to a) make sure you guys were aware of this happening now and b) find out if ForgeDevPlugin will be changed to no longer append the branch to the version string it supplies for published filenames or if I have to worry about handling the special case of how the files are named for post 1300 1.7.10 builds? Thanks!

**Comment by LexManos** [comment]
yes, you need to specify the branch if you want to use a version of forge that is in a branch.
This is how maven works.

**Comment by chrixian** [comment]
I think I worded this poorly so I'll take one more stab at it (I'm sure you're rolling your eyes already but humor me for 2 minutes) ... 

Ultimately my point is: wouldn't it be desirable/advantageous to keep a consistent format for the version string used in the minecraft block of the gradle build? The versioning scheme you use for Forge already uniquely identifies an artifact as to its minecraft version (under normal circumstances) without the need for the branch appended to the end (again, under normal circumstances) and creates an unnessesary headache.

For example: random developer updates his build.gradle file after checking the latest available version on the website, he goes from "1.7.10-10.13.1.1222" to "1.7.10-10.13.2.1270" to "1.7.10-10.13.2.1291" with no problems and then all of a sudden builds fail when updating to "1.7.10-10.13.2.1343" because randomly the version has to be identified as "1.7.10-10.13.2.1343-1.7.10" when the former could have remained valid and correct. (fast forward to when 1.8 is in it's own branch and 1.9 is in master and the scenario repeats itself)

Surely, you can see the benefit of consistency here? It's not a big change, just modify `getVersionFromJava` in `ForgeDevPlugin` to look for some flag (like a project property or environment variable) to determine whether or not to include the branch in the version string it returns (that way atypical situations where the branch *is* needed are easily handled) and when that flag isn't set, which it wouldn't be by default, don't include the branch in the version string.

You dig? Oh I know you do. :heart:

**Comment by AbrarSyed** [comment]
http://forgegradle.readthedocs.org/en/latest/reference/mcblock/

See setVersion()

ForgeGradle is smart in how it actually gets the version now, hopefully that's better. As for branch, I guess I can make that easier in the future.
