### ISSUE TITLE
Change the sourceCompatibility to 1.7 or 1.8

### ISSUE THREAD

**Issue by da3dsoul** [MinecraftForge/ForgeGradle#199]
Target can stay at 1.6, but everyone should have 1.7 by now, as everyone (Forge, Mojang, mod devs) is telling them to.

**Comment by LexManos** [comment]
No. We'll change when we are allowed to.

**Comment by da3dsoul** [comment]
Allowed to?

**Comment by AbrarSyed** [comment]
When we can guarantee that all users will have java 7.
