### ISSUE TITLE
Forge Gradle FAILED at :makeStart

### ISSUE THREAD

**Issue by KeddoXZ** [MinecraftForge/ForgeGradle#200]
Here is the log from the error: http://pastebin.com/HGtvpZ3P
Looked up for some help from here https://github.com/MinecraftForge/ForgeGradle/issues/110
Used this to try fixing the error "gradlew clean setupDec
ompWorkspace --refresh-dependencies --stacktrace"
I have Java 7 Update 75 and Java SE Developement Kit 7 Update 75 installed.

**Comment by cazzar** [comment]
From the log

* What went wrong:

Execution failed for task ':makeStart'.

> Cannot find System Java Compiler. Ensure that you have installed a JDK
(not just a JRE) and configured your JAVA_HOME system variable to point to
the according directory.

**Comment by KeddoXZ** [comment]
Tried making JAVA_HOME variable that did not work for me so I reinstalled java and it created the variable which made it to finish it successfully.
