### ISSUE TITLE
Reobfuscation failure

### ISSUE THREAD

**Issue by rallias** [MinecraftForge/ForgeGradle#202]
This morning I woke up to a reobfuscation failure on ForgeGradle for 1.7.10.

    Download http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/1.2-SNAPSHOT/ForgeGradle-1.2-20150309.045226-266.jar
    ****************************
     Powered By MCP:             
     http://mcp.ocean-labs.de/   
     Searge, ProfMobius, Fesh0r, 
     R4wk, ZeuX, IngisKahn, bspkrs
     MCP Data version : unknown
    ****************************
    :compileApiJava UP-TO-DATE
    :processApiResources UP-TO-DATE
    :apiClasses UP-TO-DATE
    :sourceMainJava
    :compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: /home/rallias/Dev/Nuclear-Control-3/build/sources/java/com/jadarstudios/developercapes/cape/CapeConfigManager.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    1 warning

    :processResources UP-TO-DATE
    :classes
    :jar
    :compileTestJava UP-TO-DATE
    :processTestResources UP-TO-DATE
    :testClasses UP-TO-DATE
    :test UP-TO-DATE
    :extractMcpData UP-TO-DATE
    :getVersionJson
    :extractUserDev UP-TO-DATE
    :genSrgs SKIPPED
    :reobf FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':reobf'.
    > java.lang.ClassNotFoundException: ic2.api.network.NetworkHelper

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 1 mins 37.015 secs

This was corrected by running gradle tasks clean, cleanCache, and setupDecompWorkspace. The above log pertains to the repo at https://github.com/rallias/nuclear-control

**Comment by cazzar** [comment]
This from discussion on IRC seems not localised to just rallias here, but a
few others. - just a FYI

**Comment by McJty** [comment]
I get a similar error. For me it is:

* What went wrong:
Execution failed for task ':reobf'.
> java.lang.ClassNotFoundException: net.minecraft.world.WorldServer

**Comment by rallias** [comment]
^ To that effect, relevant IRC logs.

    <covers1624> Can anyone here help me with gradle i have tried on #ForgeGradle with no response.
    <Rallias> What's your issue?
    <covers1624> reobf ClassNotFound net.minecraft.item.ItemStack
    <McJty> I have a similar problem but with another class.
    <McJty> For me it is WorldServer
    <McJty> this problem started today
    <Rallias> I just had that issue.
    <Rallias> Doing a cleanCache and setupDeobfWorkspace fixed it for me.
    <covers1624> have tried on 3 computers and even cleaned cache
    <covers1624> im still on 1.7 btw
    <Rallias> (and here I thought it was something to do with IC2, my issue touched     ic2.api.network.NetworkHelper)
    <Rallias> Yeah, I did clean, cleanCache, and setupDeobfWorkspace
    <covers1624> i am doing gradlew cleancache setupDecompWorkspace build
    <covers1624> waht Forge Gradle version are you using?
    <Rallias> It pulled a new one on me today and I don't have the build log anymore.
    <Cazzar> okay, you guys tried --refresh-dependencies?
    <covers1624> yep.
    <covers1624> can send you log
    <Rallias> It pulled ForgeGradle-1.2-20150309.045226-266.jar
    <Rallias> Try ./gradlew clean cleanCache setupDeobfWorkspace
    <Cazzar> well, maybe put a issue on GH since I am on my phone, and it'll notify abrar.
    <covers1624> i only put gradlew in there not gradlew.bat because i have cygwin
    <Cazzar> windows auto looks for some extensions.
    <McJty> Task 'setupDeobfWorkspace' not found in root project 'RFTools'. Some candidates are: 'setupDecompWorkspace', 'setupDevWorkspace'.
    <Cazzar> soo it is probably running the .bat
    <McJty> Can't find setupDeobfWorkspae for me
    <Rallias> Er yeah, it is decompworkspace.
    <covers1624> setupDecompWorkspace
    <Rallias> Sorry.. for me it's a button.
    <Cazzar> Gradle clean cC sDecW for me.
    <covers1624> Cazzar you are a dev for FG right? or just a op in #ForgeGradle
    <Cazzar> technically just help people in most cases, I don't develop FG
    <covers1624> roger.
    <Cazzar> though I am one of few that will 90% of the time know what the issue is with working out gradle
    <covers1624> ok trying clean cC sDevW build now
    <Cazzar> you know that's just shorthand "clean cleanCache setupDevWorkspace build" right? :P
    <covers1624> yeah
    <covers1624> i couldent be botherd typing it all its 12:30 AM here
    »» kroeser|away is now known as kroeser
    <Cazzar> south aus?
    <covers1624> yep
    <McJty> It worked!
    <Rallias> Issue submitted.
    <Cazzar> heh, im in Vic.
    <covers1624> and it failed
    <covers1624> oh hey over there
    »» Cazzar waits for the email
    <Cazzar> there we go.
    <covers1624> i can give you pastebin of error
    <Rallias> https://github.com/MinecraftForge/ForgeGradle/issues/202
    <McJty> Ah no. I still have the same error too

**Comment by matthewprenger** [comment]
b5e593e582f8392f9baab3c59b00fb3485a44c17 Appears to be the cause of it.

**Comment by covers1624** [comment]
i get similar issue only that is is ItemStack that cant be found, Gradle log: http://pastebin.com/mfcBKA6K
