### ISSUE TITLE
Manifest stripped from reobfed JAR

### ISSUE THREAD

**Issue by octarine-noise** [MinecraftForge/ForgeGradle#203]
I changed some of my code recently, but left **build.gradle** unchanged. After building my project, the **MANIFEST.MF** file was missing from the reobfed JAR. The **build/tmp/jar** directory has it, the **build/tmp/reobf/toObfXXXX.jar** file has it too, but it's missing from the final one.

Since my build script did not change, I got suspicious, and tried pulling an older build of ForgeGradle out of my local gradle cache and using it to build my project.
**ForgeGradle-1.2-SNAPSHOT** from **2015.02.24** (don't have build num, sorry) works fine, result JAR has manifest.
**ForgeGradle-1.2-SNAPSHOT** from **2015.03.09** strips manifest from JAR.

Is this a bug, or some change I'm unaware of?

**Comment by cazzar** [comment]
You should specify the manifest in both jar tasks, what you could do is add
a global variable with the map for the manifest, then reference it in both
jar tasks.

**Comment by octarine-noise** [comment]
Fastest fix ever. Thx!

**Comment by octarine-noise** [comment]
Could you force a build, please? Latest FG in the repo (build 268) does not have the fix yet, and this prevents me from using Jenkins.

**Comment by AbrarSyed** [comment]
That build has the fix. Be sure to run with --refresh-dependencies and clean before building again. If it's nky fixed, then the commit I linked didn't fix the issue, and that's extremely unlikely.

**Comment by octarine-noise** [comment]
Sorry, false alarm. Derp. It works now.
