### ISSUE TITLE
[1.7.2]Suddenly can't build workspace

### ISSUE THREAD

**Issue by WeAthFoLD** [MinecraftForge/ForgeGradle#206]
For some reasons our dev is still in 1.7.2 workspace. Everything works fine until I(And everyone else in my team) encountered the following problem yesterday:
In MakeStart phase, gradle says that 5 classes can't be found, including Property, PropertyMap in com.mojang.authlib.
I wonder if this is a mistake while you are doing new version upgrades.
Can you fix them plz? We may still be using 1.7.2 forge for a short duration, thanks ^^

**Comment by AbrarSyed** [comment]
c38b09ab5a4085e520d2fc97e12d1d19daa1ad10

just --refresh-dependencies and everything should work.
