### ISSUE TITLE
Access denied when trying to do 'setupDecompWorkspace' 

### ISSUE THREAD

**Issue by NATSOFT** [MinecraftForge/ForgeGradle#208]
Command used: gradle setupDecompWorkspace eclipse --refresh-dependencies -i

        Resource missing. [HTTP GET: http://files.minecraftforge.net/maven//forgeSrc/1.7.2-10.12.2.1121/forgeSrc-1.7.2-10.12.2.1121.pom]
        Resource missing. [HTTP HEAD: http://files.minecraftforge.net/maven//forgeSrc/1.7.2-10.12.2.1121/forgeSrc-1.7.2-10.12.2.1121.jar]
        Resource missing. [HTTP GET: https://repo1.maven.org/maven2//forgeSrc/1.7.2-10.12.2.1121/forgeSrc-1.7.2-10.12.2.1121.pom]
        Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2//forgeSrc/1.7.2-10.12.2.1121/forgeSrc-1.7.2-10.12.2.1121.jar]
        Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://libraries.minecraft.net//forgeSrc/1.7.2-10.12.2.1121/forgeSrc-1.7.2-10.12.2.1121.pom]

How could this be corrrect?

**Comment by AbrarSyed** [comment]
Eclipse task must be invoked in a separate gradle command.
