### ISSUE TITLE
Gradle closes running command window?

### ISSUE THREAD

**Issue by 61352151511** [MinecraftForge/ForgeGradle#209]
Either I'm doing something wrong or gradle decides to close the command window when in a .bat file. Here's my .bat code

http://pastebin.com/ssCEty3H

In my test scenario build.properties did not exist in Random Utilities 1.8, so %exitcode%==2 was run, the build.properties was successfully copied, gradle runs clean, setupDecompWorkspace, then eclipse, then the command window closes and the file stops. If I run the exact same commands in a command window normally it works fine, it's just when running it from a .bat file, if I've messed something up please point it out to me.

**Comment by AbrarSyed** [comment]
Dunno why gradle doesnt like bash files... but it aint my problem. Perhaps file an issue with Gradle itself.

You are not the first,. nor likely to be the last that has found that gradle likes ignoring the pause command for some reason...

**Comment by 61352151511** [comment]
It might have something to do with me having version 1.11 of gradle, the latest is 2.3, I tried updating the wrapper.properties file but it just reverts it to 1.11, any idea why? And how do I update the gradle wrapper it uses.

**Comment by AbrarSyed** [comment]
could just locally install gradle...   no idea why that doesnt work though...
