### ISSUE TITLE
Unable to start server in development environment

### ISSUE THREAD

**Issue by master801** [MinecraftForge/ForgeGradle#211]
When I was developing a core-mod for a server, this error occured: http://pastebin.com/RgTHLZbx

I was testing how this error occured, I tried everything from reinstalling my IDE, and redownloading FML/Forge/ForgeGradle.

Nothing has worked so far, however I hope that this issue will be resolved soon.

--
How to produce the issue: Run a server in a development environment.
EDIT I should mention that I'm using ForgeGradle version 1.2 snapshot.

**Comment by AbrarSyed** [comment]
30b8aacd320c2b5a773cf3bb655f6941a553150c
