### ISSUE TITLE
Clojure Support 

### ISSUE THREAD

**Issue by Immortalin** [MinecraftForge/ForgeGradle#213]
Hi,  can you add modding support for Clojure via Leiningen? Thanks in advance!

**Comment by AbrarSyed** [comment]
no.
FML currently supports only Java and Scala (not groovy kotlin Jython jRuby or closure).
As for using ForgeGradle with closure?? itl probably work out of the box.. By all means try, but that doesnt mean itl work with FML at runtime.

for using Clojure with gradle:  https://github.com/clojuresque/base
