### ISSUE TITLE
Curse uploads to multiple projects?

### ISSUE THREAD

**Issue by MrTJP** [MinecraftForge/ForgeGradle#214]
For mods that have modules split between multiple jar files,  they each need their own independent project on curse. Is there currently a way to do so within a single gradle script?

**Comment by Lunatrius** [comment]
When FG didn't have the subfiles yet I used [this](https://gist.github.com/138442b95f42d1ff44d2) for subfiles. With a few tweaks it should upload the different modules to different projects.

**Comment by AbrarSyed** [comment]
the curse plugin adds a single type of task (the curse upload task) and adds only 1 of those to the project by default. you can add your own like so...

```
task curseMyOtherProject(type: CurseUploadTask) {
    dependsOn 'reobf'
    artifact = someJar
    addGameVersion project.minecraft.version
}
```

more docs can be found here: https://github.com/matthewprenger/ForgeGradle/blob/0e4deda9a7b81f6ba01960141016991c5fe2847f/docs/user-guide/curseforge.md
Atleast until I pull it into the proper documentation page

**Comment by matthewprenger** [comment]
@MrTJP I recently released [CurseGradle](https://github.com/matthewprenger/CurseGradle). It will allow you to define multiple projects within the `curseforge` block.
