### ISSUE TITLE
bash gradlew eclipse yeilds no result

### ISSUE THREAD

**Issue by Nutzchannel** [MinecraftForge/ForgeGradle#215]
Hi, I'm trying to begin development for a mod and _tried_ to run ```bash gradlew eclipse```.
It tells me the build is successful, but when I look in my ```/eclipse/``` folder there's nothing there.
Running the latest Java JDK on a MacBook Air (2014 or so model). Any help?
(By the way, forge 1.8-11.14.1.1337, fresh from files.minecraft-forge.net)

This also happens on my Windows machine. Runs ```gradlew.bat eclipse``` with ```BUILD SUCCESS```, but the eclipse folder has only a ```.metadata``` folder and _nothing else.*_ Both don't give any sort of package explorer in Eclipse (works in my other mods, but not new ones.)

Thanks for ~~listening to~~ _reading_ my ramble.

*UPDATE: that was just the one project it still does nothing???

**Comment by AbrarSyed** [comment]
There isnt supposed to be anything there. Gradle generates an eclipse **project** in the same folder as the build.gradle. The eclipse folder shipped in the Forge src package is a packaged workspace for the lazy; It is not generated by gradle at all.

You should instead use a different eclipse workspace somewhere on your computer, and then import the generated project as an existing eclipse project (after running `gradlew eclipse` of course). The create your own run configs. The run configs are easy, just need to specify the main class to GradleStart and GradleStartServer for the client and server respectively.

**Comment by Nutzchannel** [comment]
ah ok so my eclipse was just being weird :P
