### ISSUE TITLE
Docs Typo

### ISSUE THREAD

**Issue by Draco18s** [MinecraftForge/ForgeGradle#217]
On http://forgegradle.readthedocs.org/en/latest/reference/mcblock/
There is a typo under source replacement, which separates a key:value pair with a comma.

I'd edit the file, but the link that says "edit on github" takes me to this Git repo which does not appear to contain the doc file at all.

**Comment by AbrarSyed** [comment]
The docs for the master branch dont exist just yet because is ForgeGradle 2.0 is still under development. Change the branch to FG_1.2 and youl see the docs folder there.

**Comment by Draco18s** [comment]
Oh ho, that'd do it.  Thanks!
