### ISSUE TITLE
Add Annotation Processor

### ISSUE THREAD

**Issue by killjoy1221** [MinecraftForge/ForgeGradle#221]
Based on this: https://github.com/killjoy1221/Kappa

Making this so you remember to do it.

Edit: I split the repo. Enabling is located at https://github.com/killjoy1221/ap-ide

**Comment by luacs1998** [comment]
AFAIK javac will automatically look for any annotation processors on the compile class path, so there isn't a need to add specific support.

**Comment by AbrarSyed** [comment]
I know. Its... idk.. I ahevtn looked into anything yet.. this is just a reminder to look into this stuff

**Comment by luacs1998** [comment]
Yeah, but I use multiple annotation processors in gradle (mixin and hibernate-jpa) and they all work without intervention in the build.gradle.

It should be simple enough to just have a compile dependency added for those who want to use the AP in their projects.

**Comment by AbrarSyed** [comment]
Except lex wants this to affect all the projects. Hence integration into FG somehow..

**Comment by killjoy1221** [comment]
They work in javac and gradle, but not in your IDE. Mumfrey made a video which briefly explained how to enable it in eclipse. The gradle subproject is a plugin that does this automatically for eclipse and IntelliJ.

**Comment by AbrarSyed** [comment]
ooohhh, if we can do that, we can force lombok too... 
* rubs hands together*
oh but then they  need the lombok plugin.. nevermind,...

**Comment by killjoy1221** [comment]
The thing with that.. if they have an annotation processor anywhere on their compile classpath, it will be added to the aptCompile classpath automatically. If they have no processors, the task will be skipped.

**Comment by LexManos** [comment]
If we can find a way to get IDE integration there are quite a few processors I will add.
But the thing is the IDE integration...

**Comment by killjoy1221** [comment]
I should mention a thing I learned while messing with eclipse's apt. Any libraries you reference in a processor also have to be on the factory classpath. I tried to use Gson and everything broke. I'm not sure about Idea, but I'm certain that it does the classpath automatically.

**Comment by SizableShrimp** [comment]
This is quite old. Not sure what this is. Feel free to update it to FG5 if still something that we could find use out of.
