### ISSUE TITLE
setupDevWorkspace injects illegal ACC_SUPER flags on inner class attributes

### ISSUE THREAD

**Issue by jk-5** [MinecraftForge/ForgeGradle#222]
For reference, see https://github.com/SpongePowered/Mixin/issues/45

Inner class attributes may not have these flags. Normally, nobody would notice, but because the mixin library uses asm's CheckClassAdapter to validate generated bytecode, i was notified of this issue. Not really sure if this is an issue of ForgeGradle itself or an issue of MCInjector, so i'm opening it here.

**Comment by LexManos** [comment]
https://github.com/ModCoderPack/MCInjector/commit/05aa80e569728813c9618da86eed8afbe11154ea
