### ISSUE TITLE
MinecraftForge - Skype API error

### ISSUE THREAD

**Issue by rikrobots** [MinecraftForge/ForgeGradle#223]
Hello, my name is rik and im trying to make a mod that allows the player to receive skype messages in his mc chat.
But there is a problem im trying to use the Skype-Java-API and it works on debug but now i'm trying to build it.
But it gives a error:
http://prntscr.com/76ars9
I hope someone can i help me with it (Sorry if my grammer/language is incorrect im 14 year old and dutch so yeah..)

**Comment by jk-5** [comment]
Either place the skype api jar in the 'libs' folder or add it as a maven dependency in build.gradle.
The issue is that gradle can't find the skype library.

**Comment by AbrarSyed** [comment]
http://gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html

https://search.maven.org/#artifactdetails%7Ccom.github.taksan%7Cskype-java-api%7C1.7%7Cjar
```
dependencies {
    compile 'com.github.taksan:skype-java-api:1.7'
}
```

https://forgegradle.readthedocs.org/en/FG_1.2/user-guide/shading/

**Comment by diesieben07** [comment]
You need to declare dependencies in the build.gradle properly, not just tell your IDE about them.
