### ISSUE TITLE
Forge Gradle 2.0 IDEA

### ISSUE THREAD

**Issue by Prototik** [MinecraftForge/ForgeGradle#224]
IntelliJ IDEA cannot import project into workspace:
![screenshot from 2015-05-21 14-40-09](https://cloud.githubusercontent.com/assets/1416030/7743690/fbee82fc-ffbe-11e4-9bde-895175a0423b.png)

**Comment by AbrarSyed** [comment]
I use linux, its a case sensitive file-system, and it works fine for me.. Looking at the code as well, it uses all the capitalized names correctly. Perhaps you just need to clean out the workspace and setup again? Maybe also add a --refresh-dependencies to be sure you are using the latest ForgeGradle.

**Comment by AbrarSyed** [comment]
A quickfix is to add the content root manually. Its somewhere in the project properties...

**Comment by thomas15v** [comment]
Any ETA on this?

**Comment by LexManos** [comment]
It would be useful for me as well so you should probably do this.
Worst case you could always symlink things in :P

**Comment by Lunatrius** [comment]
This should be [fixed in IDEA 15.1](https://youtrack.jetbrains.com/issue/IDEA-122577), no ETA on the release though.

**Comment by AbrarSyed** [comment]
Fixed in the Idea 16 EAP apeprantly according to @matthewprenger

**Comment by matthewprenger** [comment]
Yeah it works out of the box with Idea 16. Important note: Don't open the `.ipr` file, instead import the `projects/build.gradle` file.
