### ISSUE TITLE
Problems using "runClient" on Windows 10.

### ISSUE THREAD

**Issue by halvors** [MinecraftForge/ForgeGradle#233]
When trying to run "gradle runClient" on Windows 10. Somehow the classes aren't present at runtime.

I've built my mod manually in IntelliJ using a simple application run configuration, on Travis-CI and built it with "gradle build" and loaded on a Minecraft instance. Everything works fine except "gradle runClient".

Here is the error i'm getting.
http://pastebin.com/vhjHVPWD

And again, yes "org.halvors.electrometrics.common.tile.machine.TileEntityElectricityMeter" is present in the built JAR.

So this somehow seems to be related to Windows 10...

**Comment by AbrarSyed** [comment]
Its impossible that windows 10 is involved... Java was designed to be platform independant.. If anything, something is derped with your install of java, but thats also extremely unlikely.

**Comment by cpw** [comment]
Dude. Why would win10 decide to nuke one *specific* class out of dozens?

A crash report isn't helpful. Upload logs with the full monty of classpath debugging enabled:

-Dlegacy.debugClassLoading=true -> upload the fml-client log file...
