### ISSUE TITLE
Forge is failing to build on jenkins - problem with a bootstrap gradle init file fixing boot Java library for 1.6

### ISSUE THREAD

**Issue by cpw** [MinecraftForge/ForgeGradle#240]
Forge is failing to build on jenkins. It works fine on my local environments, using the exact same commands. It's very odd - I think it might be related to the sourceCompatibility level in FG2..

Gist of the log here: https://gist.github.com/cpw/2243f62a8a406d33ed84

The problem seems to be that it's using java 1.5 compatilibilty level (note the lack of warnings about java 1.6 compatibility in the compile section, where it fails). It should also be noted, I have to force GRADLE_OPTS=-Dfile.encoding=UTF-8 because otherwise the daemon seems to pick up US-ASCII, which is completely wrong.

**Comment by AbrarSyed** [comment]
Seems like overmind added a build slave on a misconfigured box?
Its also worth mentioning that the project compile tasks are subject to any initscripts that are specified at the user and system levels (not ones passed into the CLI).

**Comment by cpw** [comment]
It's been this way for about a year or more dude. Nothing has changed in forever. Something specific with how you launch the gradle daemon seems to be causing an issue that wasn't present with the older FG1.x way of doing things.

**Comment by cpw** [comment]
How much testing with java 6 have you done? The only candidate I can find, is one to set the bootpath in case of targetcompat == 1.6. I've just confirmed, this breaks the build:
```
allprojects {
        afterEvaluate {
                tasks.withType(JavaCompile) { task ->
                        if (task.targetCompatibility == '1.6')
                        {
                                task.options.fork = true;
                                task.options.bootClasspath = "/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/rt.jar"
                        }

                }

        }
}
```

**Comment by cpw** [comment]
Having researched this some more, I don't get why FG1.2 ever worked. This is supposed to extend the bootclasspath, not fully replace it. I'm gonna call it a bug in the jenkins env. No idea why it ever worked before to be honest, now I'm looking at it. @LexManos any ideas on why this script was added?

**Comment by LexManos** [comment]
It was added because @AbrarSyed made FG's builds fail with errors if the boot classpath was not set so this was a hack around to fix it that he said to do.

**Comment by AbrarSyed** [comment]
Its not a hack, its actually the proper (and only) way to set th ebootstrap classpath in gradle.. But yeah, I wont have time to debug this until sunday. Work and stuff.

**Comment by LexManos** [comment]
Use a proper version that adds more than just the rt.jar, we're good to go now.

**Comment by AbrarSyed** [comment]
for future reference: https://gist.github.com/AbrarSyed/9440192
