### ISSUE TITLE
setupCIWorkspace creates classes with inexistent inner classes

### ISSUE THREAD

**Issue by Minecrell** [MinecraftForge/ForgeGradle#244]
Using `setupCIWorkspace` on the `tweaker-server` plugin creates classes where inner classes are referenced that actually don't even exist in the created JAR:

Here is an example, the class header from `Block` in the created JAR:

![](https://i.imgur.com/caGJYMr.png)

... and `Block$EnumOffsetType` doesn't exist inside the created JAR:

![](https://i.imgur.com/2WXWP3m.png)

This is probably not a problem for `setupDecompWorkspace` because recompilation removes the inner class, however it is causing the compilation to fail on CI servers for some projects because itis trying to find the class: https://travis-ci.org/SpongePowered/SpongeCommon/jobs/77010585#L446-L449

```
error: cannot access EnumOffsetType
  class file for net.minecraft.block.Block$EnumOffsetType not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for net.minecraft.block.Block$EnumOffsetType not found
1 error
:compileJava FAILED
```

**Comment by AbrarSyed** [comment]
After some debugging I have found that the that specific enum class is not in the server jar at all. It could be that the exceptor is adding the reference to the class even though the class itself doesnt exist. 

Unfortunately this isnt really a problem i can fix... The exceptor (McInjector) is something I dont know anything about, nor have any desire to touch. If possible, I ask that you guys fix it from your end.

**Comment by LexManos** [comment]
The enum exists as we should be inerged space here, nothing to do with the server or client seperation anymore

**Comment by Minecrell** [comment]
The problem this is causing is basically not only affecting the Mixin annotation processor, but basically every annotation processor trying to collect information about the classes with the bad inner classes. For example, if an annotation processor is trying to check which methods/fields exist in one of these classes it will print this error because it is trying to load the inner class too:

```java
TypeElement element = processingEnv.getElementUtils().getTypeElement("net.minecraft.block.Block");
System.out.println(element);
for (Element e : element.getEnclosedElements()) {
        System.out.println(e);
}
```
Results in:
```
error: cannot access EnumOffsetType
  class file for net.minecraft.block.Block$EnumOffsetType not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for net.minecraft.block.Block$EnumOffsetType not found
1 error
```
