### ISSUE TITLE
[FG2] Cannot add task ':eclipse'

### ISSUE THREAD

**Issue by iLexiconn** [MinecraftForge/ForgeGradle#245]
I get this error when I try to import my FG2 prject into eclipse. (The build.gradle file in the projects/ dir)

https://media.ilexiconn.net/cytu0nru.png

**Comment by AbrarSyed** [comment]
need more info, specifically your build.gradle

**Comment by AbrarSyed** [comment]
unable to reproduce this...

**Comment by AbrarSyed** [comment]
well then.....
