### ISSUE TITLE
Eclipse .project missing.

### ISSUE THREAD

**Issue by JBelCOOL** [MinecraftForge/ForgeGradle#249]
I have downloaded the latest source for minecraft Forge 1.8-11.14.3.1505 (the MDK download) and run
    ```./gradlew setupDecompWorkspace```
    ```./gradlew eclipse```
Both completed without problems, but when I set my eclipse workspace to /eclipse/ it tells me the .project file is missing.
I have tried deleting everything and reinstalling, to no avail, what do I do?

**Comment by AbrarSyed** [comment]
@cpw I thaught we fixed this...

**Comment by cpw** [comment]
Try 1506

**Comment by JBelCOOL** [comment]
Thanks.
