### ISSUE TITLE
gradlew setupCIWorkspace build causes errors.

### ISSUE THREAD

**Issue by LordMastodon** [MinecraftForge/ForgeGradle#252]
Running gradlew setupCIWorkspace build in 1506 causes errors both on a normal computer and on a dedicated Drone server. Here is a link to the full error report from the Drone server: http://pastebin.com/zM62QXwJ. Here is a link to the repository containing the build.gradle file: http://github.com/LordMastodon/Miscal. Side note: I have added a task into the build.gradle called "version" which creates a .txt file in the output with the version number that my mod can download and check for new versions, but testing with and without that task in the command does not seem to affect anything. I'm not sure if this is a bug or an unimplemented feature, but diesieben07 recommended I post a bug report, so here I am. Thank you in advance!

P.S.

It's also worth noting that the Drone server runs on Ubuntu and my computer runs on Windows, making it impossible to fully recreate the situation on my computer, however the crash report seems exactly the same, so I'm pretty sure there's no conflict there.

**Comment by matthewprenger** [comment]
`setupCIWorkspace` and `setupDevWorkspace` both seem to be broke. (Verified with the latest MDK download) A workaround is to use `setupDecompWorkspace`.

**Comment by LordMastodon** [comment]
OK, is Forge working on a fix?

**Comment by AbrarSyed** [comment]
Hey Mathew, is it the same error? With the ATs that's the issue? Or do the bin workspaces have a different issue?

On August 31, 2015 11:10:10 AM PDT, LordMastodon <notifications@github.com> wrote:
>OK, is Forge working on a fix?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/MinecraftForge/ForgeGradle/issues/252#issuecomment-136449740

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LordMastodon** [comment]
The crash report says "127 Broken Access Transformer lines" meaning, yes, it's probably an AT issue. These are definitely Forge's fault and not mine, seeing as I don't use Access Transformers and certainly not 127 line's worth of them.

**Comment by AbrarSyed** [comment]
There are a gee options...
1) ensure you are using the 2.0.1 stable
2) if that doesn't work try the snapshots.
3) last resort use this to ignore the error: ``` deobfMcMCP.failOnAtError = false ```

**Comment by LordMastodon** [comment]
Well, my build.gradle says I'm using ForgeGradle-2.0-SNAPSHOT. If I replace that with ForgeGradle-2.0.1 the same thing happens. Where should I put that line to get it to compile? It also seems to me like doing that might cause problems with compilation if I actually distribute it and put it into a Minecraft install...

**Comment by AbrarSyed** [comment]
Hmmm, dont just silence the error.. It would likely stop you from being able to compile..
I'll try and debug tomorrow..

**Comment by LordMastodon** [comment]
Thanks.

**Comment by LordMastodon** [comment]
setupCIWorkspace seems to broken in the stable versions as well.

**Comment by LordMastodon** [comment]
What info should I add? Anything you need I'll try to obtain in order to solve this.

**Comment by AbrarSyed** [comment]
Nope, nothing from you. This time I added the label as a reminder for myself to debug it.

**Comment by LordMastodon** [comment]
Ahh. Well, how's it going?

**Comment by LordMastodon** [comment]
Also, as a side note, it gave me this error using setupCIWorkspace and 1512: Could not resolve all dependencies for configuration ':forgeGradleMcpData'.
> Could not download mcp-srg.zip (de.oceanlabs.mcp:mcp:1.8)
   > Could not get resource 'http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.8/mcp-1.8-srg.zip'.
      > Could not GET 'http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.8/mcp-1.8-srg.zip'.
         > Connection to http://files.minecraftforge.net refused

**Comment by AbrarSyed** [comment]
I honestly have no idea why this isnt working.. did SPecialSource break or something??

**Comment by LordMastodon** [comment]
Yay! What should I do?

**Comment by AbrarSyed** [comment]
waiting on md-5/SpecialSource#33

**Comment by Minecrell** [comment]
@AbrarSyed Wasn't it merged already? https://github.com/md-5/SpecialSource/commit/fcd1c49bb7ff742d23b838865bb057fc41d83b4c The PR wasn't closed but it seems to be in master

**Comment by AbrarSyed** [comment]
hah, didnt see that.. fix incomming.

**Comment by AbrarSyed** [comment]
a5509a29631c6ced1a7ffc2080652d76c66ce5c5
