### ISSUE TITLE
Add line numbers to recompiled source.

### ISSUE THREAD

**Issue by kenzierocks** [MinecraftForge/ForgeGradle#254]
For debugging.

**Comment by LexManos** [comment]
Explain, when you recompile the lines are included.

**Comment by kenzierocks** [comment]
Not according to Eclipse, running with a breakpoint makes it produce an error message. I do have source, so I have a successful decomp workspace.

**Comment by LexManos** [comment]
What library is it saying that Minecraft's code is in, what is the file name?
When you setup a decomp workspace it decompiles minecraft, patches it, and recompiles it into a jar so it should be fine.
Beyond that, vanilla includes line numbers just fine as well...
So... you're going to have to be more specific what do you mean by errors. 
Logs, logs always logs.

**Comment by cpw** [comment]
Make sure you have refreshed your eclipse projects after the update. (Delete from workspace and reimport, or use the newly built eclipse workspace in your clean dir, and import your code in).. The pre-fg2 projects might not be 100% good with the new layout..

**Comment by kenzierocks** [comment]
This is a brand new project, so no pre-fg2 stuff.

**Comment by cpw** [comment]
Your error is exceptionally unclear then. What's the error from eclipse? Do you have some funky workspace level settings meaning you strip debug symbols?

**Comment by kenzierocks** [comment]
Here's logs: https://gist.github.com/kenzierocks/da4e8cf94dc04332634f
Here's the file that is declared as forge-<whatever>.jar: `/Users/kenzietogami/.gradle/caches/minecraft/net/minecraftforge/forge/1.8-11.14.3.1506/stable/16/forgeSrc-1.8-11.14.3.1506.jar`
And the attached sources are `/Users/kenzietogami/.gradle/caches/minecraft/net/minecraftforge/forge/1.8-11.14.3.1506/stable/16/forgeSrc-1.8-11.14.3.1506-sources.jar`
Here's the error I get, it's not instantly after it starts but a little bit later. ![error.png](http://i.imgur.com/mBZFZsS.png)

I don't strip debug symbols to my knowledge. ![debug.png](http://i.imgur.com/w0v2GOG.png)

**Comment by LexManos** [comment]
Post your gradle logs. Gradle is the one that recompiles it, if your system is setup to strip everything then it will.
However java's default setup maintains line numbers so something is special on your end.

**Comment by kenzierocks** [comment]
Gradle logs with `--debug` and after `gradle clean cleanCache`: https://gist.github.com/8d55bfc2937f80214c19 (warning, very large)

**Comment by kenzierocks** [comment]
It does look like `ant:javac` is picking up on `-g:none` somewhere. I don't think I have anything configured to that aspect.

**Comment by kenzierocks** [comment]
Ant does not compile with debug by default, see the `debug` parameter [here](https://ant.apache.org/manual/Tasks/javac.html).
