### ISSUE TITLE
[FG2] Usage of {SRG_DIR} causes MISSING REPLACEMENT DATA

### ISSUE THREAD

**Issue by me4502** [MinecraftForge/ForgeGradle#258]
Using SRG_DIR, like the following,

task copySrgs(type: Copy, dependsOn: 'genSrgs') {
    from minecraftPlugin.delayedFile('{SRG_DIR}')

```
include '**/*.srg'
into 'build/srgs'
```

}

Causes ForgeGradle to throw a RuntimeException with the text MISSING REPLACEMENT DATA FOR SRG_DIR

**Comment by Minecrell** [comment]
ForgeGradle 2 doesn't provide SRG_DIR anymore; however you can use something like this to add it manually, or just use the constant directly (for now): https://github.com/SpongePowered/SpongeCommon/blob/fg2/build.gradle#L19

**Comment by AbrarSyed** [comment]
I plan instead to add some sort of api to the minecraft{} block that will allow for buildscripts to get access to nearly everything FG has access to. The days of randomly putting tokens places are over.

**Comment by kashike** [comment]
Is there any time you think this will be done?

**Comment by AbrarSyed** [comment]
Eventually... I'll try to get it done Monday
