### ISSUE TITLE
Current installers seem to be broken

### ISSUE THREAD

**Issue by diesieben07** [MinecraftForge/ForgeGradle#259]
The installers that have been created since FG2 use the installer code from Mai 2014.

**Comment by GirafiStudios** [comment]
May * (Sorry :3)
I did notice that too yeah.

**Comment by diesieben07** [comment]
/me is german :P But yeah, may.

**Comment by LexManos** [comment]
God fucking dammet @AbrarSyed

**Comment by diesieben07** [comment]
Well, they are not broken (that was a misjudgement on my part, it was a different issue), but it is still not right that the code from over a year ago is shipped (still using the `cpw.mods` package).

**Comment by AbrarSyed** [comment]
df10f8fd66137efc63329b7898538480d8f0e183
lex should quickly rebuild the installers.. and everything should be good.

**Comment by LexManos** [comment]
Its not broken so it doesnt need to be rebuilt. But it's fixed now for future versions.
