### ISSUE TITLE
FG2.0.1 + IDEA not loading dependencies from ./libs

### ISSUE THREAD

**Issue by MattDahEpic** [MinecraftForge/ForgeGradle#269]
I just grabbed a new instance of forge 1.8 (1.8-11.14.3.1512) and the gradle wrapper will no longer load, decompile, or use as dependencies any jars I put in ./libs. Offending repository is https://github.com/MattDahEpic/MobDropOres1.9 should it be needed.

**Comment by AbrarSyed** [comment]
you are using the 2.0 snapshot?

**Comment by MattDahEpic** [comment]
// for people who want stable
    plugins {
        id "net.minecraftforge.gradle.forge" version "2.0.1"
    }
no

**Comment by AbrarSyed** [comment]
try using the snapshot, I think this issue is already fixed there.

**Comment by MattDahEpic** [comment]
It's not fixed in the snapshot.

**Comment by GirafiStudios** [comment]
Have you cleared your caches before installing the snapshot?

**Comment by MattDahEpic** [comment]
@GirafiStudios yes
