### ISSUE TITLE
Problem with gradle eclipse

### ISSUE THREAD

**Issue by odensc** [MinecraftForge/ForgeGradle#27]
When I run:

``` java
gradle setupDevWorkspace
gradle eclipse
```

And then I set the workspace in eclipse to forgeroot/eclipse, it says this:

``` java
The project description file (.project) for 'Minecraft' is missing.
This file contains important information about the project.
The project will not function properly until this file is restored.
```

EDIT: This seems to be caused by:
http://www.minecraftforge.net/forum/index.php/topic,14636.0.html

**Comment by acesblue** [comment]
https://www.youtube.com/watch?v=tfJEEbRJyo8 i need help with my gradle i'm not sure whats wrong

**Comment by LexManos** [comment]
Why did you name your folder the ONE thing you can't name folder that contain jars? Remove the damn !
Also don't hijack others 2 year old threads.
Also don't post here unless you've tried to fix your issue on the forum first as this is for bugs in FG itself not user errors.
0/10 Your post is a mess....
