### ISSUE TITLE
Get ATs from mod dependencies

### ISSUE THREAD

**Issue by me4502** [MinecraftForge/ForgeGradle#273]
Hi,

Just throwing this suggestion out there. Say you are making an addon for a mod, but want to have access to all the AT-modified fields. You'd need to basically put a copy of that AT in your mod. I'm suggesting a way to specify mods to inherit AT from.

**Comment by diesieben07** [comment]
This is not technically possible, since at the time where ATs are applied (before classes are loaded, ATs are ASM!) there is no inheritance information.
Instead of using ATs just use reflection.

**Comment by me4502** [comment]
That's not the type of inheritance I am talking about. I am talking about mod-add ons inheriting the AT from the mods they enhance.

**Comment by diesieben07** [comment]
Damn, actually reading would help... Sorry.
ATs are a global thing. They are not applied on the mod, they actually modify the targeted class. So, if one mod has an AT, that field/method is modified for everyone.

**Comment by AbrarSyed** [comment]
You have to extract the AT of the dependency mods, and put them in src/api/java. Then rerun the setup.

It is planned to have this pulled from dependencies automatically in FG2, have to double check if I added that or not yet.

**Comment by me4502** [comment]
Yeah, it's the automatic pulling of ATs that I was suggesting

**Comment by AbrarSyed** [comment]
Currently available in in the 2.0 snapshot.
``` minecraft { useDepAts = true } ```
This will only get ATs defined in the manifest of the dependency and can be found in the META-INF folder of the dependency jar, as is done by FML.

**Comment by me4502** [comment]
Thanks
