### ISSUE TITLE
Add a Liteloader plugin

### ISSUE THREAD

**Issue by killjoy1221** [MinecraftForge/ForgeGradle#275]
It should be put in the build dir so projects can have different settings for it.

Using the forge plugin in one project and tweaker in another messes this up. The last setup project will overwrite every other project's GradleStart.

**Comment by AbrarSyed** [comment]
uh, the forge gradleStart and the other GradleStart should be isolated in different places and not be stepping on each other. If they do, then its a bug.

**Comment by killjoy1221** [comment]
Ok, they don't, but different projects using the tweaker plugin with different settings will still override eachother. I'm currently doing this to change some of them.

```groovy
def mc = plugins.getPlugin 'net.minecraftforge.gradle.tweaker-client'
mc.replacer.putReplacement '{RUN_CLIENT_MAIN}', 'com.mumfrey.liteloader.debug.Start'
mc.replacer.putReplacement '{RUN_CLIENT_TWEAKER}', 'com.mumfrey.liteloader.launch.LiteLoaderTweaker'
```

**Comment by AbrarSyed** [comment]
private api.. I shall not be blamed. Make a seperate issue for adding back the liteloader plugin...

**Comment by AbrarSyed** [comment]
finally did this.. thanks @Mumfrey
