### ISSUE TITLE
makeStart failed

### ISSUE THREAD

**Issue by SchnitzelVan** [MinecraftForge/ForgeGradle#278]
I'm trying to run gradlew setupDecompWorkspace in command prompt but once it gets to makeStart it fails saying that it can't find the javac compiler and that JAVA_HOME might not point to the JDK. I checked my environmental variables and couldn't find a JAVA_HOME variable so I added one that points to the JDK, but whenever I try it still says the same thing. It says the JAVA_HOME is currently pointing to C:\Program Files (86x)\Java\jre1.8.0_45 but there wasn't even a JAVA_HOME variable until I added one. when I type "where javac" it tells me C:\Program Files\Java\jdk1.7.0_79\bin\javac.exe and I put that into the JAVA_HOME variable I created but it's still saying it's pointing to the first. Please help.

**Comment by AbrarSyed** [comment]
you need to add the following  to your PATH variable.
`%JAVA_HOME%/bin`
