### ISSUE TITLE
Eclipse Multiple Projects per Workspace.

### ISSUE THREAD

**Issue by BinaryAura** [MinecraftForge/ForgeGradle#279]
Have it possible to create multiple projects per workspace, Instead of a seperate workspace per project.

**Comment by matthewprenger** [comment]
This is already possible with eclipse... just import more projects to the workspace.

**Comment by LexManos** [comment]
The workspace that is included is a 'simple' example only you do not need to create a new workspace for each project.
You just need to learn how to import projects in your IDE which sadly we can't teach you as there are already plenty of tutorials.
