### ISSUE TITLE
Egit functionality

### ISSUE THREAD

**Issue by BinaryAura** [MinecraftForge/ForgeGradle#280]
Following ForgeGradle Setup instructions, Egit doesn't recognize my project as a repo. My .git, .gitignore, and .gitattributes are all in the main directory.

**Comment by LexManos** [comment]
FG does not mess with any .git functionality except to {IIRC} force ./build into the .gitignore file. {People were stupid}
You're going to have to be more specific.

**Comment by AbrarSyed** [comment]
yeah.. Egit is an eclipse thing.. hardly our problem..
