### ISSUE TITLE
Grammatical Errors

### ISSUE THREAD

**Issue by quaggaman555555** [MinecraftForge/ForgeGradle#284]
"status": "BROKEN",
        "docUrl": "https://forgegradle.readthedocs.org",
        "version": "2.0.0",
        "changes": [
        	"Massive update **fro** ForgeGradle 1.2"
        ],

[Here](https://github.com/MinecraftForge/ForgeGradle/blob/master/versionCheck/ForgeGradleVersion.json) is where this is from.

**Comment by liach** [comment]
Btw many typos [here] (https://github.com/MinecraftForge/ForgeGradle/blob/master/build.gradle#L192-L207). (what's minicraft and mincraft?)
