### ISSUE TITLE
Badly need help changing file path 

### ISSUE THREAD

**Issue by BROLEKAITHEERADICATOR** [MinecraftForge/ForgeGradle#294]
Hello, so I took over a mod from my friend and installed all his files onto my computer. Everything's good no errors in the code itself or anything of the sort; however when I try to run it I get this: Caused by: java.io.FileNotFoundException: C:\Users\lee\.gradle\caches\minecraft\assets\indexes\1.7.10.json (The system cannot find the path specified) You see the problem is that my user name is austin, not lee. Ive spent a while trying to locate the where I can change the path but I simply can't searched through all the files named 1.7.10, and all the files with the word 'lee' in it. I'm thinking the computer cant even search for it because the file path is invalid. 

Here's a picture of my eclipse file http://imgur.com/OuEKlh5 maybe you can direct me on where to go based off here. Thanks!

**Comment by AbrarSyed** [comment]
Did you run the 'serupDecompWorkspace' ?

**Comment by BROLEKAITHEERADICATOR** [comment]
Sorry not entirely sure what that is still pretty new to this, are you talking about the two setup files in the picture?

**Comment by BROLEKAITHEERADICATOR** [comment]
So I found out what it was, and it worked! Thanks a bunch man c';
