### ISSUE TITLE
SrgNames as the last entry on a line don't get renamed in RenameSources

### ISSUE THREAD

**Issue by cpw** [MinecraftForge/ForgeGradle#297]
https://github.com/MinecraftForge/ForgeGradle/commit/2f0ca9921b961133689d29b807333241010a802d seems to have added a weird trailing bit. We need to investigate why, and make sure trailing srgnames work properly.

**Comment by AbrarSyed** [comment]
63acb4dcf9b8c8d9153a3931b1b96017f43c5263
