### ISSUE TITLE
Decompile causes GC overhead limit exceded

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/ForgeGradle#298]
Running a `setupForge` on FG 2.1:
It also keeps all four cores of my processor maxed out until I kill the process. CTRL-C'ing out of gradle isn't enough.
```
[matthew@matt-desktop MinecraftForge]$ gradle setupForge
...
:decompileJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':decompileJar'.
> GC overhead limit exceeded

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 52.588 secs
```

**Comment by LexManos** [comment]
You know the stacktrace would be nice, or more information on your machine like how much ram you're giving to java {cuz thats what GC overhead limit is, memory} Something useful.
There shouldn't be any reason that your process is stalling like that and this log is useless, so try reporting again this time with useful information.

**Comment by matthewprenger** [comment]
@LexManos Apologies, was mainly a reminder for me to talk to abrar tomorrow on irc.  

Core i5-3570K / 16GB ram
OS: 4.2.5-1-ARCH
Java: 1.8.0_66 Oracle

I tried giving gradle 6GB of ram and the error still occured:
```
[matthew@matt-desktop MinecraftForge]$ GRADLE_OPTS=-Xmx6G gradle setupForge -S
...
:decompileJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':decompileJar'.
> GC overhead limit exceeded

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':decompileJar'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded


BUILD FAILED

Total time: 46.418 secs
```

**Comment by cpw** [comment]
@matthewprenger we actually would appreciate diagnostic info on this. It's been sporadically observed. You are using latest fg2.1, right? Do you have anything specific you're doing? 6gb heap was ample in all the tests so far. What JVM version?

**Comment by hea3ven** [comment]
Are these seriously gonna be the specs requirement for developing mc mods? I'm getting this error on a pc with 4GB of physical ram until I gave gradle 3GB, of course the whole system locked up while the decompileMc task was running:
```
$ gradle -Dorg.gradle.jvmargs=3072m setupDecompWorkspace
```
versions:
```
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
$ gradle --version

------------------------------------------------------------
Gradle 2.8
------------------------------------------------------------

Build time:   2015-10-20 03:46:36 UTC
Build number: none
Revision:     b463d7980c40d44c4657dc80025275b84a29e31f

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Windows 8.1 6.3 amd64
```

**Comment by cpw** [comment]
No. Try and --refresh-dependencies. I've pushed a change to fernflower that might help the memory footprint a bit.

**Comment by hea3ven** [comment]
Alright, I think it got better, but still something going wrong.

First of all, after the first successful decompilation mentioned in the previous post, the recompileMc task was failing: https://gist.githubusercontent.com/hea3ven/8a83f74191c4bc069835/raw/f57dfd96311eba1ceeb4b98125eeca16524dadaa/gradle_recompile_error.log

Once I cleaned up and run with --refresh-dependencies, and default memory config, it was getting stuck using 100% cpu for at least 5 minutes before I killed it: http://www.mediafire.com/download/bc76cmjisacn1l1/gradle_refresh_dependencies_stuck.zip (13MB file, couldnt upload it as a gist). Without --refresh-dependencies it was giving me the same error as before: https://gist.githubusercontent.com/hea3ven/8a83f74191c4bc069835/raw/f57dfd96311eba1ceeb4b98125eeca16524dadaa/gradle_decompile_error.log

I tried running it with -Xmx=2048m which seemed to work, but failed in the fixMcSources task: https://gist.githubusercontent.com/hea3ven/8a83f74191c4bc069835/raw/f57dfd96311eba1ceeb4b98125eeca16524dadaa/gradle_decompile_no_error_2048m.log

**Comment by Minecrell** [comment]
I can confirm a similar problem as @hea3ven, however here is an exception from Fernflower: https://gist.github.com/Minecrell/dfb2a034028962f370f0, probably caused by https://github.com/MinecraftForge/FernFlower/commit/f3c197fc7633ffc69ce33e711f542fc1b25d9b3d

**Comment by Minecrell** [comment]
The latest version works fine for me if I allocate more RAM to the Gradle process. Without adding a specific amount of maximum RAM it seems to just freeze immediately after starting to decompile (the decompile log is not getting filled, except with a few lines scanning JARs). Wasn't able to get any kind of dump because of that reason.

However, when allocating more memory, like 3 GB RAM max. it then seems to use up to 2.5 GB RAM but completes just fine in a surprising time of 2 minutes (I'm decompiling the server source only right now). Previously this took up to 5 minutes with FG2.0.

**Operating System:** Arch Linux
**Java version:**
```
openjdk version "1.8.0_66"
OpenJDK Runtime Environment (build 1.8.0_66-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)
```
**Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz / 4 GB RAM**

**Comment by cpw** [comment]
OK. Run a refresh-dependencies. You should pick up Fernflower: http://files.minecraftforge.net/maven/net/minecraftforge/fernflower/2.0-SNAPSHOT/fernflower-2.0-20151123.195705-16.jar

That will fix your memory issue. The minimum required memory is now 1200M. (Note, at that low value, it will take significantly longer to decompile due to GC pressure). 2G heap size should work with decent speed. 

Set your heap size with "GRADLE_OPTS="-Xmx2G" ./gradlew setupForge or similar.

**Comment by Minecrell** [comment]
Decompiling Forge didn't work that well on my machine unfortunately. While it basically decompiled fine with 3 GB allocated RAM it was using the max. amount of memory the whole time and was also extremely slow with decompiling (more then 15 minutes). I guess it was working on cleaning the memory a lot of the time instead of actually decompiling.

**Comment by cpw** [comment]
@Minecrell unless you are using the **LATEST FERNFLOWER** I will completely disregard. PLEASE ENSURE YOU'RE UP TO DATE with FERNFLOWER.

**Comment by Minecrell** [comment]
@cpw I had everything but https://github.com/MinecraftForge/FernFlower/commit/add9bf560f6db5cea287c95b2ee13575ba15c8f3, I'll try again later.

**Comment by cpw** [comment]
Heh. without that, you'll get a broken decompile. So yeah.

**Comment by Illyohs** [comment]
I'm still having this issue even with the latest FernFlower.

_OS_: Arch Linux
_MEMORY_: 6GB


_Gradle Info_:
````
~/McWorkSpace/LibIlly (updoot/1.8.8 ✘)✹✭ ᐅ bash gradlew -v

------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_66 (Oracle Corporation 25.66-b17)
OS:           Linux 4.2.5-1-ARCH amd64
```

_Gradle Command: `GRADLE_OPTS=-Xmx4G bash gradlew setupdecompworkspace`
_Gradle Log_: http://sprunge.us/RAXD

**Comment by LexManos** [comment]
"Memory: 6GB"
"-Xmx4G"
LIES!

**Comment by Illyohs** [comment]
Fixed by changing the adding `org.gradle.jvmargs=-Xmx3G` to my gradle.properties

**Comment by cpw** [comment]
@illyochs You had your env var in the wrong spot which is why GRADLE_OPTS didn't work. BTW, 2gb is sufficient in my tests..

**Comment by Termin8or** [comment]
I'm still getting this error, from what I can see, it seems to be a Linux thing, as on windows I never had to allocate more ram to gradle. Also my cpu is at 100%. When trying to decompile. I have a 2.3Ghz Core i3 2350M, 8Gb of ram with 3 allocated, and Zorin os 10.

**Comment by kane-thornwyrd** [comment]
`gradlew -Dorg.gradle.jvmargs=-Xmx10240m setupDecompWorkspace && gradlew eclipse` in my `setup_workspace.bat` file did my day (I have 32Go physical ram)

**Comment by pravihs** [comment]
Thanlks @kane-thornwyrd . For me also -Dorg.gradle.jvmargs=-Xmx10240m worked!
