### ISSUE TITLE
Mapping validity is checked too early

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/ForgeGradle#304]
Mappings are checked when they are set rather than in afterEvaluate. This causes the MC version to have to be declared before the mappings version.

https://github.com/MinecraftForge/ForgeGradle/blob/master/src/main/java/net/minecraftforge/gradle/common/BaseExtension.java#L239
https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.1/src/main/java/net/minecraftforge/gradle/common/BaseExtension.java#L195

**Comment by way2muchnoise** [comment]
Guess this failure I'm having is related to this issue.
http://pastebin.com/AVNDs6rM

**Comment by AbrarSyed** [comment]
hmm, I dont think thats an issue matthew... the chckMappigns() code has a check to ensure the MC version is set first...

https://github.com/MinecraftForge/ForgeGradle/blob/master/src/main/java/net/minecraftforge/gradle/common/BaseExtension.java#L249

**Comment by kashike** [comment]
https://gist.github.com/OrionDevelopment/d0bb622b45221511d267
