### ISSUE TITLE
[FG 2.1-snapshot] PatchException

### ISSUE THREAD

**Issue by rubensworks** [MinecraftForge/ForgeGradle#307]
(Not sure if this issue should be moved to Forge instead...)

I just tried updating to Forge 11.15.0.1609-1.8.8 (also tried with 1.8.8-11.15.0.1603-1.8.8), and I'm getting a `com.cloudbees.diff.PatchException: Cannot find hunk target` for the `fixMcSources` task.
I also tried cleaning multiple times, so I don't think this is a mistake on my end. Please correct me if I'm wrong.

I'm using ForgeGradle 2.1-SNAPSHOT with Java 8 (build 66) on Mac OS 10.9.5.

Full output: http://hastebin.com/hocofuqico.coffee

**Comment by heni123321** [comment]
try cleaning .gradle/minecraft in your workspace, for sum reason clean doesn't delete it

**Comment by rubensworks** [comment]
I'd prefer not to delete the cached folder, as I still want to be able to have access to older Forge versions, and deleting that folder will probably just re-introduce the problem later on.

**Comment by AbrarSyed** [comment]
yeah cleanCache and try again.. im not sure whats wrong, but its probably a corrupted/wrong jar somewhere in the pipeline.

**Comment by rubensworks** [comment]
You are right, removing all 1.8.8 related files in the .gradle folder fixed it.

A small suggestion: Maybe some cleanCache tasks could be created that only removes files that are related to that specific Forge version. Because removing the complete minecraft/ directory might not always desirable.
