### ISSUE TITLE
PatchException: Cannot find hunk target on Vanilla 1.8.8

### ISSUE THREAD

**Issue by Minecrell** [MinecraftForge/ForgeGradle#310]
Just tried updating my 1.8.8 workspace and it seems after it downloaded a new `mcp-1.8.8-srg.jar` it is now unable to decompile the Vanilla server for the tweaker-server plugin properly. I've already tried cleaning the whole .gradle folder, the issue would still occur no matter what I do. This is the error I'm getting:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fixMcSources'.
> com.cloudbees.diff.PatchException: Cannot find hunk target
```

Full output: https://gist.github.com/Minecrell/b9360f53459a890c8117#file-gistfile1-txt-L4504-L7182

**Comment by GirafiStudios** [comment]
Yeah, that happened to me too. Just had to re-run setupDecompWorkspace a couple of times and then it worked.

**Comment by AbrarSyed** [comment]
Gradle setupDecompWorkspace --refresh-dependencies

**Comment by Minecrell** [comment]
@AbrarSyed That's what I run. And deleting the whole `.gradle` folder would trigger that anyway.

**Comment by AbrarSyed** [comment]
Clean cache isn't necessary and is overkill.

**Comment by Minecrell** [comment]
@AbrarSyed Well it is broken for some reason anyway, just tried this on a machine where I've never used FG (or Gradle) before and it's not working there either.

**Comment by AbrarSyed** [comment]
Clean cache isn't necessary and is overkill.

Your probably right, lex probably didn't update the client and server jars, only updated the merged jar. I'll ask him about it.

**Comment by AbrarSyed** [comment]
@lexmanos

**Comment by LexManos** [comment]
Right.. vanilla.... Why do people mod that again anyways?
