### ISSUE TITLE
ForgeGradle integration with JetGradle fails

### ISSUE THREAD

**Issue by JBYoshi** [MinecraftForge/ForgeGradle#311]
When I use IntelliJ's built-in Gradle integration (JetGradle) to refresh a ForgeGradle project (specifically SpongeForge), the `start` directory is not added to the classpath. Running `gradle idea` works properly. Could someone fix this?

**Comment by luacs1998** [comment]
I'm only encountering this issue if I use the "refresh" button in the gradle tool window.

**Comment by Minecrell** [comment]
@JBYoshi Pretty sure you're doing something wrong when importing, it has always worked just fine for me (for the Sponge projects). Are you using the latest IntelliJ IDEA version?

**Comment by JBYoshi** [comment]
@Minecrell Yes.

@luacs1998 That's one of the ways I can get the problem to appear.

**Comment by Mumfrey** [comment]
@JBYoshi what version of the gradle wrapper is included in your project? I had weird things going on with Buildship when the wrapper version in my project was out of date, this seems to be because the tooling api is "wrapper aware" and changes its behaviour based on the settings in the `gradle-wrapper.properties`

**Comment by JBYoshi** [comment]
I believe the wrapper is on 2.8.

**Comment by JBYoshi** [comment]
I took a look, and IntelliJ doesn't refresh the project on startup (I guess I had done a refresh before shutting it down previously). However, it would be nice to have support for the Refresh button.

**Comment by AbrarSyed** [comment]
Well... I have no control over what intellj does... So I can't fix this from the FG side of things.
