### ISSUE TITLE
gradle idea sets up dependency order incorrectly

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/ForgeGradle#313]
When I create a project with `gradle idea` after it has been cleaned or I update Forge, gradle puts log4j higher in the dependency order than forge.
This means that all my logging is broken. Nothing except latest.log goes to file, all mod logging below a certain level is lost, and a few other problems.

The workaround is to edit the project structure in Modules -> Dependencies and drag the forgeSrc jar to near the top of the list every time.

**Comment by ZenDarva** [comment]
Just discovered this affecting my work as well, output from mods reporting errors in the Development environment never made it to the output console.  Lost an hour of debugging.

**Comment by matthewprenger** [comment]
See: https://github.com/MinecraftForge/ForgeGradle/issues/331#issuecomment-172670511

**Comment by AbrarSyed** [comment]
dupliate of #331, but #331 has better discussion.
