### ISSUE TITLE
Method references in dependencies do not get mapped

### ISSUE THREAD

**Issue by fnuecke** [MinecraftForge/ForgeGradle#314]
Given mod [`dependee`](https://github.com/fnuecke/MC-Mapping-Issue-Dependee) and mod [`depender`](https://github.com/fnuecke/MC-Mapping-Issue-Depender), where `depender` has [a dependency on mod `dependee`](https://github.com/fnuecke/MC-Mapping-Issue-Depender/blob/master/build.gradle#L68), if `dependee` [uses a method reference](https://github.com/fnuecke/MC-Mapping-Issue-Dependee/blob/master/src/main/java/li/cil/test/ModDependee.java#L28) to something that needs mapping, it isn't mapped, leading to a `NoSuchMethodError` when executing `depender` in the dev-env and the respective code in `dependee` gets executed.

**Comment by AbrarSyed** [comment]
Is that :: syntax valid kava? Never seen that before... I'll look into it.

**Comment by matthewprenger** [comment]
The `::` are method references added in Java 8.

**Comment by AbrarSyed** [comment]
Does that compile to a string literal? Otherwise I see no reason why the bytecode wouldn't get reobfuscated..

**Comment by fnuecke** [comment]
It's a Java 8 thing, yes, [and it's very much valid syntax](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html) ;-) I don't know what bytecode that exactly compiles to, though, and jd-gui fails on the class. If it helps, the [binary of the `dependee` mod is here](http://maven.cil.li/li/cil/test/test-mapping-dependee/1.0/test-mapping-dependee-1.0.jar).

**Comment by cpw** [comment]
I believe it compiles to a lambda artifact. This probably is a hidden class, and might not be visited by normal class visitors. Likely a special source fix is needed to find it..

**Comment by LexManos** [comment]
Here is a really simple example of a function handle: https://dl.dropboxusercontent.com/u/28221422/FunctionHandleTest.zip
The bytecode is... weird.. to say the least.

**Comment by AbrarSyed** [comment]
@md_5 can Special Source be made to handle this?

**Comment by md-5** [comment]
Yeah, need to look into what facility ASM provides for visiting this. Somewhat surprising that their default remapper doesn't handle it.

**Comment by md-5** [comment]
Cannot reproduce with Lex's FunctionHandleTest and the srg mapping


`java/util/Arrays sort ([I)V newSort`

`java -jar SpecialSource.jar -i FunctionHandleTest.zip -o Mapped.jar -m mappings.srg`

**Comment by AbrarSyed** [comment]
what SS version? FG is currently shading in 1.7.4-SNAPSHOT, so the snapshot as of 5 days ago should be the one FG is using right now..

**Comment by md-5** [comment]
Same, 1.7.4-SNAPSHOT straight from git.

**Comment by ljfa-ag** [comment]
Simply using a lambda that implements an obfuscated interface seems to trigger a similar problem, for instace with ItemMeshDefinition:
https://github.com/TeamTotemic/Totemic/blob/53d26cd2d4f0c39c2d8e8b30d02815ebb4f27a46/src/main/java/totemic_commons/pokefenn/ModBlocks.java#L106-L109
This crashes in the obfuscated environment with an AbstractMethodError.

**Comment by williewillus** [comment]
^ Same issue here with botania port 1.8 https://gist.github.com/MrGraphic/bb1cd0dd128026356b5b

**Comment by LexManos** [comment]
Lambdas are probably implemented the same way, function handles for speed.
For now while md5 takes a look use normal anon classes.

**Comment by matthewprenger** [comment]
Looking into it, SpecialSource isn't used at all for dependency deobf. It's done strictly with ASM [HERE](https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.1/src/main/java/net/minecraftforge/gradle/user/TaskSingleDeobfBin.java#L145). My ASM skills aren't good enough to figure out what needs to be changed however.

**Comment by md-5** [comment]
@matthewprenger if that is indeed the case I would suggest someone rewrites that code to use the SpecialSource API because it's missing inheritance and rewriting anything other than basic field references. Alternatively ASM has a SimpleRemapper that can probably consume those Maps (or slightly modified versions). No inheritance with that, but it will get the lambdas.

**Comment by AbrarSyed** [comment]
yeah I somehow misread the original Issue here and thought it was reobf or something.. Its done by my own code. 

I do a very simple (and probably naive) string-replacement of symbol names in all fields and methods and invocations. I dont know what bytecode I should be looking for when it comes to lambdas and stuff though... Need to research that.

**Comment by md-5** [comment]
@AbrarSyed 
http://websvn.ow2.org/filedetails.php?repname=asm&path=%2Ftrunk%2Fasm%2Fsrc%2Forg%2Fobjectweb%2Fasm%2Fcommons%2FRemapper.java

Just override the three map methods, shouldn't take more than 10 minutes to fix.

**Comment by md-5** [comment]
@AbrarSyed 
http://websvn.ow2.org/filedetails.php?repname=asm&path=%2Ftrunk%2Fasm%2Fsrc%2Forg%2Fobjectweb%2Fasm%2Fcommons%2FRemapper.java

Just override the three map methods, shouldn't take more than 10 minutes to fix.

**Comment by matthewprenger** [comment]
#325
