### ISSUE TITLE
Execution failed for task ':reobfJar'

### ISSUE THREAD

**Issue by iLexiconn** [MinecraftForge/ForgeGradle#319]
Crash log: https://media.ilexiconn.net/m2cKjFx.txt

**Comment by AbrarSyed** [comment]
need build.gradle

**Comment by iLexiconn** [comment]
https://github.com/iLexiconn/LLibrary/blob/1.8.9/build.gradle

**Comment by AbrarSyed** [comment]
this doesnt make sense, why do you have 'dummyThing' in your jar? you dont appear to be shading or packaging anything into your release jar, so the 'dummyThing' entries shouldnt be there.

For future reference, you dont need the dev jars in FG 2+ anymore, FG can deobfuscate dependencies now: https://github.com/MinecraftForge/MinecraftForge/blob/master/mdk/build.gradle#L53-L56

**Comment by iLexiconn** [comment]
Okay, I'll use the new method. Thanks for your help.

**Comment by AbrarSyed** [comment]
wait so.. the crash is fixed?

**Comment by iLexiconn** [comment]
This code caused the crash:
```gradle
jar {
    from configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
}
```
(I got it from https://github.com/MinecraftForge/ForgeGradle/wiki/Dependencies)
