### ISSUE TITLE
Forge/MC sources not auto-attached with Idea 16 (EAP)

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/ForgeGradle#321]
Haven't had a chance to dig into exactly why, but Idea 16 (currently on the Early Access Program release channel) doesn't get auto-attached sources for Forge/MC. The source jar does exist in the gradle cache however and can be manually attached.

**Comment by AbrarSyed** [comment]
appears to be an issue with the idea gradle integration plugin.. not my problem.

**Comment by matthewprenger** [comment]
IntelliJ 2016.1 just released so now this issue is affecting everyone. FYI

**Comment by AbrarSyed** [comment]
Dammit idea....

**Comment by Minecrell** [comment]
It seems to be related to `flatDir` repos, see https://youtrack.jetbrains.com/issue/IDEA-150685#comment=27-1347737

**Comment by diesieben07** [comment]
The run generated run configs also do not work by default, you have to choose the correct classpath manually: ![a](http://i.imgur.com/49qpav0.png)

**Comment by matthewprenger** [comment]
FYI: This seems to be fixed with Idea 2016.1.1

**Comment by Minecrell** [comment]
Ye, that bug was fixed :)
