### ISSUE TITLE
gradlew setupDecompWorkspace failing with decompileMc

### ISSUE THREAD

**Issue by abused** [MinecraftForge/ForgeGradle#324]
Hello everyone, so i am trying to create a mod for minecraft 1.8.9 but when i open a command prompt and type graldew setupDecompWorkspace it fails and gives me this http://pastebin.com/zWSt41DT and then when i run with --stacktrace i get http://pastebin.com/vZ80WGh7

can anyone help me fix this issue

**Comment by matthewprenger** [comment]
@abused You need to either create a file here: `USER_HOME/.gradle/gradle.properties` and put `org.gradle.jvmargs=-Xmx2G` in it, or set the `GRADLE_OPTS` environment variable to `-Xmx2G`.

**Comment by yooksi** [comment]
@matthewprenger How exactly do we set the `GRADLE_OPTS` environment variable?

**Comment by Kman636** [comment]
Go to environment variables the same way you do when editing path variable and create new or edit
