### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by ThunderTNT33** [MinecraftForge/ForgeGradle#328]
When I try to recompile or start client test environment it gives a lot of errors.
Full log: http://pastebin.com/rqaQbFDF

**Comment by diesieben07** [comment]
Don't use MCreator. If you want to make a mod, learn Java.

**Comment by ThunderTNT33** [comment]
Even when I try to set it up for eclipse it gives the same error

**Comment by LexManos** [comment]
Dont use MCreator, follow the normal setup instructions for the MDK.

**Comment by ThunderTNT33** [comment]
I did that but then it gives me also the same error
