### ISSUE TITLE
retromapReplacedMain doesn't generate jar / sourceJar crashes

### ISSUE THREAD

**Issue by bdew** [MinecraftForge/ForgeGradle#329]
Might be because i use non-default source locations (there are some hardcoded paths [here](https://github.com/MinecraftForge/ForgeGradle/blob/master/src/main/java/net/minecraftforge/gradle/user/UserBasePlugin.java#L751)) or because i don't have java sources.

At any rate the jar doesn't get generated at all in retromapReplacedMain which causes sourceJar to crash.

Log and build script here: https://gist.github.com/bdew/68ab8b433ae8478d55cf

Disabling this thing with makeObfSourceJar = false stops it from crashing, but it should handle this state more gracefully.

**Comment by carrotengineer** [comment]
I have the same issue in a Kotlin based mod, and it was caused by not having any Java files in my sources.

Adding a dummy Java class in to the sources fixed it. (file here: https://gist.github.com/carrotengineer/8443cbf8037c85cdaabe )
