### ISSUE TITLE
Error when trying to setup

### ISSUE THREAD

**Issue by ThunderTNT33** [MinecraftForge/ForgeGradle#330]
When I try to setup it for eclipse it gives me this errors: http://pastebin.com/9n3F5gBB

**Comment by AbrarSyed** [comment]
need your build.gradle

**Comment by ThunderTNT33** [comment]
build.gradle : http://pastebin.com/BR7ciLnS

**Comment by AbrarSyed** [comment]
run `gradle -v` and get me that output.

**Comment by ThunderTNT33** [comment]
Gradle -v output : http://pastebin.com/KtLJX5CX

**Comment by AbrarSyed** [comment]
I honestly have no idea... its something with reading corrupted POM files... Try updating gradle to the latest, and also try updating java.. I really dont know...

**Comment by ThunderTNT33** [comment]
Ok thx for your help.

**Comment by Mumfrey** [comment]
@ThunderTNT33 do you have any local firewall software, or parental lock software or anything like that which might be blocking the connections?

**Comment by ThunderTNT33** [comment]
No I have turned off Windows firewall and my anti virus

**Comment by ThunderTNT33** [comment]
I dont know why but I fixed it I made a new user and tried it there and it worked so I think a program is blocking .pom files
