### ISSUE TITLE
IDEA projects have incorrect classpath order, breaking logging

### ISSUE THREAD

**Issue by Emberwalker** [MinecraftForge/ForgeGradle#331]
In a fresh dev env created with `gradle setupDecompWorkspace idea`, the forgeSrc dependency is not first in the dependency list in IDEA, so logging isn't configured (mainly manifesting by not showing the logger name) - there's probably something else with a Log4j2 config somewhere in the classpath before it.

Tested with IDEA 15.1 (Ultimate) on Ubuntu 15.10, Forge 1.8.9 (FG `2.1-SNAPSHOT`)

**Comment by matthewprenger** [comment]
Try importing the `build.gradle` instead of running the `idea` task. I just tested using that method on Idea 16 and the dependency order looks ok to me.
![](http://i.imgur.com/rHuyQzT.png)

**Comment by Parker8283** [comment]
Still, no reason this can't be fixed if it is on FG's side.

**Comment by AbrarSyed** [comment]
I cant fix this.
the MC jar is added last in the dependency list because it is the one that is created as opposed to grabbed. There is nothing I can do about that.. short of requiring people to setup before doing anything else (like it was in the old days). This would mean you cant run a build and have it auto-setup, and cant run a the setup and IDE tasks in the same call.
As for how the IDE orders the dependencies.. thats opaque to me, I assume it does it in the arbitrary order gradle provides, which I assume is the order I add the dependencies.. which as I mentioned above, I cannot change.

**Comment by LexManos** [comment]
So actually I DO have a fix for this, I'd just like abrar to look into it:
Add this to ForgePlugin.afterEvaulate:
```java
        if (project.getExtensions().findByName("idea") != null)
        {
            IdeaModel idea = (IdeaModel)project.getExtensions().findByName("idea");
            idea.getModule().getIml().whenMerged(new Closure<Object>(project)
            {
                private static final long serialVersionUID = 7231843530218328935L;
                @Override
                public Object call()
                {
                    Module mod = (Module)this.getDelegate();
                    List<Dependency> deps = new ArrayList<Dependency>();
                    for (Dependency dep : mod.getDependencies())
                    {
                        if (dep.toString().contains("forgeSrc") || dep.toString().contains("forgeBin"))
                            deps.add(0, dep);
                        else
                            deps.add(dep);
                    }
                    mod.getDependencies().clear();
                    mod.getDependencies().addAll(deps);
                    return null;
                }
            });
        }
```
UBER hacky but forces the forge dep to be at the top of the list.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
