### ISSUE TITLE
gradlew setupForge not applying patches from ServerHangWatchdog

### ISSUE THREAD

**Issue by VikeStep** [MinecraftForge/ForgeGradle#332]
Steps to reproduce:
1. Clone MinecraftForge (Doesn't need to be a fork)
2. run gradlew setupForge
If you open up the dev environment you will see that it has not applied the patches from here https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/server/dedicated/ServerHangWatchdog.java.patch
3. Run gradlew genPatches
4. Run git status and you will notice that the patches to the ServerHangWatchdog class were undone and that single file is different that the origin.

I am able to reproduce this in two separate directories, one from a fork, one from the main MinecraftForge repository. Running gradlew cleanCache did also not solve the issue.

Of note: There was a commit to this class 8 days ago https://github.com/MinecraftForge/MinecraftForge/commit/2ba595b207148784b9b8cadeb48883ba7bd4cac8

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/be6577b9ce4114bb27b8e60cf8b3e20a0519d4a8
Broken PRs -.-
