### ISSUE TITLE
:makestart issue on setupDecompWorkspace

### ISSUE THREAD

**Issue by Umbra27** [MinecraftForge/ForgeGradle#333]
I'm trying to setup a workspace on windows 7,  java 1.8.0
 
It doesn't run with Dev or Decomp (gradlew setupDecompWorkspace) and produces the same error both times http://pastebin.com/Sn4mGY5L 
I believe that the Java_home goes to the right place but I've no idea how to check.

**Comment by AbrarSyed** [comment]
http://www.robertsindall.co.uk/blog/setting-java-home-variable-in-windows/

**Comment by Umbra27** [comment]
I've setup the Java_home and it still produces the same error

**Comment by diesieben07** [comment]
It's pointing to your JRE. You need to install the JDK and point `JAVA_HOME` at it.
