### ISSUE TITLE
[FG_2.1] Not all javadocs from the MCP csv's get added

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/ForgeGradle#334]
I've noticed that a few javadocs end up missing in the final processed forgeSrc jar when they exist in the MCP snapshot data.

Example: The lines in the `methods.csv` pulled from the gradle cache:
```
func_71518_a,getCommandUsage,2,Gets the usage string for the command.
func_71514_a,getCommandAliases,2,Get a list of aliases for this command. <b>Never return null!</b>
```
The corresponding methods in the forgeSrc jar `ICommand.java`:
![](http://i.imgur.com/SMbyqPE.png)
You can see that `getCommandUsage` has its javadocs attached, while `getCommandAliases` does not.

**Comment by AbrarSyed** [comment]
hmm.. I think it might be because of those html tags.. any thing else have html tags?

**Comment by matthewprenger** [comment]
Ahh yeah. At a quck glance it looks like all the problem ones have html tags.

**Comment by matthewprenger** [comment]
OK identified the problem, but I don't know enough about regex to fix it. The METHOD (and I assume FIELD) regexs [HERE](https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.1/src/main/java/net/minecraftforge/gradle/tasks/RemapSources.java#L63-L64) don't work with generic method (and I assume field) declarations. So the `<` and `>` characters mess up the regex matching.

**Comment by tterrag1098** [comment]
Working on a fix

**Comment by tterrag1098** [comment]
There you go :smile:
