### ISSUE TITLE
AbstractMethodError related to lambdas and reobfuscation

### ISSUE THREAD

**Issue by RainWarrior** [MinecraftForge/ForgeGradle#336]
People get AbstractMethodError in production, which I assume are related to this #314, when calling [ModelLoader.setCustomMeshDefinition](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/client/model/ModelLoader.java#L1007) with a lambda.
https://gist.github.com/shadowfacts/e851d262816c5965864c

**Comment by matthewprenger** [comment]
Example code would help with debugging this.

**Comment by RainWarrior** [comment]
https://github.com/williewillus/Botania/blob/8e7f1cfac171753cf02671fb21616020b39a385d/src/main/java/vazkii/botania/client/core/handler/ModelHandler.java#L174-L177

**Comment by matthewprenger** [comment]
Opened SpecialSource issue here, md-5/SpecialSource#36

**Comment by williewillus** [comment]
can be closed as SS issue is closed

**Comment by mezz** [comment]
I'm encountering this error.

Here's an example crash from Railcraft, placed into the `mods` folder of a clean Forge project on the latest version:
https://gist.github.com/mezz/02363fadc93673a1c443789eb9707cd5
