### ISSUE TITLE
addExtraSrgLine does not remove original

### ISSUE THREAD

**Issue by modmuss50** [MinecraftForge/ForgeGradle#337]
When using addExtraSrgLine it does not remove the original package. The new renamed package does exist.

**Comment by LexManos** [comment]
Example, and intended result.

**Comment by AbrarSyed** [comment]
It usually just leaves empty folders behind...

**Comment by killjoy1221** [comment]
https://gist.github.com/killjoy1221/c9487befa9cafd65054f#file-build-gradle-L27-L28

Use a real shadow plugin.

**Comment by AbrarSyed** [comment]
seems like this is answered.....

**Comment by modmuss50** [comment]
It is broken but I did end up using that shadow plugin, sorry I didn't get back to you was very busy with real life.

**Comment by AbrarSyed** [comment]
Ok then I need more info.. to actually debug it if its still an issue...

**Comment by modmuss50** [comment]
Ok, sorry for being unclear at the start,
When adding kotlin in gradle and shading it everything works as intended. I then realised I needed repackage kotlin to allow other kotlin mods work with mine. 

So I added this to my build.gradle file:

    reobfJar { 
        addExtraSrgLine "PK: kotlin kotlinRepackFluxedRedstone" 
        addExtraSrgLine "PK: org/jetbrains org/jetbrainsRepackFluxedRedstone"
    }

The full file can be seen here: https://github.com/modmuss50/Fluxed-Redstone/blob/91d7dae67fc31191d2ca63bcaa60d82ee2a31952/build.gradle

This repackaged kotlin to the new location, and correctaly remapped my mod to use the `kotlinRepackFluxedRedstone` version of kotlin. But I notcied that jar was very big, so I opened it up in WinRar. I saw the new package with all the classes in, and I still saw the old folder. But the old folder still had the original classes in. (If you want me to get you an example I can get you one)

After talking on IRC I was shown that Shadow plugin, and that fixed all of my issues. You can see my current file here: https://github.com/modmuss50/Fluxed-Redstone/blob/master/build.gradle

Hope this helps. The issue might just be that kotlin is too much for it.

**Comment by killjoy1221** [comment]
I'm thinking it would be an issue with SpecialSource because that's what handles the reobfuscation.

**Comment by modmuss50** [comment]
It would most likely be, just wasn't sure what issue tracker to put it on. At least it will get seen by the relevant people here.

**Comment by AbrarSyed** [comment]
is this still an issue?

**Comment by modmuss50** [comment]
Im using the shadow plugin now, I think its jsut an issue when trying to shade a lot of stuff(koltin) so for most cases it is fine.

**Comment by killjoy1221** [comment]
Could this be related to md-5/SpecialSource#36?

**Comment by AbrarSyed** [comment]
For anyone looking at this later. Use the Gradle Shadow plugin.
