### ISSUE TITLE
HotSwap not supported

### ISSUE THREAD

**Issue by Kostronor** [MinecraftForge/ForgeGradle#338]
I am trying to get HotSwap to work with Intellij15 and forgegradle for 1.7.10 and it tells me that hot swap is not supported by runClient. Do I have to use a different command, or is there a way to fix this?

**Comment by AbrarSyed** [comment]
you gotta use actual intellij run configs instead of runClient. These can be generated by running  `gradle genIntellijRuns`

**Comment by Kostronor** [comment]
Thanks a lot for the info!
Do we have a list with all tasks and a little explanation of them, so questions like this are easy to answer by reading a readme or so? (Would reduce people like me asking ;) )

**Comment by AbrarSyed** [comment]
`Gradle tasks`
