### ISSUE TITLE
Options to switch mirror

### ISSUE THREAD

**Issue by LasmGratel** [MinecraftForge/ForgeGradle#343]
Is there an option to custom a minecraft mirror?
Because s3.amazonaws.com site is very slow in my country.
Or a option to select a path to .minecraft folder?

**Comment by Meow-J** [comment]
See https://git.io/v2UAp and https://git.io/v2Uxf

Since the urls are hardcoded, I don't think you can customize them atm.

**Comment by AbrarSyed** [comment]
Indeed you cant..
WOnder if its worth making that configurable...

Id say just configure yourself a proxy or something, or use your hosts file to redirect the s3 host to some HTTP server that does have what you need.

**Comment by matthewprenger** [comment]
Looks like Mojang is moving game/asset downloading to cloudfront(Amazon CDN) so that should help with your slow downloads whenever ForgeGradle is switched to use the new URLs.

**Comment by AbrarSyed** [comment]
they are? thats news to me...

**Comment by matthewprenger** [comment]
Yeah `https://launchermeta.mojang.com/mc/game/version_manifest.json` is the new entry-point json.

**Comment by AbrarSyed** [comment]
... well then... time to revamp all the old things...

**Comment by AbrarSyed** [comment]
5b59efa4e735f70749ad2be779b780063abc10a2
this will be merged into 2.1 sometime soon (2 weeks max  I hope)
