### ISSUE TITLE
Missing running configuration

### ISSUE THREAD

**Issue by BloodyError** [MinecraftForge/ForgeGradle#345]
Unfortunately I had to format my windows and now I re-install forge for modding and for some reason I have missing configuration.
First I'm doing `gradlew setupDecompWorkspace --refresh-dependencies` and then `gradlew genIntellijRuns` and yet there are no running configuration for intellij.
For Eclipse, however, it's does running (can't choose between Client or Server side), But I prefer to work with intellij.

Any ideas? please?

**Comment by AbrarSyed** [comment]
1) gradle setupDecompWorkspace
2) open idea and import the build.gradle
3) gradle genIntellijRuns
4) close and re-open idea
