### ISSUE TITLE
Minecraft Decompile Error/Failure Help

### ISSUE THREAD

**Issue by ReeCays** [MinecraftForge/ForgeGradle#348]
This is the output of the following console:

http://pastebin.com/V1sTynKD

**Comment by liach** [comment]
See #298

**Comment by ReeCays** [comment]
Just tell me what to do.

**Comment by matthewprenger** [comment]
@ReeCays 

Add this line to `USER_HOME/.gradle/gradle.propertes`: `org.gradle.jvmargs=-Xmx3G`

You may need to create that file.

**Comment by liach** [comment]
Create a `gradle.properties` file in the same directory as `build.gradle`. In that file, put `org.gradle.jvmargs=-Xmx2G` and it should be good.

**Comment by ReeCays** [comment]
I already done it by myself.
