### ISSUE TITLE
Minecraft Modding Questions

### ISSUE THREAD

**Issue by ReeCays** [MinecraftForge/ForgeGradle#349]

**Comment by AbrarSyed** [comment]
... srsly?

**Comment by ReeCays** [comment]
wait a sec...

**Comment by AbrarSyed** [comment]
This github issue tracker, is for bugs and enhancement requests for ForgeGradle. Not for general Minecraft modding. Each question/bug should also be isolated to its own issue.

**Comment by ReeCays** [comment]
it was a mistake, how can I redo this?

**Comment by AbrarSyed** [comment]
You cant delete issues on github. Only edit them.

**Comment by ReeCays** [comment]
Where can I ask questions then?

**Comment by AbrarSyed** [comment]
Minecraft Forums, MinecraftForge forums, IRC, plenty of places. Not here.
