### ISSUE TITLE
Modding/Coding Questions about Minecraft

### ISSUE THREAD

**Issue by ReeCays** [MinecraftForge/ForgeGradle#350]
Could anyone answer the following questions:

Difficulty in my opinion:
1 = easy, 2 = normal, 3 = hard;

I putted this question here on GitHub because noone else want to answer me and they don't respond as quick as on GitHub!

Every question is about Minecraft-Modding/Coding - Those questions are about a mod that I'm about to create:

Q1_2: How can I create a Multiblock?
Q2_3: How can I let a mob attack a specific multiblock?
Q3_1: How can I create a mob that flies on a specific height?
Q4_3: How do I create a mob with a very realistic animation (like Mowzie's Mobs; without AnimationAPI)
Q5_3: How do I let a mob spawn at a Multiblock when the Multiblock is done?
Q6_2: How can I make a Container with specific, costumized slots with background?
Q7_3: How can I make a spawner that doesn't look like a normal spawner that can spawn a created mob? The "Spawner" is made out of a Multiblock!
Q8_3: How do I let the multiblock look like a TileEntity, so it isn't even a normal Multiblock with optical Blocks, but made out of physical blocks?
Q9_2: How can I add an Updater to my mod, so I only need to put some files on a server?
Q10_3: How can I add a block tha... just look here: http://pastebin.com/gjCzjHQA

I just want to bring the Clash Royale Game to MC!

**Comment by AbrarSyed** [comment]
see #349
Google.
