### ISSUE TITLE
GradleStart not loading assets

### ISSUE THREAD

**Issue by yrsegal** [MinecraftForge/ForgeGradle#352]
I've tried a bunch of things, but nothing i've done will get the IntelliJ run to work with my assets folder.

(2.1-SNAPSHOT-9e8f067)

**Comment by AbrarSyed** [comment]
If you tried everything it would be working.

What exactly is hapenning, and what exactly did you try?

**Comment by yrsegal** [comment]
What's happening: my resources folder contents aren't being included (unlocalized and untextured/unmodeled everything). gradle runClient works, but GradleStart doesn't. I tried running makeStart, too, which I saw was created for this purpose, and nothing happened.

**Comment by AbrarSyed** [comment]
If run client works, then your IDE is messed up. You using GradleStart as your main class?

**Comment by yrsegal** [comment]
Yes, I am. Only args are --username and --password.

**Comment by AbrarSyed** [comment]
Dunno. Something is wrong with your IDE. Try clearing and reinooeting. Make sure you are using the right module (if you are using idea 2016.1)

**Comment by yrsegal** [comment]
I'll try updating IDEA, but I just did `gradle cle cI cIW sDecW id gIR` and it didn't change anything.

**Comment by yrsegal** [comment]
hm. reclone and that command worked. ¯\\\_(ツ)\_/¯
