### ISSUE TITLE
Forge 1.9 setupDecompWorkspace Error

### ISSUE THREAD

**Issue by goldenpotato76** [MinecraftForge/ForgeGradle#356]
I keep getting an error when trying to setup forge for 1.9: http://pastebin.com/rpKUh9Nd

**Comment by kashike** [comment]
Duplicate of #298

**Comment by goldenpotato76** [comment]
I can't find how to add more RAM to the gradle process.....(i am not that used with those things)

**Comment by kashike** [comment]
Add this line to *USER_HOME/.gradle/gradle.propertes*: `org.gradle.jvmargs=-Xmx3G`

**Comment by goldenpotato76** [comment]
Trying it now, i hopw i put gradle.propertes in the right place...(as stated above, i am not that familiar with this)

**Comment by Brian4321** [comment]
How would I add this?

**Comment by Frontrider** [comment]
added,the error still persists.

**Comment by LexManos** [comment]
Not much we can do, you ran out fop ram, you need to give your gradle more ram.
