### ISSUE TITLE
Curse Dependencies

### ISSUE THREAD

**Issue by rallias** [MinecraftForge/ForgeGradle#360]
Since Curse integration already exists (well... for FG1.2, I haven't had a gander at it in 2.x) to upload mods, it'd be nice to be able to tell ForgeGradle "Hey, there's this mod that exists on curse, could you be an angel and grab it for me automatically?"

**Comment by AbrarSyed** [comment]
see @matthewprenger, im not the only one who wanted this.

**Comment by rallias** [comment]
Did I... did I just accidentally uncover an argument that's been going on in the background?

**Comment by AbrarSyed** [comment]
lol not really, ive been telling mathew to do this since he made that one CUrseGradle plugin of his, but he never implemented it (as far as I know).

If you look at the commit history, youl see how rarely ive been doing any FG work, so sorry, but its extremely unlikely that this change will get into FG 1.2

**Comment by rallias** [comment]
Oh, I'm totally fine with it not making it into 1.2, I just mentioned 1.2 because that's the only version that I know for sure has curse integration.

**Comment by matthewprenger** [comment]
So there isn't really a good way to do this. Curse doesn't have a proper API for getting files. They have maven access (which is dumb and requires an API key), but you don't need a plugin for that. You can just add it to your `repositories { }` and `dependencies { }`.

**Comment by AbrarSyed** [comment]
The point of the plugin is convenience. The plugin already gets access to the API key. All it needs is some info about the dependency, and it can add the repo and dependency declaration to the appropriate configuration.

**Comment by ntzrmtthihu777** [comment]
While the subject is open, does fg 2.x for 1.8.9 work with curse?

**Comment by matthewprenger** [comment]
@ntzrmtthihu777 It's a separate plugin now. https://github.com/matthewprenger/CurseGradle#cursegradle
