### ISSUE TITLE
Run client and server in different directories

### ISSUE THREAD

**Issue by MattDahEpic** [MinecraftForge/ForgeGradle#361]
Short cleanliness feature request:

Have the run directory for the client be `./run/client` and the server be `./run/server`.
Possible use case: different configs/worlds/settings for client/server.

**Comment by kashike** [comment]
This should be optional.

**Comment by TehNut** [comment]
Well we have `runDir = "blah"`. Could we have `serverRunDir = "blah/server"`?

**Comment by AbrarSyed** [comment]
```
runClient {
    workingDir = file('run/client')
}
runServer {
    workingDir = file('run/server')
}
```

The rest can be configured quite easily in your IDE for those run configs.

**Comment by Dijkstra1** [comment]
In idea you can change this run configs.
