### ISSUE TITLE
Fails to execute :makeStart

### ISSUE THREAD

**Issue by jamierocks** [MinecraftForge/ForgeGradle#364]
Gradle log: https://gist.github.com/jamierocks/dcdd30cb20714caaea33912073bfb9b5
Gradle (--stacktrace) log: https://gist.github.com/jamierocks/1b2c559647b981b34d7df633b4c434ea
Gradle (-i) log: https://gist.github.com/jamierocks/6086d4b3178347d5b3dab5b6573ea2e3

It's an issue with the Ant stuff you have: https://github.com/MinecraftForge/ForgeGradle/blob/master/src/main/java/net/minecraftforge/gradle/tasks/CreateStartTask.java#L134

`[21:49:15]  <@jamierocks>	System Information: Model: Mac Mini (Late 2014) • CPU: Intel Core i5-4278U (4 Threads, 2 Cores) @ 2.60 GHz • Memory: 8.00 GB • Uptime: 5 hours • Disk Space: 998.98 GB • Graphics: Intel Iris • Screen Resolution: 1920 x 1080 • OS: OS X El Capitan (Version 10.11.1, Build 15B42)`

My build.gradle is available https://github.com/NeptunePowered/NeptuneVanilla/blob/1.9/build.gradle

**Comment by AbrarSyed** [comment]
Tried a `gradle clean`? that might fix it.

**Comment by jamierocks** [comment]
I tried a `gradle cleanCache` but I'll try that now.

**Comment by jamierocks** [comment]
Thanks - I have it working now ;)
