### ISSUE TITLE
Gradlew "decompMc" Failure

### ISSUE THREAD

**Issue by DannyCon** [MinecraftForge/ForgeGradle#366]
I need help, I've tried using "gradlew setupDecompWorkspace", but no matter what, it slows down at decompMc, then pulls up an error reading...
(Ignore eveything weird below, apperently every symbol does something, like the star making a list...)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':decompileMc'.
> GC overhead limit exceeded

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 0.994 sec

The time varies... I did this the same thing a long time ago, and the same error occurred. On the subject of that, I'm not using the code here, but the one provided at [http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.9.html](url). (Version: 1.9 - 12.16.0.186, Download is the 'MDK' button.) Another thing, I was watching MrCrayfish's tutorial, at [https://www.youtube.com/watch?v=VhOSL7rGb10](url). When I went to go enter the new path file... It looked like this: 
![image](https://cloud.githubusercontent.com/assets/18647433/14769912/88785acc-0a31-11e6-8177-cb5ef8e6b4fc.png) (Yes the new path is already in place.) I don't know what to do, help!

**Comment by matthewprenger** [comment]
See #324

**Comment by AbrarSyed** [comment]
yal need to start searching the issues before making new ones...
