### ISSUE TITLE
RunServerDebug & RunClientDebug

### ISSUE THREAD

**Issue by TechplexEngineer** [MinecraftForge/ForgeGradle#367]
If there is a way to easily run the client or server in debug mode I can't seem to grasp how.

```gradle runClient``` works great, but I'd like to attach a debugger so I can inspect when an exception is thrown.

**Comment by AbrarSyed** [comment]
`--debug-jvm`

or you could.. ya know.. could use actual run configs.. can generate them with `gradle genIntellijRuns`
