### ISSUE TITLE
deobfCompile/deobfProvided dependency source attachment issue

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/ForgeGradle#369]
It looks like when you have a deobf\* dependency that has a classifier, like -api, the sources don't get downloaded and attached in idea like they would with the regular artifact.

**Comment by mezz** [comment]
hi @DaemonUmbra, I see this is closed, was it fixed at some point or was it closed as part of a github issues cleanup?

**Comment by DaemonUmbra** [comment]
Closed as part of cleanup, feel free to reopen if you want

**Comment by mezz** [comment]
Hmm actually, @tterrag1098 did your commit (https://github.com/MinecraftForge/ForgeGradle/pull/637) fix this issue?

**Comment by tterrag1098** [comment]
No, that PR was reverted. Pretty sure this is fixed in newer FG versions though.
