### ISSUE TITLE
FG stops extracting rangemap, if method has class?

### ISSUE THREAD

**Issue by fewizz** [MinecraftForge/ForgeGradle#371]
(Sorry for my english)

![635733238065666659](https://cloud.githubusercontent.com/assets/8060034/16043892/ab7b4fe8-324a-11e6-93ed-52969dbd80d5.png)

Extract rangemap log: http://pastebin.com/KAT9B7ne
CommandExecuteAt class fragment (look at integrated class "ProxyListener"): http://pastebin.com/Xf4DrPpE
Or maybe problem not in FG?

**Comment by oleg599** [comment]
Just move patched vanilla subclasses by bukkit to external class, Forge does not allow to modify vanilla subclasses which can be used at client and server side.

Hey @LexManos, how about say that is not Forge problem and we can't change vanilla classes?

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
