### ISSUE TITLE
Stop using deprecated setLevel for ant compiles

### ISSUE THREAD

**Issue by kenzierocks** [MinecraftForge/ForgeGradle#372]
I added this to suppress some messages from the ant compiler, but Gradle warns deprecation. I'll PR a fix at some point, this is just a reminder.

From Gradle: "LoggingManager.setLevel(LogLevel) has been deprecated and is scheduled to be removed in Gradle 3.0. If you are using this method to expose Ant logging messages, please use AntBuilder.setLifecycleLogLevel() instead."

**Comment by delvr** [comment]
As per the warning, the deprecated method has been removed in Gradle 3.0 which breaks ForgeGradle builds. I look forward to seeing this resolved so I can upgrade.
