### ISSUE TITLE
:recompileMc/:genSrgs Failing

### ISSUE THREAD

**Issue by pikachu923** [MinecraftForge/ForgeGradle#373]
My setupDecompWorkspace is failing at :recompileMc saying compile failed

ForgeGradle 2.1-SNAPSHOT-da90449
Forge 1.9-12.16.1.1887

**Comment by GirafiStudios** [comment]
Don't you need Forge Gradle 2.2 for 1.9+ ?

**Comment by pikachu923** [comment]
I just updated and now its failing at :genSrgs with an exception

ForgeGradle 2.2-SNAPSHOT-59f33ec
1.9.4-12.17.0.1980

**Comment by robin4002** [comment]
Update your JDK.
joptsimple required at least Java 1.7.

**Comment by pikachu923** [comment]
That Worked, Thanks GirafiStudios and robin4002!!

**Comment by AbrarSyed** [comment]
Oh yay, I no longer have to answer these things, I have helpful people
doing it for me :D

yay for helpful people.
