### ISSUE TITLE
2.14 incompatibility with CopyInto

### ISSUE THREAD

**Issue by kenzierocks** [MinecraftForge/ForgeGradle#375]
CopyInto uses a `null` owner (https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.2/src/main/java/net/minecraftforge/gradle/util/CopyInto.java#L40) which is unexpected since groovy closures _always_ get one and it is therefore not a nullable property. This somehow worked ok prior to 2.14 but now breaks and I would recommend that something is passed in as the owner to match Groovy's auto-generated closure creation. I can PR this if needed.

**Comment by williewillus** [comment]
Chiming in to say that using my system gradle on latest forge 1.10.x repo (FG 2.2 snapshot) breaks. System gradle version is 2.14-1, gradlew works

**Comment by AbrarSyed** [comment]
Wow.. I set the owner to null like EVERYWHERE.. please PR to all the closures, not just that one... Make it take the project as the owner or something. Careful to avoid serialization loops, as closures ate serializable.

On July 8, 2016 7:11:22 PM CDT, Kenzie Togami <notifications@github.com> wrote:
>CopyInto uses a `null` owner
>(https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.2/src/main/java/net/minecraftforge/gradle/util/CopyInto.java#L40)
>which is unexpected since groovy closures _always_ get one and it is
>therefore not a nullable property. This somehow worked ok prior to 2.14
>but now breaks and I would recommend that something is passed in as the
>owner to match Groovy's auto-generated closure creation. I can PR this
>if needed.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MinecraftForge/ForgeGradle/issues/375

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AbrarSyed** [comment]
Its been a while since this code changes.. Would have noticed long ago of it broke gradle 1.10

On July 8, 2016 7:12:59 PM CDT, Vincent Lee <notifications@github.com> wrote:
>Chiming in to say that using my system gradle on latest forge 1.10.x
>repo (FG 2.2 snapshot) breaks. System gradle version is 2.14-1, gradlew
>works
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MinecraftForge/ForgeGradle/issues/375#issuecomment-231501067

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kenzierocks** [comment]
Ok, will update all closures.

**Comment by kenzierocks** [comment]
Closing in favor of discussion on #376.
