### ISSUE TITLE
Remapping source fails for some classes

### ISSUE THREAD

**Issue by empiricist** [MinecraftForge/ForgeGradle#377]
Building a mod fails if a class in the mod's source has no import statements and also has three or more blank lines following the final closing brace.  Don't ask how long it took to figure this out.  

[Here](http://pastebin.com/MsSgAusy) is a build log with a stacktrace.  This is from using the recommended version of the MDK for 1.9.4 (1.9.4 - 12.17.0.1976) but I checked and the error is also present in the latest version for 1.10.2 (1.10.2 - 12.18.1.2018).

**Comment by LexManos** [comment]
Provide the exact source file with the least amount of code necessary to reproduce it.

**Comment by empiricist** [comment]
[This](https://github.com/MinecraftForge/ForgeGradle/files/379388/ReproduceBug.java.txt) should do it.  Tested at location src\main\java\com\example\examplemod\ReproduceBug.java in a fresh MDK.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
