### ISSUE TITLE
gradlew setupDecompWorkspace failed

### ISSUE THREAD

**Issue by MattG2002** [MinecraftForge/ForgeGradle#378]
I'm trying to create a 1.8 mod, but whenever I try to run `./gradlew setupDecompWorkspace` I get this output: (I'm on a Mac, btw)

./gradlew setupDecompWorkspace
#################################################
         ForgeGradle 2.0-SNAPSHOT        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP 9.10               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:getFernFlower SKIPPED
:decompileMc SKIPPED
:fixMcSources SKIPPED
:applySourcePatches
:remapMcSources SKIPPED
:recompileMc
[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[ant:javac] /Users/MattMac/Desktop/New Mod/build/tmp/recompileMc/sources/net/minecraftforge/client/model/obj/OBJModel.java:617: error: cannot find symbol
[ant:javac]                     material.getColor().setW(alpha);
[ant:javac]                                        ^
[ant:javac]   symbol:   method setW(float)
[ant:javac]   location: class Vector4f
[ant:javac] Note: Some input files use or override a deprecated API.
[ant:javac] Note: Recompile with -Xlint:deprecation for details.
[ant:javac] Note: Some input files use unchecked or unsafe operations.
[ant:javac] Note: Recompile with -Xlint:unchecked for details.
[ant:javac] 1 error
[ant:javac] 1 warning
:recompileMc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':recompileMc'.
> Compile failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 38.991 secs

**Comment by kashike** [comment]
What version of ForgeGradle are you using? This was [fixed](https://github.com/MinecraftForge/ForgeGradle/pull/296) a while back now.

**Comment by MattG2002** [comment]
Decided to try and install ForgeGradel for 1.10.2 instead and it worked!
