### ISSUE TITLE
Custom arguments on "genIntellijRuns"

### ISSUE THREAD

**Issue by joserobjr** [MinecraftForge/ForgeGradle#379]
I see that there are [inputs for arguments and configurations there](https://github.com/MinecraftForge/ForgeGradle/blob/59f33ecef984e6fd85df81ae7b131ef01bff1a8e/src/main/java/net/minecraftforge/gradle/patcher/TaskGenIdeaRun.java#L56) but how do I set them?

**Comment by AbrarSyed** [comment]
in the extnsion object:
https://github.com/MinecraftForge/ForgeGradle/blob/59f33ecef984e6fd85df81ae7b131ef01bff1a8e/src/main/java/net/minecraftforge/gradle/user/UserBaseExtension.java#L47-L50

```

minecraft {

    clientRunArgs += "arg1", "arg2"

}

```

it gets added to the eclipse generating one too.
