### ISSUE TITLE
Issues with generating SRG patches

### ISSUE THREAD

**Issue by oleg599** [MinecraftForge/ForgeGradle#381]
When FG generating SRG patches I always got duplicated imports in patches and sources after build.

Examples below: 

When I use imports: https://monosnap.com/file/ysI2I6gpAbzbKRnWEe544BuxeZEjZM
When I specify class directly: https://monosnap.com/file/atkNv2yM8Whi46F3W60xgIvV6CX7t4

- FG 2.2, latest Forge for MC 1.10.2

P.S If I enable generating and applying from MCP patches - issue seems like to be solved

**Comment by LexManos** [comment]
1) Why are you editing base classes
2) No clue what your setup is, it works perfectly fine in Forge/Sponge environment.

**Comment by oleg599** [comment]
My setup is basic Forge with CraftBukkit/Spigot patches, I need to modify vanilla classes because CraftBukkit/Spigot required this and I don't have any issues with FG 2.1 with MC 1.8.9

**Comment by LexManos** [comment]
Cauldron is dead, stop working on it.
Sponge is it's successor, work with them.

**Comment by bloodmc** [comment]
@oleg599 More like you are attempting to update Cauldron to 1.8+.... Cauldron has been DMCA'd and will never be supported by Forge or FG.

https://github.com/oleg599/Cauldron-Reloaded
https://github.com/oleg599/Cauldron-Old

These repos are illegal and need to be taken down.

**Comment by oleg599** [comment]
@bloodmc I work on this only for private purposes, because Sponge is not finished yet and I can't port all bukkit plugins to Sponge now.

**Comment by LexManos** [comment]
You can, hell you can port all Bukkit plugins to raw Forge.
Stop working in the past, and stop stealing other's work.
You will get no help here for this.

**Comment by mcsnetworks** [comment]
Hell even I gave up beating a dead horse, you should too.

**Comment by oleg599** [comment]
@LexManos What Istole?

 Some Cauldron patches or Bukkit/Spigot? :)

**Comment by oleg599** [comment]
Everybody here says about Bukkit is dead/DMCA, bla-bla, etc. 

But you can also got DMCA takedown, if Mojang or something else want this. You use decompiled and patched vanilla code, which does not allowed by EULA. 

Spigot also use patched vanilla code and doesn't have any issues, tons of servers now use Bukkit (Spigot) API.

Can Sponge be useful for huge projects like Hypixel if we already have Spigot? :)

**Comment by LexManos** [comment]
Sponge/Forge can work on 'huge projects' like Hypixel and the like just fine.
You obviously have no idea what you're commenting on when it comes to the DMCA issues, or legality of things. 
So we're not gunna get into that debate here.
The final word has been spoken, we will not support you re-creating Cauldron.
