### ISSUE TITLE
Unable to setup workspace for eclipse: Task 'setupDecompWorkspce' not found in root project '-Minecraft-Wily-Wonka-s-Marvelous-Mod-'

### ISSUE THREAD

**Issue by DrMeepster** [MinecraftForge/ForgeGradle#386]
Log with --info and --stacktrace options:
[log.log](https://gist.github.com/DrMeepster/f79f9b4da0a360853bf0d3a4d89309aa)

**Comment by LexManos** [comment]
Yes, I to call it Worklspce.......

**Comment by liach** [comment]
`setupDecompWorkspace`
or
`sDecW` which is easier to remember.

**Comment by AbrarSyed** [comment]
`gradle tasks` will give you a listing and what they do

**Comment by DrMeepster** [comment]
I just laughed so hard when I looked at your words and saw my spelling error. :laughing:

**Comment by LexManos** [comment]
Just a lesson in READING your error messages.
It literally tells you your problem.
