### ISSUE TITLE
When I open gradlew SetupDecompWorkSpace the setup window opens then closes.

### ISSUE THREAD

**Issue by AquaPlayzX** [MinecraftForge/ForgeGradle#387]
Location: C:\Program Files (x86)\Java\jdk1.8.0_102\bin

Log: None

**Comment by GirafiStudios** [comment]
What do you mean open? It is a command you run in the command prompt in the directory where you setup your workspace.

**Comment by AquaPlayzX** [comment]
The file is a .bat file.

**Comment by GirafiStudios** [comment]
Dude, that is not how it works.. please go read a guide about how to setup your Forge dev workspace. This is not the place for support questions.
