### ISSUE TITLE
Exceptions are added with setupDecompWorkspace, but not with setupCIWorkspace

### ISSUE THREAD

**Issue by octylFractal** [MinecraftForge/ForgeGradle#390]
In my Decomp workspace, DataSerializer.java looks like this:
```java
public interface DataSerializer<T>
{
// ...
    T read(PacketBuffer buf) throws java.io.IOException;
// ...
}
```
However, when a CI workspace is used, it looks like this (from a `forgeBin` jar decompiled):
```java
public interface DataSerializer<T>
{
 // ...
  public abstract T read(PacketBuffer paramPacketBuffer);
  // ...
}
```

**Comment by TehNut** [comment]
IIRC, `setupCIWorkspace` only does the minimal amount needed for building. It's not meant for use in a dev environment.

**Comment by diesieben07** [comment]
What you are seeing is decompiled like you said. Decompiled code looks different.

**Comment by LexManos** [comment]
Guys shutup unless you know what you're talking about.
Exceptions are added pre-decompile in the same step for both decomp and ci so it should be adding them.

**Comment by kenzierocks** [comment]
@TehNut @diesieben07 If you had read the title, you would have noticed this is not about source vs. decompiled but the presence of exceptions, which causes compile errors if they're not there (see the [travis build](https://travis-ci.org/TechShroom/LudicrousHooks/builds/174242903#L558) that alerted me to this)

**Comment by diesieben07** [comment]
Reading the title definitely helps. Sorry.

**Comment by AbrarSyed** [comment]
hmm.. something is wrong with the application od the Exceptor.. had this bug before an it was fixed.. what hapenned recently?

**Comment by liach** [comment]
@kenzierocks Agrees. See https://github.com/CovertJaguar/Railcraft as an example. When you run `./gradlew build` it fails; but when you run `./gradlew setupDecompWorkspace build` it succeed.

**Comment by liach** [comment]
@kenzierocks How about `setupDevWorkspace`?

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
