### ISSUE TITLE
Stuck Resolving Dependencies?

### ISSUE THREAD

**Issue by xtilly5000** [MinecraftForge/ForgeGradle#391]
For some reason when I use: gradlew setupDecompWorkspace && gradlew eclipse OR gradlew setupDecompWorkspace it keeps getting stuck on Resolving Dependencies ':classpath:', I have tried this on multiple computers, and for some reason it will never work. I setup all the paths up on the system AND user variables. help :/

**Comment by ghostii3005** [comment]
Did you ever fix it? I am having the same problem

**Comment by AbrarSyed** [comment]
run with `--debug`, it will probably get you better visibility into whats going on.
That part is almost purely in Gradle code and not really under our control...

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
