### ISSUE TITLE
SetupDecompWorkspace decompileMc Fails at 56%

### ISSUE THREAD

**Issue by darp25** [MinecraftForge/ForgeGradle#407]
The title says it all. I ran ./gradlew setupDecompWorkspace --stacktrace. I'm on an Ubuntu 16.04 with 2 gigs of ram, which I thought was enough. I ran it on a Windows machine with the same amount of ram flawlessly.

Output of  ./gradlew setupDecompWorkspace --stacktrace: http://pastebin.com/KNeRwx9K

Any help?

**Comment by matthewprenger** [comment]
2GB of total ram is probably not enough when you factor in what the OS itself and other programs are using. You can try running the build with `-PforkDecompile=false` to turn off the new auto-fork system. If that works, you can set it permanently for the project in a `gradle.properties` file in the project directory, or globally in `~/.gradle/gradle.properties`. Either way you use `forkDecompile=false` syntax in the file.

**Comment by darp25** [comment]
Running _./gradlew setupDecompWorkspace --stacktrace -PforkDecompile=false_ got me through the decompileMc process, but once it reaches recompileMc, it fails, complaining that there is no javac compiler.

Output of /gradlew setupDecompWorkspace --stacktrace -PforkDecompile=false: http://pastebin.com/sxs2gYjD

**Comment by darp25** [comment]
Alrighty, I was able to run the program using Ubuntu Server instead of Kubuntu and it worked.
Thanks for your help!
