### ISSUE TITLE
Need not to load  jars in ./libs as mod

### ISSUE THREAD

**Issue by LaysDragon** [MinecraftForge/ForgeGradle#408]
How can I made runClient and runServer not to load mod jars in libs as mod?
The mods in libs load in Client or Server keep error.
I need those mod jars in libs to compile mod but not to load as mod.
I have no idea how to config gradle about this.
need help.:(

**Comment by diesieben07** [comment]
That has nothing to do with Gradle. FML will load anything that's on the classpath as a mod (if it is a mod). Why do you not want mods to load?

**Comment by laysdra7265** [comment]
Actually I am trying to fix a old mod's bug without source code.(I had do it many times)
I just decompiled a small part of code and modify .
So I need to use original mod jar in classpath for compiled pass.
But I don't need it to load as mod ,or I will get duplicated mod error.
I had try to add task that remove classpath after Jar task in gradle,but not effective.(Not familiar with gradle)
Now I has to manually replace original mod's class with modified one and some manually process before runClient to avoid duplicated mod error.(not really convenience and inefficient)

**Comment by diesieben07** [comment]
You are looking for a compile-time-only dependency, which was [added in Gradle 2.12](https://blog.gradle.org/introducing-compile-only-dependencies). This is often known from the Maven world as "provided".

**Comment by laysdra7265** [comment]
oh! Thanks  for indormation.I'll take a look.:)
