### ISSUE TITLE
deobfCompile dependencies need setupCI/Dev/DecompWorkspace before build

### ISSUE THREAD

**Issue by Barteks2x** [MinecraftForge/ForgeGradle#410]
Based on what AbrarSyed told me, setupCIWorkspace should be done implicitly when running `gradle build` without any setup. This doesn't seem to work when using deobfCompile dependencies.

Gradle build output when trying that with my mod: http://pastebin.com/raw/1YPwX4XQ (using `net.malisis:malisiscore:1.11.2-5.0.1-SNAPSHOT` as example dependency).

The commit in my mod that causes the issue (slightly different version of the dependency than in the log because I already had that one when creating the log): https://github.com/Barteks2x/CubicChunks/tree/f64ee678279f30dfa01d1c36979a49810d514a9c

Travis CI log for that build: https://travis-ci.org/Barteks2x/CubicChunks/jobs/200366627

**Comment by mahtaran** [comment]
Just wondering, why was this never addressed? It is still an issue for me and it is pretty annoying.

**Comment by Niko-sk2x** [comment]
I remember at some point figuring out what in my build.gradle caused it and it was something about some of my task causing those dependencies to be resolved too early. I don't remember the exact cause anymore.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
