### ISSUE TITLE
[Quick fix] Update comment on TaskSingleReobf

### ISSUE THREAD

**Issue by thecodewarrior** [MinecraftForge/ForgeGradle#411]
The header comments for TaskSingleReobf are outdated, they say to use `extra "PK: ..."` when it has to be `extraLines "PK: ..."`

Incorrect comment: https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.2/src/main/java/net/minecraftforge/gradle/user/TaskSingleReobf.java#L81-L86

Proper names: https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.2/src/main/java/net/minecraftforge/gradle/user/IReobfuscator.java

(Not quite so quick, but updating the section of the RTD about shading would be nice, even just a small "hey, just so you know it's been changed to be `reobf { jar { extraLines ... } }`" would be nice. Not complaining, I'm notorious for my bad docs)

**Comment by LexManos** [comment]
It needs to be updated to explain that its appears to have been split between extraLine and addSecondarySrgFile as well

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
