### ISSUE TITLE
ApplyFernFlowerTask not respecting gradle.properties JVM setting

### ISSUE THREAD

**Issue by radfast** [MinecraftForge/ForgeGradle#414]
Problem: Hardcoded to "-Xmx3G" here:

https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.2/src/main/java/net/minecraftforge/gradle/tasks/fernflower/ApplyFernFlowerTask.java#L138

Result:  if the user sets different JVM settings in ```gradle.properties```, the user settings will be used by tasks until the **:decompileMC** task is reached.  **:decompileMC** executes ApplyFernFlowerTask and so uses this hard-coded JVM setting.  This will cause a crash, if -Xmx3G is not good for the user's machine.

**Comment by LexManos** [comment]
It splits it if you don't have enough ram. There is also a flag to disable this because people complained. There are many options. It isn't going to change

**Comment by radfast** [comment]
It appears that [this](https://github.com/MinecraftForge/ForgeGradle/issues/405) may be the **only** documentation for the "flag to disable this". :/
