### ISSUE TITLE
setupDecompWorkspace seems to skip most steps on successful first run

### ISSUE THREAD

**Issue by Driky** [MinecraftForge/ForgeGradle#416]
I new to the forge modding stuff, so I might have misunderstood something. But I'm pretty sure that on
`gradlew setupDecompWorkspace`
graddle is supposed to download a bunch of stuff and do some decompiling and compiling. As you can see on the following output, mine isn't doing most of the task it is supposed to do.

Any help appreciated.

```
#################################################
         ForgeGradle 2.2-SNAPSHOT-7f5a769
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:decompileMc SKIPPED
:fixMcSources SKIPPED
:applySourcePatches
:remapMcSources SKIPPED
:recompileMc SKIPPED
:extractNatives SKIPPED
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 1193/1196   99%
:makeStart
:setupDecompWorkspace

BUILD SUCCESSFUL
```

**Comment by Driky** [comment]
The problem might come from the fact that on the first run graddle crashed mid execution. I deleted the folder graddle inside my user folder to redo all steps cleanly.

**Comment by Driky** [comment]
Now when I load the project it seems that the dependancies are not loaded. All the following are missing if I use the example project : 
```
import net.minecraft.init.Blocks;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
```

**Comment by Driky** [comment]
ok so it seems i missed the step : 

> Finally, assuming you use IDEA 2016 or newer, you will have to fix the classpath module. Go to Edit configurations and in both Minecraft Client and Minecraft Server, change  Use classpath of module to point to the task with a name like <project>_main.

But i cannot execute that step since no other choice appear in the dropdown to change the classpath.

It might be related to that error that I get : 

> java.lang.RuntimeException: java.io.FileNotFoundException: Resource nexus-maven-repository-index.properties does not exist

**Comment by LexManos** [comment]
Skipped gradle tasks mean that they did run before and are do not need to be repeated for this run.
There is a central gradle cache in your user directory that holds all this information.
This is working as intended.
