### ISSUE TITLE
Using Notch instead of searge mappings

### ISSUE THREAD

**Issue by teammaxxer** [MinecraftForge/ForgeGradle#419]
Hello,
i want to use Notch instead of searge mappings but it seems that its not working.
i tried it using
`reobf {
    setMappingType(net.minecraftforge.gradle.user.ReobfMappingType.SEARGE)
}` and
`reobf {
    useNotchSrg()
}`
in my build.gradle but i get a method not found error everytime

**Comment by LexManos** [comment]
Its not supported, searge mappings are there for a reason, Runtime contains searge names and in the future this will be pre-baked so there will be no option for otherwise.

**Comment by teammaxxer** [comment]
wow. thanks.

**Comment by killjoy1221** [comment]
This roughly documents the reobfuscation specification.

https://gist.github.com/killjoy1221/c9487befa9cafd65054f
