### ISSUE TITLE
[1.2] files.minecraftforge.net: connection timed out

### ISSUE THREAD

**Issue by gamerforEA** [MinecraftForge/ForgeGradle#420]
Sometimes files.minecraftforge.net is not available, due to what the use of ForgeGradle becomes impossible. Is there anything you can do about it?

gradle.log: https://pastebin.com/Cjpbdca5
Command line screenshot: https://prnt.sc/f9asnz

**Comment by matthewprenger** [comment]
The `--offline` flag will tell gradle to work offline.

**Comment by LexManos** [comment]
OVH had issues.

**Comment by gamerforEA** [comment]
Thanks, matthewprenger.
