### ISSUE TITLE
Compiling modified Minecraft

### ISSUE THREAD

**Issue by xrgv** [MinecraftForge/ForgeGradle#421]
I'm using MCP to compile a client with modifications written in Scala, and I'm tired of editing its custom build system. By the look of the things ForgeGradle has all of the needed functionality, but it's used for another purpose and internals are not very much documented. Could you please clarify which tasks should I use to

- decompile without extending MC with Forge patches;
- compile decompiled MC source code back?

**Comment by LexManos** [comment]
You don't. FG is not here for you to make direct modifications to minecraft. It has that functionality so that we can use it in Forge. Or other APIs can. But the way of JarModding is dead. Stop trying to revive it.
