### ISSUE TITLE
gradlew setupDecompWorkspace error with decompileMc

### ISSUE THREAD

**Issue by cbggamer** [MinecraftForge/ForgeGradle#422]
Hello guys
I was trying to code a mod for minecraft using forge mdk 1.8.9 and i`m getting this error
https://gist.github.com/cbggamer/6db82355260d5a1e85fa1bc93fd261eb
plz help me
ty

(Sorry for my english)

**Comment by kashike** [comment]
See #324.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
