### ISSUE TITLE
gradle idea not specifying module in the run configurations

### ISSUE THREAD

**Issue by The-Fireplace** [MinecraftForge/ForgeGradle#425]
Every time I run gradle idea, it doesn't specify the module in the run configurations, so before the first run after doing that, I have to use the dropdown and manually set it.
![image](https://user-images.githubusercontent.com/5914284/27190718-1001c380-51bb-11e7-9a60-32961e29c5b2.png)
[My build.gradle](https://github.com/The-Fireplace/Mob-Rebirth/blob/ecc6904815658b87966c4bf94f3f6493029757c3/build.gradle)

EDIT: I forgot to mention, I am using gradle 3.5

Steps I use to reproduce:
1.) Open a Powershell window in the folder with my build.gradle
2.) run "gradle idea"
3.) Open the project in Idea
4.) Attempt to run the project.

Expected behavior: It runs on the first try, no extra configuration needed
Actual behavior: It opens the Run Configuration window for the one I am trying to run(Client or Server), and I have to specify the module.

**Comment by AbrarSyed** [comment]
see https://github.com/MinecraftForge/ForgeGradle/pull/351

**Comment by Xalcon** [comment]
Ok, i took some time to look into this.
This only happens, if you use the `idea` task to create the project files. If you take a look into the `PROJECT.iws` file you can see that forge gradle appends `_main` to the module for each run configuration. The `idea` uses the current path as the module name though. Thats why intellij shows `<no module>`; it cant find it.

The module configuration happens in https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.3/src/main/java/net/minecraftforge/gradle/user/UserBasePlugin.java#L1283
This works just fine if you import the build.gradle and tell IntelliJ to create a source set for each module; but it doesnt work if you use the `idea` task to create the project files.

How to get things working atm:
* Project from Existing sources
* Select `build.gradle` 
* Make sure **Create separate module per source set** is **checked**; use Project Format: .idea (Directory based)
* Wait until intellij has imported and build the project
* Open the gradle task window and execute the `genIntellijRuns` task (or run via terminal)
* Done

I was also toying around with getting the `idea` task to work without breaking the `genIntellijRuns` task, and this is what I came up with. Its not fully tested yet but I was able to generate valid project files via the `idea` tasks and the `genIntellijRuns` run configs look good as well.
https://gist.github.com/Xalcon/7044aaf98eb7dcff5ffa00d0d3cb07ae

If I find some more time (and motivation), ill look into it a bit more and do a PR. If someone else wants to do it in the meantime: have fun :P

**Comment by thecodewarrior** [comment]
This seems to have come back even when importing the gradle script into IDEA. When I manually set the module the run configuration XML changes from `moduleName_main` to `moduleName.main`. I don't know why IDEA changed its naming scheme but there was recently an update that deprecated the non-*Create separate module per source set* behavior, so they may have made some changes along the way there.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
