### ISSUE TITLE
MCP Does not start

### ISSUE THREAD

**Issue by cbggamer** [MinecraftForge/ForgeGradle#426]
Hello, Guys!
I was trying to decompile the MCP, however, it is not starting I literally waited 12 hours to start and nothing happened plz help me
sry english

**Comment by killjoy1221** [comment]
1. This isn't a support forum.
2. This isn't MCP
3. You need to use the command line, not double click `gradlew.bat`
4. https://mcforge.readthedocs.io/en/latest/gettingstarted/
