### ISSUE TITLE
Gradlew - Error on run "gradlew setupDecompWorkspace eclipse"

### ISSUE THREAD

**Issue by Sejoslaw** [MinecraftForge/ForgeGradle#428]
I'm sorry if I posted this issue in wrong repository.

Forge used: forge-1.12-14.21.1.2387-mdk (Recommended)

I did try to run the command `gradlew setupDecompWorkspace eclipse`. It started fine and downloaded all required libraries. After short time it crashed with this issue (I cut-out all the class bodies. The whole paste was too big for free-user pastebin). Also a stacktrace is included at the end:
[gradle.log](https://pastebin.com/bgkpfSWz)
It looks like it crashed in `fixMcSources` 

Whole file is here:
[full gradle.log ](https://ufile.io/gj0cn)

**Comment by kashike** [comment]
I'm guessing you tried to use ForgeGradle 2.2-SNAPSHOT first. The easiest way to fix this is to run `gradle cleanCache`.

**Comment by Sejoslaw** [comment]
I changed 2.2 to 2.3 and run command `gradlew cleanCache` and after that `gradlew setupDecompWorkspace eclipse` worked :)
Thank You :)
