### ISSUE TITLE
Intellij and provided/deobfProvided

### ISSUE THREAD

**Issue by TechnicianLP** [MinecraftForge/ForgeGradle#433]
I basically have a dependencies-section with:
`dependencies { provided fileTree(dir: "libraries", include: "*.jar") }`
but in intellij the libraries in that folder still show up in the "compile"-scope (which causes "my" environment to crash upon starting minecraft) 
the same happens for entries with  spcified with `deobfCompile`

Is there any way to get this working?
What i want is a dependency to only be there at compile-time on not at runtime (but intellij does not seem to care about the runtime-part and just adds it anyways ...)

So far i only got trolled by idea ... this: idea `{ module { scopes.COMPILE.plus.clear() }}`should according to the [documentation](https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.idea.model.IdeaModule.html) remove all compile-dependencies - but it does nothing

**Comment by Barteks2x** [comment]
I actually reported it to intellij because even manually changing the scope in project structure doesn't work. Just forgot about the issue and didn't reply to tem witha test case: https://youtrack.jetbrains.com/issue/IDEA-174300

**Comment by AbrarSyed** [comment]
if using a newer build of gradle, they added `compileOnly` which is kinda the same as provided.

**Comment by TechnicianLP** [comment]
Yeah this was what i ended up with as a workaround: https://hastebin.com/siwewabibi.txt

**Comment by Barteks2x** [comment]
This is most likely to be a ForgeGradle issue as adding this code:
```groovy
afterEvaluate {
    sourceSets.main.runtimeClasspath.each {println it}
}
```

clearly shows that the deobfProvided dependency is listed in runtime classpath. So Intellij has no way to determine the scope correctly, and based on the fact that it's both in compile and rumtime classpath, it probably concludes that it's "compile" scope.

**Comment by Keridos** [comment]
Got a similar issue here, on my Intellij IDEA 2017.2.5 and ForgeGradle 2.3 the deobfCompile dependencies are correctly added to the project, but not to the compile classpath, which they should be. Did not happen in FG 2.2.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
