### ISSUE TITLE
Gradle 4 compatibility

### ISSUE THREAD

**Issue by xaeroverse** [MinecraftForge/ForgeGradle#435]
To be clear up front, developing a mod with Gradle 4.0 works fine, it's just compiling FG with it that fails.

Log:  https://gist.github.com/xaeroverse/57464ef6454e9c8dc9710e7ccfcfee12

It seems that Gradle 4.0 removed the @ParallelizableTask annotation in their API.  I don't have time to look into this so I'm not sure what the replacement is (if any; it could be redundant now).  Nevertheless, I don't expect this to be high priority anyway since downgrading Gradle compiles fine and fixing it might mean losing backwards compatibility with older Gradle versions.

**Comment by matthewprenger** [comment]
More info about `@ParallelizableTask` being removed: https://discuss.gradle.org/t/parallelizabletask-is-removed-in-gradle-4-0/22970. From the sounds of it, unless you set a gradle config option, the annotations never actually did anything.

**Comment by Pokechu22** [comment]
This was fixed a while back in 3b167e971bea9c250683df4b62586d46d98197df; everything builds fine with Gradle 4.4.1.  It compiles with Gradle 4.6, but the tests fail due to #469; still, this issue can probably be closed.
