### ISSUE TITLE
Maven doesn't seem to support DSL plugin syntax

### ISSUE THREAD

**Issue by LeafHacker** [MinecraftForge/ForgeGradle#439]
I am trying to use [DSL plugin syntax](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) in a build script:

```gradle
plugins {
    id 'java'
    id 'net.minecraftforge.gradle.tweaker-client' version '2.3-SNAPSHOT'
}
```

Without configuring `pluginManagement.repositories` this won't work because of #438 however even when configuring the following it doesn't work:

```gradle
pluginManagement {
    repositories {
        maven {
            url 'http://files.minecraftforge.net/maven'
        }
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.namespace == 'net.minecraftforge.gradle') {
                useModule 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
            }
        }
    }
}
```

Produces the following errors:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/leaf/Dev/minecraft/TestForgeDSL/build.gradle' line: 29

* What went wrong:
Plugin [id: 'net.minecraftforge.gradle.tweaker-client', artifact: 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- maven(http://files.minecraftforge.net/maven) (snapshot plugin versions are not supported)
- Gradle Central Plugin Repository (explicit artifact coordinates are not supported by this source)
```

Or without the `resolutionStrategy` this error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/leaf/Dev/minecraft/TestForgeDSL/build.gradle' line: 29

* What went wrong:
Plugin [id: 'net.minecraftforge.gradle.tweaker-client'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- maven(http://files.minecraftforge.net/maven) (plugin dependency must include a version number for this source)
- maven(http://repo.spongepowered.org/maven) (plugin dependency must include a version number for this source)
- Gradle Central Plugin Repository (plugin dependency must include a version number for this source)
```

**Comment by MinecraftPlaye** [comment]
Would really be nice to have this feature here. I've lately updated all my Gradle build scripts and the Forge buildscripts are the only ones keeping the old `buildscript` syntax as the new syntax is not supportet.

**Comment by Barteks2x** [comment]
This actually happens because ForgeGradle is always a snapshot, see https://github.com/gradle/gradle/issues/3902

**Comment by carif** [comment]
[This has been resolved in Gradle 4.10.](https://github.com/gradle/gradle/issues/3902#issuecomment-400617865) Thought it seems like FG currently does not work on 4.10 or higher as of #552.

**Comment by LexManos** [comment]
FG 2.x- will always be snapshots. This isn't going to be changed.
FG3 now has unique version numbers, but I doubt the central repo wants to host every build we ever make. So we'll probably never publish to them either.

**Comment by snowe2010** [comment]
>  FG3 now has unique version numbers, but I doubt the central repo wants to host every build we ever make. So we'll probably never publish to them either.

you don't need to publish to central, you could just make sure to publish the `*.gradle.plugin` file and then people could use a custom resolutionStrategy.
