### ISSUE TITLE
[Suggestion] Let jar task get finalized by reobfJar

### ISSUE THREAD

**Issue by BrainStone** [MinecraftForge/ForgeGradle#440]
It has come to my attention that if you are not careful with your build scripts, it is easily possible that you depend on the jar task from upload tasks, meaning that the jar (which should be obfuscated) is not obfuscated jet, since the reobfJar task has not be run.

In the build script this is easily fixable by doing this:

```Groovy
jar {
    // Do whatever you need here...

    finalizedBy reobfJar
}
```

I think this should be the default behavior for ForgeGradle 2.2 and 2.3

**Comment by AbrarSyed** [comment]
No. Plenty of reasons when you might want an unobfuscated jar. One example is a multiproject build.
just do `dependsOn reobfJar` for your upload task.

**Comment by BrainStone** [comment]
Is this caviat documented somewhere? Because many modders get that wrong when uploading artifacts.

**Comment by AbrarSyed** [comment]
Actually, as long as you specify the `maven` plugin before ForgeGradle, it automatically adds the reobf task as a dependency: https://github.com/MinecraftForge/ForgeGradle/blob/ac7f579d79a0df1fad0a44ef5c827dc23422d1c0/src/main/java/net/minecraftforge/gradle/user/UserBasePlugin.java#L222

This isnt the case if you use the newer maven-publishing plugin

**Comment by BrainStone** [comment]
It's still a big caveceat for new modders or modders that don't know gradle. I mean this issue happend in Mantle which belongs to the most downloaded core mods on curseforge.

I most certainly understand the downsides of doing that but keep in mind that if you know gradle you can work around this. If not it's a big frustration and error trap.

**Comment by nallar** [comment]
The way reobfJar works just now also means that the jar task is always ran.

reobfJar should probably create a separate artifact instead of overwriting the original. This allows up-to-date checking to work on the jar task, and allows you to correctly depend on the reobfed or the non-reobfed jar easily.
