### ISSUE TITLE
Give replace() optional third parameter specifying file to modify

### ISSUE THREAD

**Issue by xbony2** [MinecraftForge/ForgeGradle#441]
So then
```gradle
replace "%%%VERSION%%%", project.version
replaceIn "LongFallBoots.java"
```
can be simplified to
```gradle
replace "%%%VERSION%%%", project.version, "LongFallBoots.java"
```
if desired. This would be a lot cleaner than using `replaceIn`.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
