### ISSUE TITLE
mcp standalone library plugin

### ISSUE THREAD

**Issue by LeafHacker** [MinecraftForge/ForgeGradle#446]
Similar to #122, I would like a forgegradle plugin that doesn't require building a mod, patcher or tweaker.

I am considering developing a small library that needs to import minecraft classes, but will not modify minecraft in any way. My specific example is a library that parses markdown input and outputs a `TextComponent`, but obviously this is applicable to any library using minecraft classes without being a mod/etc.

This would be more or less the same as the tweak class plugin, other than the fact that no tweak class is specified. The generated dependencies and compile tasks would be more or less the same.

The built jar would obviously only include the project code, not the decompiled minecraft code, as with any other forgegradle project.

- [ ] Ability to setup a decompiled workspace
- [ ] Ability to build searge mapped jars
- [ ] Ability to build notch mapped jars
- [ ] Ability to build searge mapped source jars
- [ ] Ability to build mcp mapped source jars

**Comment by LexManos** [comment]
How do you propose that this 'library' be used?
The runtime environment is different on all those platforms...

**Comment by AbrarSyed** [comment]
There is the tweaker plugin that mumfrey uses to develop liteloader

On September 6, 2017 12:43:52 PM CDT, LexManos <notifications@github.com> wrote:
>How do you propose that this 'library' be used?
>The runtime environment is different on all those platforms...
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MinecraftForge/ForgeGradle/issues/446#issuecomment-327560284

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AbrarSyed** [comment]
And here is an example build.gradle for it: https://github.com/AbrarSyed/fgTest/blob/master/tweaker/build.gradle

notice that the plugin is `tweaker-client`, there is also `tweaker-server` if you want a workspace made from the server jar.

- [x] Ability to setup a decompiled workspace
- [ ] Ability to build searge mapped jars
- [x] Ability to build notch mapped jars
- [ ] Ability to build searge mapped source jars
- [ ] Ability to build mcp mapped source jars
