### ISSUE TITLE
./gradlew setup(Ci|Dev|Decomp)Workspace build won't resolve deobfCompile dependencies until setup(Ci|Dev|Decomp)Workspace task is ran alone without build

### ISSUE THREAD

**Issue by Barteks2x** [MinecraftForge/ForgeGradle#450]
It seems like gradle will try to resolve dependencies before the setup*Workspace task has a chance to run.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
