### ISSUE TITLE
Forge mdk setup failed

### ISSUE THREAD

**Issue by MineProjectZ** [MinecraftForge/ForgeGradle#455]
when i try to setup forge mdk i get this error:
https://pastebin.com/YDvmMgr2
I have the newest version of JDK 8 and JRE 8 installed.

**Comment by jriwanek** [comment]
If you're still around @MineProjectZ, what version of Forge (Not ForgeGradle), and what version of Minecraft?

**Comment by MineProjectZ** [comment]
it is alreade solved. i forgot to close it
