### ISSUE TITLE
gradle exception : com.cloudbees.diff.PatchException

### ISSUE THREAD

**Issue by ohadguetta** [MinecraftForge/ForgeGradle#458]
java version:

```
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```
gradle -v:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/o4255/Desktop/minecraft%20mods%20porting%20and%20coding/gradle-4.3.1/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9.0.1 (Oracle Corporation 9.0.1+11)
OS:           Windows 10 10.0 amd64
```

error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fixMcSources'.
> com.cloudbees.diff.PatchException: Cannot find hunk target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

```

#26 didn't work for me, pls do not close this thread!

**Comment by TehNut** [comment]
You cannot use Java 9 for mod development

**Comment by ohadguetta** [comment]
@TehNut I downgrade for Java 8, still the same problem

**Comment by TehNut** [comment]
What version of MC and FG? How much memory are you allocating?

**Comment by ohadguetta** [comment]
1.8.9 mc
build.gradle file:
`minecraft {
    version = "1.8.9-11.15.1.2318-1.8.9"
    runDir = "run"
    
    // the mappings can be changed at any time, and must be in the following format.
    // snapshot_YYYYMMDD   snapshot are built nightly.
    // stable_#            stables are built at the discretion of the MCP team.
    // Use non-default mappings at your own risk. they may not allways work.
    // simply re-run your setup task after changing the mappings to update your workspace.
    mappings = "stable_20"
    // makeObfSourceJar = false // an Srg named sources jar is made by default. uncomment this to disable.
}`

**Comment by LexManos** [comment]
Run cleanCache and try again on a J8 JDK.

**Comment by ohadguetta** [comment]
@LexManos not working.

**Comment by LexManos** [comment]
be more descriptive. And use the forums for basic tech support.
