### ISSUE TITLE
Syntax error on the variable 'Version' when running setupDevWorkspace (Mac OS X El Capitan 10.11.6)

### ISSUE THREAD

**Issue by yameatmeyourdead** [MinecraftForge/ForgeGradle#460]
Following a tutorial made by Lex [🔗](https://www.youtube.com/watch?v=xp2jmt47yTQ)  and it worked perfectly, but now I'm getting a syntax error

My Folder: 
![screen shot 2017-12-18 at 11 52 09 am](https://user-images.githubusercontent.com/20462595/34122504-e8d60ee4-e3e9-11e7-932e-debb62e64931.png)

Logs: 
Edited [build.gradle](https://pastebin.com/1rZW8HJp)
Terminal [Output](https://pastebin.com/TvERsSrq) (No Stacktrace or Debug)
(Long) Terminal [Output](https://pastebin.com/95bjB5Aq) (Stacktrace)
(Very Long) Terminal [Output](https://pastebin.com/sHmgyXpq) (Debug)

No idea what caused this, worked yesterday.
Attempted changing Version to just "1" but then got syntax errored on the :

if(file('../run').exists()){
 runDir = "../run"
}
else{
 runDir = "run"
}﻿

I was told to replace runDir = "run" with that ^^

Reverting the replaced code still returns the original syntax error

Tried deleting everything, redownloading and restarting but still returns these errors.

**Comment by diesieben07** [comment]
These: “” are not a normal quotation marks. Get a proper computer/os/text editor (delete as appropriate) that does not mess with what you type in.
