### ISSUE TITLE
[forge development] Cannot find GradleStart in intellij idea

### ISSUE THREAD

**Issue by liach** [MinecraftForge/ForgeGradle#461]
This issue is for forge itself only. `gradle setupForge` sets up a development environment for forge. When opening `projects` project from the root folder, in intellj idea, the run configurations for clean/forge client/server exist, but they are all erroneous since idea cannot find `GradleStart` and `GradleStartServer` in classpath. eclipse, in contrast, can find `GradleStart` and `GradleStartServer`, thus it can launch forge with test mods.

**Comment by ConorTheOreo** [comment]
Change "Use classpath and SDK module" to  *your project name*_main

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ConorTheOreo** [comment]
Just realised this was 2 months old

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DarkCat09** [comment]
I change the option "Use classpath or module".
Intellij IDEA shows message "Warning: Class "GradleStart" not found in module ..."
How I can fix it?

**Comment by liach** [comment]
Also this is about the forgegradle for forge itself (not for your forge mods!), and was on forgegradle 2, which is no longer supported. Obsolete.
