### ISSUE TITLE
Could not resolve all dependencies for configuration

### ISSUE THREAD

**Issue by acadus** [MinecraftForge/ForgeGradle#465]
I'm trying to setup ForgeGradle for the 14.23.0.2491-mdk and I keep receiving the same error when I try to run setupDecompWorkspace:

https://pastebin.com/CRNnHmkr

**Comment by jriwanek** [comment]
Looks like you were behind a proxy or some variety of transparent firewall.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
