### ISSUE TITLE
Cannot resolve dependencies and SDK modifications made in Intellij

### ISSUE THREAD

**Issue by 0xlsca** [MinecraftForge/ForgeGradle#471]
So, I waned to spice up my MC Java experience and add some custom Lombok Annotation handlers, however I ran into a major blocker which is gradle being unable to resolve both the tools.jar in my %SDK%/lib folder and the lombok dependency.

[build.gradle](https://pastebin.com/AFR43wrC)

["gradlew buid" yields this](https://pastebin.com/AsTK6Dgc) but [the dependency shows up correctly under "gradlew dependencies".](https://pastebin.com/TxBAR7uR)

Is this now an IDEAj, Gradle or Forge Gradle issue? 

EDIT: I can verify that the library has been correctly downloaded

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
