### ISSUE TITLE
Multiple litemod.json files are present before reobf

### ISSUE THREAD

**Issue by Pokechu22** [MinecraftForge/ForgeGradle#476]
When using liteloader's `litemod` task to generate litemod.json, multiple litemod.json files are present in the jar before reobf happens.  While this seems to be fixed later on during reobf, it still seems to be a problem.

To reproduce:
1. Download the [liteloader example mod](http://develop.liteloader.com/liteloader/ExampleMod/tree/master).
2. Run `gradle jar` which makes the jar but does not apply reobf.
3. Open the created jar in `build/libs` using e.g. 7-zip.
4. Observe that there are multiple files named `litemod.json` inside of it, one for the one found in src/main/resource and one generated by the `litemod` task.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
