### ISSUE TITLE
Clean up `Throwables.propagate` usage

### ISSUE THREAD

**Issue by liach** [MinecraftForge/ForgeGradle#479]
Currently, it is observed during compilation that 16 usages of `Throwables.propagate` exist in ForgeGradle's latest FG_2.3 branch (as of c9bb57920456fb8e982c43c71d8726102d307b09). Since the usage of `propagate`s have been removed in forge itself already, I believe that cleaning this up may be necessary, too.

**Comment by LexManos** [comment]
It's not strictly necessary, but its on my to-do eventually. Its just a lot of copy/paste.

**Comment by liach** [comment]
Fixed in def00039474de8e3af0962f442b9025e0e6df2be. Thanks so much lex!
