### ISSUE TITLE
I don`t setup MDK, please help me =(

### ISSUE THREAD

**Issue by Rumaruka** [MinecraftForge/ForgeGradle#481]
Okay, It`s very strange problem
But i try told about this
Im grab new version forge and usually starting make project (If  you think im change somathing - nope)
And catch this:
![screenshot_2](https://user-images.githubusercontent.com/8148679/37288533-58ee1e16-2629-11e8-9cc4-3ab40c3f72cc.png)

"Oh okay, maybe updating gradle" - thinking, im did this
Nope DON`T WORK.
Im change different version forge - don`t work
Error with version forge build 
I need help, guys =(

**Comment by liach** [comment]
it is in the format of mcversion-forgeversion, e.g. 1.6.4-9.11.1.965

**Comment by Rumaruka** [comment]
I don't change build file,  then all right "mcversion-forgebuild"

**Comment by liach** [comment]
post your build.gradle on github gist and link here

**Comment by LexManos** [comment]
Forums
