### ISSUE TITLE
Gradle skipping everything

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/ForgeGradle#492]
When I run "gradlew setupDecompWorkspace" I get "To honour the JVM settings for this build a new JVM will be forked. Please consi                                                                                                                der using the daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html.
This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-27b9d44
  https://github.com/MinecraftForge/ForgeGradle
#################################################
                 Powered by MCP
             http://modcoderpack.com
     by: Searge, ProfMobius, R4wk, ZeuX
     Fesh0r, IngisKahn, bspkrs, LexManos
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:decompileMc SKIPPED
:fixMcSources SKIPPED
:applySourcePatches SKIPPED
:remapMcSources SKIPPED
:recompileMc SKIPPED
:extractNatives SKIPPED
:getAssetIndex UP-TO-DATE
:getAssets
Current status: 108/1283   8%
Current status: 209/1283   16%
Current status: 323/1283   25%
Current status: 510/1283   39%
Current status: 634/1283   49%
Current status: 815/1283   63%
Current status: 950/1283   74%
Current status: 1065/1283   83%
Current status: 1212/1283   94%
:makeStart
:setupDecompWorkspace

BUILD SUCCESSFUL

Total time: 1 mins 55.855 secs
" therefore I cannot decompile Minecraft.

**Comment by Barteks2x** [comment]
This usually means it's already decompiled, unless something went wrong in your gradle cache.

**Comment by Keridos** [comment]
It is already decompiled. So this is no issue unless your cache is broken. You can technically try using cleanCache but remember this will need you to do the whole workspace setup again.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
