### ISSUE TITLE
Code that builds when set up with setupDecompWorkspace, fails when set up with setupCiWorkspace

### ISSUE THREAD

**Issue by Exidex** [MinecraftForge/ForgeGradle#498]
Came across what seems to be a bug in ForgeGradle. I have a custom registry that extends `RegistryNamespaced`. The jar builds fine if setup with `setupDecompWorkspace`, but fails when using `setupCiWorkspace` or `setupDevWorkspace` with compile error:
```
> Task :compileJava 
.../GregTechCE/build/sources/main/java/gregtech/api/util/GTControlledRegistry.java:11: error: Iterable cannot be inherited with different arguments: <> and <T>
public class GTControlledRegistry<T> extends RegistryNamespaced<String, T> {
       ^
```
After some experiments I got this: 
```
> Task :compileJava
/home/exidex/Documents/GregTech/build/sources/main/java/gregtech/api/util/GTControlledRegistry.java:16: error: type IObjectIntIterable does not take parameters
public class GTControlledRegistry<T> extends RegistrySimple<String, T> implements IObjectIntIterable<T> {
                                                                                                    ^
```
which means that `IObjectIntIterable` has no parameters when set up with `setupCiWorkspace` but has one when set up with `setupDecompWorkspace`

**Comment by Pokechu22** [comment]
See also #472

**Comment by LexManos** [comment]
Thats a known issue and I haven't decided how I want to address it.
That data simply doesnt exist in the obfusicated jar file and we have to patch it manually.
#472 is solved with the change to MCInjector and only tangentially related.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
