### ISSUE TITLE
Allow per-IDEA-module 'start' library

### ISSUE THREAD

**Issue by Aaron1011** [MinecraftForge/ForgeGradle#504]
Currently, each IDEA module receives its own Minecraft classes jar.

However, the `start` library (which contains `GradleStartServer`, `GradleStartCommon`, and `GradleStartServer` is currently shared between all modules in a project. Since `GradleStartCommon` contains module-specific information - [the MCP mappings to use for deobfuscation](https://github.com/MinecraftForge/ForgeGradle/blob/4a7d6236848b792ac4b99a620fff489209d7cf2d/src/main/resources/net/minecraftforge/gradle/GradleStartCommon.java#L45-L51) - a multi-module project will not have the proper MCP mappings applied for each module run configuration. Instead, the MCP mappings from the most recently run `setupDecompWorkspace` will be used for all modules.

It would be helpful if ForgeGradle could generate a `start` library on a per-module basis, similar to how each module receives its own `minecraft_serverSrc` jar. This would allow an Intellij project to contain mutliple different run configurations, each targeting a different module.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
