### ISSUE TITLE
ForgeGradle maven repository doesn't have Plugin Marker Artifacts

### ISSUE THREAD

**Issue by Barteks2x** [MinecraftForge/ForgeGradle#508]
As of gradle 4.10 it will be possible to use the new plugins syntax for snapshpot versions, and this feature is already available in latest 4.10 nightly build of gradle. But for it to work correctly, the plugin repositories need [Plugin Marker Artifacts](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers), otherwise gradle won't be able to resolve the plugin by ID.

While the old `apply plugin: ` syntax still works, the new plugins syntax allows gradle kotlin DSL to automatically generate all the right accessors, without the need for the buildscript top successfully compile and configure, which allows to simplify the buildscript, and avoid relying on exact class names from plugins.

Currently it's possible to work around the issue by specifying a custom resolution strategy in `settings.gradle` like this:

```groovy
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.toString() == 'net.minecraftforge.gradle.forge') {
                useModule('net.minecraftforge.gradle:ForgeGradle:' + requested.version)
            }
        }
    }
    repositories {
        maven {
            setUrl("http://files.minecraftforge.net/maven")
        }
    }
}
```

**Comment by LexManos** [comment]
You would have to verify that everything works fine on 4.10+. last i checked, fg broke on higher gradle versioms do to internal changes.
Ama is working on a full replacement, whuch we can see about addressing this on.

**Comment by Barteks2x** [comment]
Everything I need seems to work fine in that gradle version. Unless something breaks for actual forge development.

**Comment by Caellian** [comment]
Might be related: https://scans.gradle.com/s/eqlikfk4imsse/
Gradle 5.0, FG 2.3-SNAPSHOT

**Comment by liach** [comment]
@caellian fg is not designed to be gradle 5 compatible. you are off-topic here.

**Comment by NikkyAI** [comment]
as mentioned here https://github.com/SpongePowered/MixinGradle/issues/8#issuecomment-453331410
using the `java-gradle-plugin` and `maven-publish`
plugin identifier in `META-INF/` will be created 
and the publish task will also take care of the marker for maven

https://docs.gradle.org/4.10-rc-2/userguide/java_gradle_plugin.html#example_using_the_gradleplugin_block

**Comment by ntvangoor** [comment]
Can this be reopened now that fg is updated to 6.8?

**Comment by LexManos** [comment]
Honestly? No. As we don't really give a crap about the extra metadata that gradle wants.
It doesn't hurt anything to not have it. And it opens up a lot of weird potential side cases that I don't have the willpower to dig into gradle internals to figure out what the hell breaks.  Combined with the fact that we not have unique identifiers for each version, not -SNAPSHOT. This shouldn't be an issue.

It's not worth the effort.

**Comment by sciwhiz12** [comment]
After reconsideration, we are now planning to generate and publish plugin marker artifacts for ForgeGradle, through PR #858. I am reopening this issue so it will be (automatically) closed as completed once the PR is merged.
