### ISSUE TITLE
Run/Debug configuration application main class GradleStart shows as red

### ISSUE THREAD

**Issue by RexTheCapt** [MinecraftForge/ForgeGradle#509]
When i add a new Run/Debug application configuration and set the "Main class" to "GradleStart" it shows up as red. I am following a tutorial on youtube and when they do this step it [shows up as blue](https://youtu.be/RZ66HdNkank?t=14m35s)

Then i did try to follow [this video](https://youtu.be/G2aPT36kf60) i get the same red text. I did do what he did but with never version.

version= 1.12.2-14.23.4.2705
mappings= snapshot_20180716
did not upgrade wrapper

When it comes to run minecraft i press the green play button and ["Edit configuration" pops up instead of a minecraft client and this is the window](https://imgur.com/WLDx1gL)

**Comment by DaemonUmbra** [comment]
Did you try setting the "Classpath of Module" box to use [YourMod]_main ? When I do that it still shows red text but it launches.

**Comment by derimagia** [comment]
The error is on the bottom, "Module not specified". Try number 5 here: https://mcforge.readthedocs.io/en/latest/gettingstarted/#terminal-free-intellij-idea-configuration

**Comment by RexTheCapt** [comment]
I only get two options in the "Use classpath of module" list. "<no module>" and "forge*mdk".

Here is a screenshot https://imgur.com/U39Lhzb

**Comment by RexTheCapt** [comment]
@derimagia i still can't find a sollution

**Comment by derimagia** [comment]
If you try to run it what error do you get?

**Comment by RexTheCapt** [comment]
In the build console i get the error `java: invalid source release: 9`, i have no idea what that means. After i have run the gradle task genIntellijRuns and edit the configuration for "Minecraft Client" the main class is still red. Updated the gradle config to use the latest forge and yesterdays mappings. If you wan't i can make a little short video that shows what i do.

**Comment by derimagia** [comment]
Sounds like you need to set your project to be using Java 8

**Comment by derimagia** [comment]
In your IDE, similar to https://stackoverflow.com/a/26009627/9741606

**Comment by RexTheCapt** [comment]
Followed the instructions in the link, ran the gradle task setupDecompWorkspace, ran genIntellijRuns, selected minecraft client and clicked play `Error: java: invalid source release: 9`, checked the config for the task and same as always.

**Comment by RexTheCapt** [comment]
I am pretty sure i have done that.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
