### ISSUE TITLE
ForgeGradle trouble with JDK 10

### ISSUE THREAD

**Issue by Blu3FireEdeN** [MinecraftForge/ForgeGradle#514]
Hello, i have a problem with the Minecraft Forge installation.

Here's my error :
https://scans.gradle.com/s/dxaajaft54bus/

JavaSE Version : 10.1
Gradle Version : 4.9
Minecraft Forge Version : 14.23.4.2746

Followed tutorial : http://mcforge.readthedocs.io/en/latest/gettingstarted/

Thanks.

**Comment by Blu3FireEdeN** [comment]
Issue solved.
I upgraded Gradle to 4.10 version 
and i did "gradlew setupDecompWorkspace -Djava.ext.dirs="" "

**Comment by jriwanek** [comment]
Not really a fix, *dont* use Java 10 for minecraft modding yet, Forge isn't compatible with Java >8 currently
