### ISSUE TITLE
Fallback for McpMappings.json is getting old

### ISSUE THREAD

**Issue by GotoLink** [MinecraftForge/ForgeGradle#515]
While trying to build a updated mod to latest forge version, i got a really old mapping downloaded by gradle.
http://files.minecraftforge.net/maven/de/oceanlabs/mcp/versions.json
Instead of the recent one
http://export.mcpbot.bspk.rs/versions.json
Which results in "No such version" error.
The only way to solve it was to replace the file manually and build with gradlew in --offline mode.

**Comment by Pokechu22** [comment]
Both of those files seem to have the exact same contents to me (with the latest 1.13 mapping being 20180823).  MCPBot is currently down right now so that might be why it's getting old -- it's not pushing new mappings?

**Comment by GotoLink** [comment]
From my point of view, latest forge maven mappings are snapshot_20180402, for 1.12.

**Comment by Pokechu22** [comment]
1.13 seems to be listed after 1.12 (I'm not sure why; perhaps because there wasn't a stable build?).

**Comment by GotoLink** [comment]
Here is what i see.
![forgemaven](https://user-images.githubusercontent.com/2155547/44626382-76f85f00-a91b-11e8-8d16-5ad99e46277c.png)

![mcpbot](https://user-images.githubusercontent.com/2155547/44626386-811a5d80-a91b-11e8-801b-c10e257c2350.png)

**Comment by amadornes** [comment]
Looks just fine on my end.

![both URLs returning the same file](https://user-images.githubusercontent.com/2066666/44627930-28f15480-a937-11e8-95a4-be9a25f3cbc4.png)

Try clearing your caches or use incognito mode, maybe?
This may also be one of those stupid ISP-level caches, which would be... a problem.

**Comment by GotoLink** [comment]
Huh seems ISP level.
Got a different result by checking through https instead.
Sorry for the invalid ticket, and thanks for the help.

**Comment by LexManos** [comment]
For future reference, bspkrs/the bot is responsible for pushing that file. Not on our end if its outdated.
