### ISSUE TITLE
FG3 server pipeline missing download version JSON

### ISSUE THREAD

**Issue by Earthcomputer** [MinecraftForge/ForgeGradle#517]
To reproduce, take a similar buildscript as the one in Forge's 1.13-pre branch at the moment, and replace the line `pipeline = 'joined'` with `pipeline = 'server'`.
Then, running `gradlew setup` gives the following error:
```
Could not find a step of type net.minecraftforge.gradle.mcp.function.DownloadVersionJSONFunction
```
This is due to https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/mcp/java/net/minecraftforge/gradle/mcp/function/AbstractDownloadMCFunction.java#L21 assuming that the pipeline contains a function to download version json, which the server pipeline is currently missing.

**Comment by LexManos** [comment]
Fixed in MCP config, and small hack fix in FG until I push replacements.
