### ISSUE TITLE
Default Eclipse run configurations cause crashes when attempting to load mods in /run/mods while in deobfuscated environment.

### ISSUE THREAD

**Issue by Pheenixm** [MinecraftForge/ForgeGradle#519]
[Example of crash with Mekanism
](https://pastebin.com/tbH0032Z)

Issue can be resolved by removing "-DFORGE_FORCE_FRAME_RECALC=true" from the VM arguments in ForgeGradle auto-generated launch configurations. 

Example of broken run configuration: 
`<?xml version="1.0" encoding="UTF-8"?>
<launchConfiguration type="org.eclipse.jdt.launching.localJavaApplication">
   <stringAttribute key="org.eclipse.jdt.launching.MAIN_TYPE" value="GradleStart" />
   <stringAttribute key="org.eclipse.jdt.launching.PROJECT_ATTR" value="GraphLib" />
   <stringAttribute key="org.eclipse.jdt.launching.WORKING_DIRECTORY" value="/Users/NAMEGOESHERE/git/GraphLib/run" />
   <stringAttribute key="org.eclipse.jdt.launching.VM_ARGUMENTS" value=" -DFORGE_FORCE_FRAME_RECALC=true" />
</launchConfiguration>`

Example of functional run configuration: 
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration type="org.eclipse.jdt.launching.localJavaApplication">
<listAttribute key="org.eclipse.debug.core.MAPPED_RESOURCE_PATHS">
<listEntry value="/Explosives+"/>
</listAttribute>
<listAttribute key="org.eclipse.debug.core.MAPPED_RESOURCE_TYPES">
<listEntry value="4"/>
</listAttribute>
<booleanAttribute key="org.eclipse.jdt.launching.ATTR_USE_START_ON_FIRST_THREAD" value="true"/>
<stringAttribute key="org.eclipse.jdt.launching.MAIN_TYPE" value="GradleStart"/>
<stringAttribute key="org.eclipse.jdt.launching.PROJECT_ATTR" value="Explosives+"/>
<stringAttribute key="org.eclipse.jdt.launching.WORKING_DIRECTORY" value="/Users/NAMEGOESHERE/git/Explosives+/run"/>
</launchConfiguration>
`

The failure appears to have something to do with the ASM lib. Changing the default runtime config to not contain this VM argument would likely resolve the bug entirely

**Comment by LexManos** [comment]
Asked and answered many times.
Some configs it works, some configs it doesn't. Its required on more systems then it is not so its the default.
If you have issues, remove it.

**Comment by BrainStone** [comment]
Would it be possible to get a flag/variable in the `minecraft {}` block, so it can be excluded automatically?
