### ISSUE TITLE
FG3 not downloading OSX natives

### ISSUE THREAD

**Issue by grondag** [MinecraftForge/ForgeGradle#520]
Appears to be a regression of the issue fixed by PR #424 and described here: https://github.com/MinecraftForge/MinecraftForge/issues/3964

Example error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/grondag/MinecraftForge/build.gradle' line: 69

* What went wrong:
A problem occurred evaluating root project 'Forge'.
> A problem occurred configuring project ':clean'.
   > Could not resolve all files for configuration ':clean:downloadDeps0'.
      > Could not find java-objc-bridge-natives-osx.jar (ca.weblite:java-objc-bridge:1.0.0).
        Searched in the following locations:
            https://repo.maven.apache.org/maven2/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar
```

**Comment by LexManos** [comment]
Feel free to make a PR to fix this, i'm far to busy getting other stuff working to debug a OS issue I don't have.

**Comment by DaemonUmbra** [comment]
This appears to be a Mojang goof, I can't find a file by that name anywhere besides the libraries.minecraft.net link in the version JSON, and the file it points to is a repacked dylib that's already in the generic JAR.

Edit: Got both jars and extracted the dylibs... same SHA1

**Comment by grondag** [comment]
Yeah, I can make a PR for it this weekend.  The last fix was an egregious hard-coded hack so hopefully that's OK.  Doesn't seem worth getting fancy for this.

**Comment by JDLogic** [comment]
Got this fixed and then never got around to making a PR. On its way now...

**Comment by LexManos** [comment]
Merged PR
