### ISSUE TITLE
Failure to download ForgeVersion.json creates confusing error message

### ISSUE THREAD

**Issue by Aaron1011** [MinecraftForge/ForgeGradle#523]
In [setForgeVersionJson](https://github.com/MinecraftForge/ForgeGradle/blob/ee3e3dffe8e2d79acbed87a9455e89d0fb94c724/src/main/java/net/minecraftforge/gradle/user/patcherUser/forge/ForgePlugin.java#L151), ForgeGradle sets the `forgeJson` field to `null` when certain errors occur, without logging any message.

This later causes an NPE on [this line](https://github.com/MinecraftForge/ForgeGradle/blob/ee3e3dffe8e2d79acbed87a9455e89d0fb94c724/src/main/java/net/minecraftforge/gradle/user/patcherUser/forge/ForgeExtension.java#L269). If gradle is run without the `--stacktrace` option, the generated NPE will appear to come from **the users' build.gradle**, which is extremely misleading.

ForgeGradle should emit a warning or error when an error occurs during the resolving of `ForgeVersion.json`, to make it clear to the user that there's no issue with their `build.gradle`.

**Comment by Aaron1011** [comment]
For reference: this condition appears to have been triggered by an issue with the Forge maven repository. The maven server was abruptly closing the connection partway through the download, resulting in an invalid json file being parsed by ForgeGradle.

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
