### ISSUE TITLE
Could not determine java version from '10.0.2'

### ISSUE THREAD

**Issue by Souttak** [MinecraftForge/ForgeGradle#532]
I've this problem when I do the 'gradlew setupDecompWorkspace' thing, I'll apreciate so much your help with this.

`C:\Users\facun\Desktop\Minecraft Modding\ModPrueba>gradlew setupDecompWorkspace
Downloading https://services.gradle.org/distributions/gradle-2.14-bin.zip
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping C:\Users\facun\.gradle\wrapper\dists\gradle-2.14-bin\76oc0mnc3ieqtsukq90mp0rxk\gradle-2.14-bin.zip to C:\Users\facun\.gradle\wrapper\dists\gradle-2.14-bin\76oc0mnc3ieqtsukq90mp0rxk

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10.0.2'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

C:\Users\facun\Desktop\Minecraft Modding\ModPrueba>`

**Comment by liach** [comment]
please do not use java 9 or higher.

**Comment by Souttak** [comment]
So I just have to install an old version and try it again? I've already done the JAVA_HOME
![image](https://user-images.githubusercontent.com/45322362/48974389-0229e380-f036-11e8-9bde-fc2cb4268b60.png)

**Comment by Souttak** [comment]
I've fixed it installing the JDK 8 instead of 10, and modifying the Path and JAVA_HOME system variables. Thank you liach.
