### ISSUE TITLE
[FG2.3] [Bug] CI build issues with using generics

### ISSUE THREAD

**Issue by UpcraftLP** [MinecraftForge/ForgeGradle#538]
When using a ci workspace (`setupCIWorkspace`), some generics fail to load properly.
see [this Travis Build](https://travis-ci.com/GlassPane/GlassPane/builds/95531313 "Glasspane build 49 on travis-ci.com") for an example.

However, when setting up the workspace using `setupDevWorkspace` or `setupDecompWorkspace` everything (sometimes) compiles fine, see [this build](https://travis-ci.com/GlassPane/GlassPane/builds/95963447 "Glasspane build 59 on travis-ci.com") and contrary [this build](https://travis-ci.com/GlassPane/GlassPane/builds/95963458 "Glasspane build 60 on travis-ci.com").

EDIT: inconsistencies only appear when using `setupDevWorkspace`, but it'll always work when using `setupDecompWorkspace`

**Comment by DaemonUmbra** [comment]
Closing this issue as it does not appear to be applicable to the currently supported ForgeGradle branch (``FG_3.0``).

If I am incorrect in this regard, please create a new issue prefixed with ``[FG_3.0]`` and containing:
* A summary of the issue (in case the issue has mutated slightly or the original report was poorly described)
* Steps to recreate the issue
* Console output or logs (if possible)

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
