### ISSUE TITLE
[FG3.0] [Mac] GLFW windows may only be created on the main thread

### ISSUE THREAD

**Issue by GoryMoon** [MinecraftForge/ForgeGradle#540]
I encountered an issue with mac and trying to run 1.13.
When trying to start the client everything runs until the game tries to create the window and then the following crash happens:
https://haste.gorymoon.se/haqusubuvo.mccrash

The fix for this is to include `-XstartOnFirstThread` in the JVM args when starting the client.
I tested this by adding the JVM args to the task in FG3.0 in [UserDevPlugin.java](https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/userdev/java/net/minecraftforge/gradle/userdev/UserDevPlugin.java) and it works as intended.
       
```java
task.setJvmArgs(Collections.singleton("-XstartOnFirstThread"));
```

Because I don't know if you want to add JVM args like you do normal args and environment variables or just add a special case I didn't make a pull for it.
Tested by loading FG as a `Composite Build` into a mdk workspace.

The code in LWJGL that needs this is in [EventLoop.java](https://github.com/LWJGL/lwjgl3/blob/015c9a95b5ac98fa53e7e5ba359541b12e6798de/modules/lwjgl/glfw/src/main/java/org/lwjgl/glfw/EventLoop.java)

#### Versions
Forge: 24.0.55-1.13-pre
Mappings: 20181008-1.13
FG: Latest from FG https://github.com/MinecraftForge/ForgeGradle/commit/56559d371b402463854bf667d7f05d501cf94a38

**Comment by Pokechu22** [comment]
This argument is specified in [the 1.13.2 version manifest](https://launchermeta.mojang.com/v1/packages/df66b5a5f451d026c356ead8caf118c71919850b/1.13.2.json) as applying to mac only, with some other arguments only applying on other platforms:

```json
{
  "arguments": {
    "game": ["-snip-"],
    "jvm": [
      {
        "rules": [
          {
            "action": "allow",
            "os": {
              "name": "osx"
            }
          }
        ],
        "value": [
          "-XstartOnFirstThread"
        ]
      },
      {
        "rules": [
          {
            "action": "allow",
            "os": {
              "name": "windows"
            }
          }
        ],
        "value": "-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump"
      },
      {
        "rules": [
          {
            "action": "allow",
            "os": {
              "name": "windows",
              "version": "^10\\."
            }
          }
        ],
        "value": [
          "-Dos.name=Windows 10",
          "-Dos.version=10.0"
        ]
      },
      {
        "rules": [
          {
            "action": "allow",
            "os": {
              "arch": "x86"
            }
          }
        ],
        "value": "-Xss1M"
      },
      "-Djava.library.path=${natives_directory}",
      "-Dminecraft.launcher.brand=${launcher_name}",
      "-Dminecraft.launcher.version=${launcher_version}",
      "-cp",
      "${classpath}"
    ]
  }
}
```

Ideally forgegradle should use those values directly.  The other ones are less important (other than the stack size one for 32-bit OS's) but probably should also be respected.

**Comment by GoryMoon** [comment]
Noticed this was still open, this has been fixed for a while now.

@JDLogic Also with the new launcher the `-Xss1M` in the manifest is correctly matched on the system [launch.diff](https://gist.github.com/GoryMoon/cf1112f9a191dfc007cac2c3e0bcff45), it was recognized as an issue in the launcher [MCL-10408](https://bugs.mojang.com/browse/MCL-10408)
