### ISSUE TITLE
[FG3.0] Unable to depend on side specific Minecraft dependencies

### ISSUE THREAD

**Issue by gabizou** [MinecraftForge/ForgeGradle#549]
Reviewing [`MinecraftUserRepo`](https://github.com/MinecraftForge/ForgeGradle/blob/03e818a66eef8205156524eaf5d46e86a6e75b85/src/userdev/java/net/minecraftforge/gradle/userdev/MinecraftUserRepo.java#L263)'s `findFile`, I can't see any way to get the dependency to resolve a `Side` so that one could depend on say `net.minecraft:server` or `net.minecraft:client`. Instead, it's hardwired to always provide a `net.minecraft:joined` dependency.

Easy way to reproduce: 
```
dependencies {
  minecraft "net.minecraft:server:1.13"
}

minecraft {
  mappings channel: "snapshot", version: "20180921-1.13"
  runs {
    server = {
      workingDirectory project.file('run').canonicalPath
      source(sourceSets.main)
    }
  }
}
```
The resulting dependency brought by `MinecraftUserRepo` will end up providing a joined jar, even though `MinecraftRepo` will happily provide a server *sided* jar, and `MCPRepo` will provide `null` since it's told that `MinecraftRepo` will provide sided mapped jars.

I haven't quite monkeyed around enough with trying to re-split the jars after AT's, injectors, and mappings are provided, but I've narrowed in on [`MinecraftUserRepo#findRaw`](https://github.com/MinecraftForge/ForgeGradle/blob/03e818a66eef8205156524eaf5d46e86a6e75b85/src/userdev/java/net/minecraftforge/gradle/userdev/MinecraftUserRepo.java#L427) starting with a joined jar (which is understandable, since injecting the start classes needs to reference client classes for recompilation) and never quite doing anything to split the jar for the sided dependency.

On further investigation and tinkering, it appears attempting to provide a sided dependency is more difficult to do since MCP's injected source includes the `net.minecraft.client.Main` references, which won't compile on a server specific dependency. Attempting to provide such a jar does work when modifying the `findRaw` in `MinecraftUserRepo`, but when `findSources` is used, the [MCP steps doesn't have enough information to be able to specifically inject only client or only server allowed sources](https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/mcp/java/net/minecraftforge/gradle/mcp/function/InjectFunction.java#L88) (there's only one client specific source, the `Start` class). While the steps are all being followed for a proper "side", it's not possible to determine what to exclude when injecting sources for sidedness.

**Comment by gabizou** [comment]
Updated issue description after some tinkering and investigation, `MinecraftUserRepo` isn't the only one affected attempting to supply recompiled and sources jars for sided dependencies, because the [`InjectFunction`](https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/mcp/java/net/minecraftforge/gradle/mcp/function/InjectFunction.java#L88) will have little to no information to be able to figure out what side an injected source requires, let alone the dependency that is being injected into (if the dependency had a side, and the source had a side, it'd be easy to detect it). I'm not sure what to modify at that point as there's a reliance on MCP's zip/config along with FG passing along information to arrive at that point.

**Comment by LexManos** [comment]
It is not intended for 3rd parties to develop 'only  client, or only server' patchers. If you're making a patcher do it against the joined source. As  for your analyses of InjectFunction, it only injects MCP stuff, which it has all the information it needs. 

But for vanilla itself, https://github.com/MinecraftForge/ForgeGradle/commit/097dd2a7145a3a4384ffa77876a55fe0b46b6551 might help. Let me know.
