### ISSUE TITLE
Import hanging

### ISSUE THREAD

**Issue by kashike** [MinecraftForge/ForgeGradle#550]
The project gets stuck synching - it has been running for nearly an hour at this point:
![x](https://i.imgur.com/YmuR9qf.png)

```
Parallel execution is an incubating feature.

> Configure project :SpongeCommon
New Dep: net.minecraft:server:1.13_mapped_snapshot_20180921-1.13_at_b27072188f97db9a65ca30c03163920147b4c84d

> Configure project :
New Dep: net.minecraftforge.test:forge:1.13-24.0.116-1.13-pre_mapped_snapshot_20180921-1.13_at_b27072188f97db9a65ca30c03163920147b4c84d

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE SUCCESSFUL in 5s
```

It is "solved" by following these steps, though it may take more than one try:
1. Force-stop the refresh process in IntelliJ
2. Run `./gradlew build --refresh-dependencies`
3. Refresh IntelliJ project

**Comment by LexManos** [comment]
IntelliJ has a habit of assigning very little ram and using random daemons for Gradle projects.
If you can find a way to debug this, and add more ram. Or at the very least post the console/build log 
 (one that isn't 1/2 deleted because gradle has a fancy self-deleting interface) instead of just random IntelliJ screenshots as they arnt helpful.

**Comment by kashike** [comment]
There's no way to tell IntelliJ to use `--debug` or anything else, and it only hangs within IntelliJ. I don't use the default RAM, I have it set to a larger value. There isn't anything else I really *can* provide. :/

**Comment by gabizou** [comment]
@kashike configure global gradle config to enable debugging, and you can attach a debugger (remote application) to debug itself), or configure the global gradle properties in your user folder to enable finer logging.

**Comment by Aaron1011** [comment]
I'm experiencing the same issue.

**Comment by Aaron1011** [comment]
I just got a stacktrace from the hanging gradle process: https://gist.github.com/Aaron1011/5328492a0aaa0e036e88d575d8f00ee6

**Comment by Aaron1011** [comment]
This seems wrong: https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/common/java/net/minecraftforge/gradle/common/util/BaseRepo.java#L79

This is synchronizing on a local variable created in that method. This will usually do nothing, unless that string happens to be the same object (as opposed to a freshly created one) in another thread.

**Comment by LexManos** [comment]
https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#intern()

**Comment by Aaron1011** [comment]
Oops - I didn't see the call to `intern` at the end.

In that case, this appears to be 'just' a deadlock between two Gradle threads

**Comment by Unnoen** [comment]
Should have been fixed by https://github.com/MinecraftForge/ForgeGradle/pull/555. Reopen if issue persists.
