### ISSUE TITLE
[FG2.3] ForgeGradle 2.3 builds no longer working as of today

### ISSUE THREAD

**Issue by starcraft66** [MinecraftForge/ForgeGradle#556]
As of today, one of my Minecraft mods using ForgeGradle 2.3 no longer builds, there have been no changes to `build.gradle` and the gradle build just fails with

```
* What went wrong:

A problem occurred evaluating root project 'forgehax'.

> No such version exists!
```

We are using gradle 4.10.0.

See the full stack trace here: https://jenkins.nhackindustries.com/blue/organizations/jenkins/ForgeHax/detail/master/8/pipeline

**Comment by DaemonUmbra** [comment]
This is a known issue with a version index on the Forge server, not a bug with FG.

**Comment by tterrag1098** [comment]
MinecraftForge/MinecraftForge#5477

**Comment by PanSzelescik** [comment]
Duplicates :D

**Comment by LexManos** [comment]
Oh wait, this was actually reported to the correct repo. This has been fixed however, https://github.com/MinecraftForge/ForgeGradle/commit/583a8e655fc8111ec15f3efcc555c5809b39f13c

As well as the upload issues. So grab the latest with --refresh-dependencies and you should be good.

**Comment by clienthax** [comment]
Appoligies it hadnt pulled the latest on that one,

current one just pulled and following output for stable-5 spongeforge

* What went wrong:
A problem occurred evaluating script.
> You must specify the full forge version, including MC version in your build.gradle. Example: 1.12.2-14.23.5.2811

**Comment by LexManos** [comment]
Then specify the full version of Forge.
Or PR in the old functionality.

**Comment by Unnoen** [comment]
What do you have in your build.gradle for minecraft.version?

**Comment by starcraft66** [comment]
Issue resolved on my end.
