### ISSUE TITLE
Offers to solve the dependencies downloading issue in China

### ISSUE THREAD

**Issue by lss233** [MinecraftForge/ForgeGradle#558]
Hi,
I'm a developer from China. It is known that due to our special network circumstance, we often have trouble in downloading dependencies from [Forge Maven](https://github.com/MinecraftForge/ForgeGradle/blob/097dd2a7145a3a4384ffa77876a55fe0b46b6551/src/common/java/net/minecraftforge/gradle/common/util/Utils.java#L70) and some other repos,.
I set up a mirror server in China, trying to improve the download process, but I failed because these repos are hardcoded in ForgeGradle. 

The mirror url is: http://crystal.lss233.com.oglrtic.cn/repositories/minecraft/
 _Backup url: https://lss233.com/artifactory/minecraft_

Can you add it to the ForgeGradle?
Or, just provide a option for us to specify the repo servers when downloading MCP, Assets, and some other files?

We have spent time and efforts on this issue. It would be great if you can help us.
Thank you.

**Comment by forestbat** [comment]
I think it's a good maven source and I have used it for many times because of the Great Fire Wall.

**Comment by LexManos** [comment]
We will not use any unofficial service. This is gradle you can already configure your own repos. We're not here to help China.

**Comment by liach** [comment]
I think the correct solution is to remove all hardcoded reference to forge maven/forge website so that proxy websites can be used.
