### ISSUE TITLE
[Forge-1.13.2-45.0.x/IntelliJ] Importing build.gradle as project fails for MDK examplemod

### ISSUE THREAD

**Issue by CatRabbit499** [MinecraftForge/ForgeGradle#563]
Importing and running the MDK build.gradle as a project using IntelliJ fails to download dependencies.

Error: `Caused by: java.lang.IllegalStateException: ProjectScopeServices has been closed.`

![2019-02-22_09h46_13](https://user-images.githubusercontent.com/15235082/53250918-6a19b580-3689-11e9-8e33-e9af2bba780f.png)

**Comment by CatRabbit499** [comment]
Running the build with --stacktrace via Powershell yields this error: [Link](https://gist.github.com/CatRabbit499/c5ca03b3f95f4f2892d4bf23fc55b2fc)

**Comment by SamboyCoding** [comment]
Run with --no-daemon to fix it. I spent several hours trying to work this one out.

**Comment by SamboyCoding** [comment]
In idea make sure your gradle.properties contains `org.gradle.daemon=false`

**Comment by mccreery** [comment]
Be careful with `gradle.properties`. Gradle seems to prioritise `GRADLE_USER_HOME` over the project directory, so if you have the same file there it might override and inadvertently enable the daemon.

**Comment by Da-Technomancer** [comment]
I'm having the same issue with Forge 1.14.2-26.0.25 (newest) and both gradle 4.9 (default version for forge) & 5.4.1 (newest). 
Running with --no-daemon seems to prevent the process from running at all- it just gets stuck on the first step of starting the daemon. 

Am I missing something?

**Comment by AlexCouch** [comment]
Try running ``clean`` before reimporting. I believe it has to do with gradle caches.

**Comment by DaemonUmbra** [comment]
The workaround for this is stopping the daemon (``gradlew --stop``), as intellij's Gradle integration is based on it they ignore the setting to disable it.

**Comment by Attack8** [comment]
> The workaround for this is stopping the daemon (`gradlew --stop`), as intellij's Gradle integration is based on it they ignore the setting to disable it.

Thanks so much for this!! it seemed to work for me!

**Comment by srcres258** [comment]
Executing `./gradlew --stop` and then re-syncing Gradle in IDEA solved my problem.

**Comment by erayerdin** [comment]
Seems like at some version of Intellij IDEA, IDE started ignoring `gradlew --stop`. The only way is to restart IDE.
