### ISSUE TITLE
Offline Build Issue FG_3.0

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/ForgeGradle#572]
ForgeGradle 3.0.1xx can't build offline because it tries to download the minecraft versión manifest from mojang repo and fails because it doesn't catch the UnkownHostException resulting in an error.

Edit: I live in Cuba... in case nobody reads the latest comments..

I'm closing this, I hope someone in the forums know what should I do...

**Comment by ghost** [comment]
More detailed, it's caused by DownloadMCMeta class at method downloadMCMeta, when it's building the inputstream it gets an exception if it's offline...
That exception is not caught and execution can't continue further.

**Comment by DaemonUmbra** [comment]
The point of this task is to download a file, how should that file be replaced if it cannot be downloaded?

**Comment by Pokechu22** [comment]
If the file is already downloaded, it shouldn't try to download again if the build is offline.  If the file hasn't yet been downloaded, the build should fail.  IIRC that's the same behavior gradle uses for regular dependencies.

**Comment by LexManos** [comment]
Its a standard task, with standard task caching. So yes thats the behavior it does.
Offline builds are dubious at best tho. You need the metadata to know what libraries to include.
If you want to submit a PR to 'fix' this go for it, but I dont think it needs fixing.

**Comment by ghost** [comment]
i live in cuba, i can only use my cellphone to download the file...

**Comment by ghost** [comment]
I used to trick ForgeGradle 2.3 with maven local and a manually settled up cradle cache so it doesn't complain...but I can't pull that of again...seems that now it's different...
and, yes, I had to download every .pom and .jar and every asset of Minecraft manually... 1000+ download by cellphone...yeah...pain...

**Comment by ghost** [comment]
So by caching...so you mean something human tweakable or a lot of files marked by horrible binary metadata?

**Comment by ghost** [comment]
Yeah...why do I ask, of course it's metadata...

**Comment by ghost** [comment]
I shouldn't submit a PR... It seems unnecessary... after all... it's only me the one with the issue... I'm probably the only Minecraft 1.13.2 + Forge user in my town...for not saying in my country...
most people don't even know what is java...
