### ISSUE TITLE
forge:extractRangeMap is not working?

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/ForgeGradle#580]
Version: 3.0.115 
`forge:extractRangeMap` has not finished after 20mins and has 0% CPU load.

Version 3.0.110:
`forge:extractRangeMap`  finishes in under 10 minuits, and has significat CPU load (about 1 core).

Log output is for both version the same (Powershell):
`> gradlew genPatches --no-daemon`

```
> Task :clean:compileJava

> Task :mcp:setupMCP
Setting up MCP environment
Initializing steps
Executing steps
 > Running 'downloadManifest'
 > Running 'downloadJson'
 > Running 'downloadClient'
 > Running 'downloadServer'
 > Running 'stripClient'
 > Running 'stripServer'
 > Running 'merge'
 > Running 'rename'
 > Running 'mcinject'
 > Running 'listLibraries'
 > Running 'forgeAccessTransformer'
 > Running 'decompile'
 > Running 'inject'
 > Running 'patch'
MCP environment setup is complete

> Task :forge:compileFmllauncherJava

> Task :forge:compileJava

> Task :forge:extractRangeMap
Unsupposrted library path: C:\Users\T³p\.gradle\caches\modules-2\files-2.1\de.oceanlabs.mcp\mcp_snapshot\20180921-1.13\c0dbdc4588889e083624b346f86e148aae928b8e\mcp_snapshot-20180921-1.13.zip

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 16m 31s
22 actionable tasks: 21 executed, 1 up-to-date

```

**Comment by LexManos** [comment]
you would need to provide the logs for the extract range task.
But im going to guess it has to do with your username.

**Comment by mcenderdragon** [comment]
I guess so too. Where are the logs saved?

**Comment by mcenderdragon** [comment]
OK I have found the logs, and now it worked also with 115. The process had CPU usage and the output logs are binary the same (checked with KDiff3). I dont know what I had messed up last time. If this should happen again I will get the logs and reopen this issue. 
Thank you for the support.
