### ISSUE TITLE
 Deobsfucate Minecraft without applying Forge patches or importing Forge code

### ISSUE THREAD

**Issue by chexo3** [MinecraftForge/ForgeGradle#582]
I'm trying to decompile and deobsfucate minecraft, but it seems like MCP packaging has fallen by the way side. The mappings are there, MCPBot exists of course, but how do I use them? I don't want to use Forge right now, I just want to apply Notch > SRG > MCP mappings to a modern version of Minecraft.

**Comment by williewillus** [comment]
you can set up a forge dev environment (the environment used to work on forge itself), which will give you two decompiled codebases: one "clean" MCP deobfuscated one, and one with forge patches applied.

Though, for all purposes, MCP is basically an inseparable part of forge now.

**Comment by LexManos** [comment]
Do not create jar mods. MCP as a tool chain  has been dead for ages. Let jar modding die. if you just want to read vanilla code.  then the are many tools that deobf jars.

**Comment by chexo3** [comment]
I'm not trying to make a jar mod. I'm trying to make a launchwrapper tweaker. And as far as I'm concerned, before 1.6 forge was a jar mod. Thank you Vincent.

**Comment by LexManos** [comment]
Better, but you still shouldn't be coremodding. And yes, Forge's job is to be the one that edits the base classes so.you dont have to. It originally started put as a jar mod, but things evolve. You can even load those old versions without modifying the jar now. So there is no reason to jar mod.

**Comment by chexo3** [comment]
I'm trying to get unmodified code so I can use a tweaker to modify the base classes. I don't want to use Forge for this, I want to write my own code here.
