### ISSUE TITLE
[FG3] Dependencies polluting Maven pom files.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/ForgeGradle#584]
As of ForgeGradle 3 all dependencies are being added to the Maven pom file, including those mapped by MCP. This leads to several major issues when using other mod dependencies in your dev environment.
1. Forge itself is added to the maven dependencies. This means that you and all your dependencies need to use the same version of Forge.
2. Dependencies have the MCP names added to their version, meaning that you and all your dependencies need to use the same MCP snapshot/version. 

A log of the exception that is thrown when Forge/MCP versions do not match can be found [here](https://gist.githubusercontent.com/darkhax/076ff445942e1fa892079b1d6beb98f4/raw/475fe714fae52016016886d17fdd3bf7ce7f7572/gradle.log). 

Some example pom files.
[Bookshelf 4.0.8](https://maven.mcmoddev.com/net/darkhax/bookshelf/Bookshelf-1.14.2/4.0.8/Bookshelf-1.14.2-4.0.8.pom)    
[CraftTweaker 5.0.0.1](https://maven.blamejared.com/com/blamejared/crafttweaker/CraftTweaker/1.14.2-5.0.0.1/CraftTweaker-1.14.2-5.0.0.1.pom)

There are two workarounds for this issue. The mod implementing the dependency can mark it as transitive, as shown [here](https://github.com/MinecraftForge/ForgeGradle/issues/584#issuecomment-493315204). The mod being depended on can also configure their maven upload task to remove these dependencies, as shown [here](https://github.com/MinecraftModDevelopment/Gradle-Collection/blob/master/minecraft/maven_nomcp.gradle#L30-L44)

**Comment by mezz** [comment]
@Cypher121 could you take a look at this? It may be an edge case bug related to `fg.deobf`.

**Comment by Cypher121** [comment]
will do later today

**Comment by Cypher121** [comment]
So the good news: issue is reproducible with the full buildscript, and switching to version 3.0.5 or 3.0.6 makes the error go away, so you can do that for now

The bad news then being I can't figure out what changed in 3.0.5 that makes version after it work and those before it not work. @darkhax since you're the author, any clues?

**Comment by mattmess1221** [comment]
I believe the cause of this is the `install` plugin adds all the dependencies (which includes deobfed) to the pom.

Use this as a workaround. You'll also need to manually add any dependency it needs, if any.

```gradle
    compile fg.deobf(project.dependencies.create("dep") {
        transitive = false
    })
```

**Comment by Darkhax** [comment]
Sorry, thought I left a reply but I can't seem to find it. The thing I have noticed is that Forge itself is being added to the pom, so I am guessing you and all your deps need to be using the same Forge and MCP versions otherwise you run into this issue. 

https://maven.mcmoddev.com/net/darkhax/bookshelf/Bookshelf-1.13.2/3.0.6/Bookshelf-1.13.2-3.0.6.pom
https://maven.mcmoddev.com/net/darkhax/bookshelf/Bookshelf-1.13.2/3.0.4/Bookshelf-1.13.2-3.0.4.pom

**Comment by Darkhax** [comment]
This is still an issue in newer versions. Marking it as transitive will fix the exceptions but you won't have access to sources/javadocs, at least not in Eclipse.

**Comment by Darkhax** [comment]
I've updated the original post with a better title. I've also included some more information about the issue, along with some current workarounds that modders can use.

**Comment by LexManos** [comment]
There seems to be a way to filter it on the pom end. But is there a way to control what dependencies get added to the pom on FG's end.
I haven't been able to find any documentation on doing that.
If you want to look at it and submit a PR to filter out the mapped deps that's what we can do.
Transitive only fixes things that are in someone elses's POM file already.
