### ISSUE TITLE
Runs Minecraft client fine but compileJava not working

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/ForgeGradle#588]
So i was working on editing a project when this happened. I ran my project using the Minecraft Client, and everything worked like i had wanted it to, but when i ran "gradlew build", it failed on CompileJava. I'm a noobie at this currently, so this could be a obvious mistake. Here is the log:

https://pastebin.com/mEMTpvVY

I'm using MC 1.12.2, and forge v2808, and Intellij.
I tried invalidating caches, Rebuild project, but nothing seemed to work.
I set my dependencies.
The thing that confuses me is that the Minecraft Client works fine, so i'm not really sure why compileJava is not working.
I am a noobie, so sorry if this is very dumb and has a very obvious fix.
I would really appreciate any help.
Thanks in advance.

EDIT: I'm not sure why it says it cannot find symbol. The class is there.

**Comment by ghost** [comment]
I just checked, and now the MC client isn't working for some reason. It was working before.

**Comment by LexManos** [comment]
Your code cant be compiled, read your error and fix it. Not a Forge issue.
