### ISSUE TITLE
Access Transformers don't work for static inner classes

### ISSUE THREAD

**Issue by Akjosch** [MinecraftForge/ForgeGradle#59]
What it says in the topic: Access Transformers which refer to the static inner class itself are being ignored (not tested, but seem to work: ATs refering to their fields and methods). In particular, this means the following line from the default fml_at.cfg doesn't work:

```
public net.minecraft.entity.ai.EntityAITasks$EntityAITaskEntry
```

Most likely something about ProcessJarTask.applyExceptor() not being able to find those inner classes at the point it's being called and silently ignoring them. Sadly, there's no debug output for the process, so I can't provide more detailed info.

**Comment by BigBastard** [comment]
Can confirm
