### ISSUE TITLE
[FG2.3] OpenJ9 VM seems to be incompatible

### ISSUE THREAD

**Issue by PT400C** [MinecraftForge/ForgeGradle#595]
When trying to run `./gradlew setupDecompWorkspace` on a machine with OpenJDK Runtime Environment (build 1.8.0_212-b03) OpenJ9, the process crashes with the following message:

https://pastebin.com/UCYj6AUf

**Comment by Unnoen** [comment]
ForgeGradle 3 doesn't have a `setupDecompWorkspace` task, you should just import as a gradle project.

**Comment by PT400C** [comment]
@Unnoen Sorry, messed up the title.

**Comment by bs2609** [comment]
Can you run with `--info` or similar, to clarify which patch exactly is failing?

**Comment by bs2609** [comment]
In any case, this issue is likely caused by https://github.com/MinecraftForge/ForgeGradle/issues/597#issuecomment-500239293.

**Comment by LexManos** [comment]
yes, FG2.3 is not compatible with OpenJ9.
