### ISSUE TITLE
Curseforge maven could not be added as deobf dependencies

### ISSUE THREAD

**Issue by HyCraftHD** [MinecraftForge/ForgeGradle#596]
There is an issue in the fg.deobf function. When the maven repository is well formatted with pom files everything is working fine.
The problem is the curseforge maven does not provide pom files and has often unusal dependency configurations.
I tried adding [morpheus](https://minecraft.curseforge.com/projects/morpheus) from curseforge as a deobf dependency:

```groovy
repositories {
    maven { url = "https://minecraft.curseforge.com/api/maven" }
}

dependencies {
    minecraft "net.minecraftforge:forge:$config.forge.version"	
	compile fg.deobf(group: "morpheus", name: "Morpheus", version: "1.13.2", classifier: "4.0.115", ext: "jar")
}
```

The crashlog is: https://pastebin.com/rPgtSBzu

If i add it as a normal dependency everything is okay.

**Comment by tterrag1098** [comment]
Are you sure that maven dep is correct? Using the classifier for the version is highly unorthodox and maybe not even supported. The problematic code seems to be in gradle itself, we don't handle parsing the artifact:  https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/userdev/java/net/minecraftforge/gradle/userdev/util/DeobfuscatingRepo.java#L69

**Comment by LexManos** [comment]
This is a issue with the maven URL format. There is no way we can determine what is the extension, and what is the classifier. We have to support the most common cases of double extension `.jar.md5`
We do the magic using a regex: https://github.com/MinecraftForge/Artifactural/blob/master/src/gradlecomp/java/com/amadornes/artifactural/gradle/GradleRepositoryAdapter.java#L83

If you have solutions, feel free to PR Artifactural.

(Deleted tterrag's response as he mistakenly thought Artifact/ArtifactIdentifier was gradle)

**Comment by HyCraftHD** [comment]
Closing this as there is a [gradle plugin](https://github.com/Wyn-Price/CurseMaven) for this and it's hard to change the regex to support all cases
