### ISSUE TITLE
Every single cached source is being added

### ISSUE THREAD

**Issue by jaredlll08** [MinecraftForge/ForgeGradle#599]
![image](https://user-images.githubusercontent.com/5553605/59539671-722e8700-8efe-11e9-8bc9-1b471866c790.png)

All of those versions are ones that I have used at some point, but are being added  by ForgeGradle during project import, and will cause find usages to return multiple times for a single actual code usage, as shown below.

![image](https://user-images.githubusercontent.com/5553605/59540474-f54fdd00-8efe-11e9-869c-37e2f805f29d.png)

**Comment by LexManos** [comment]
https://youtrack.jetbrains.com/issue/IDEA-207941
