### ISSUE TITLE
genIntellijRuns enables "Allow parallel run" by default

### ISSUE THREAD

**Issue by thecodewarrior** [MinecraftForge/ForgeGradle#602]
as of [IntelliJ IDEA 2018.3](https://blog.jetbrains.com/idea/2018/09/whats-new-in-intellij-idea-2018-3-eap2/) run configurations default to only allowing one instance, however `genIntellijRuns` doesn't reflect this change in defaults and still generates run configurations with `singleton="false"` in the XML. After a little bit of digging it appears the only change needed would be on [this line.](https://github.com/MinecraftForge/ForgeGradle/blob/bd92a0d384b987be361ed3f7df28b1980f7fae1e/src/common/java/net/minecraftforge/gradle/common/util/RunConfig.java#L61)

**Comment by LexManos** [comment]
You can edit that value yourself: https://github.com/MinecraftForge/ForgeGradle/blob/bd92a0d384b987be361ed3f7df28b1980f7fae1e/src/common/java/net/minecraftforge/gradle/common/util/RunConfig.java#L193

**Comment by thecodewarrior** [comment]
I figured that out, though changing it doesn't actually seem to work. When and if the setting is fixed, I still think it would be worth changing the default to reflect the change in IntelliJ IDEA.
