### ISSUE TITLE
Support for Java 11 and Higher

### ISSUE THREAD

**Issue by Justsnoopy30** [MinecraftForge/ForgeGradle#603]
> Failed to apply plugin [id 'net.minecraftforge.gradle.patcher']
> Found java version 12.0.1. Minimum required is 1.8.0_101. Versions 11.0.0 and newer are not supported yet.

**Comment by Lomeli12** [comment]
Forge only supports the Java version that Minecraft targets. Minecraft targets Java 8, so Forge does so as well.

**Comment by LexManos** [comment]
No Lomeli, it's more then that, there are some technical reasons why J11+ is not supported. Namely ASM. It should be supported eventually. But it requires work that I haven't gotten around to.
But don't give this guy the time of day, him and another are from a project that steals FG's work and claims it as their own.
