### ISSUE TITLE
Failed to load custom natives?

### ISSUE THREAD

**Issue by ecumene** [MinecraftForge/ForgeGradle#604]
This has me scratching my head...

In my library I have this:
**Library.class**
```
public static void init() {
     System.loadLibrary("libgilrs")
```

I've put `libgilrs.so` in these folders:
```
~/projects/Minecraft_Mod/natives
~/projects/Minecraft_Mod/libs/jgilrs.natives.jar (with a META_INF)
~/projects/Minecraft_Mod/libs/jgilrs.natives.zip
~/projects/Minecraft_Mod/libs/jgilrs.zip
~/projects/Minecraft_Mod/libs/jgilrs.jar
~/.gradle/caches/minecraft/net/minecraft/natives/1.12.2
```

I even printed `java.library.path`
```
[xyz.ecumene.jgilrs.Library:init:5]: /home/mitchell/projects/couchcraft2/natives/:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib:/home/mitchell/.gradle/caches/minecraft/net/minecraft/natives/1.12.2
```

And yet, I still get this error!
```
no libgilrs in java.library.path
```

This works fine in my JUnit test for the library, with setting the JUnit natives folder, but it doesn't in the minecraft mod. So, my thoughts are maybe Forge Gradle does something different with natives I'm not aware of? Anyway I'm submitting this for any feedback as to why this isn't working

Thanks!

**Comment by ecumene** [comment]
Just as an update, I've hardcoded the directory with `System.load(".. .so")` and it works temporarily.

But ofc this won't work with production...

**Comment by LexManos** [comment]
This is nothing to do with FG. You just need to specify the natives directory like any other java project.
