### ISSUE TITLE
[FG3] Is there any way to use FG3 with Minecraft 1.12.2?

### ISSUE THREAD

**Issue by KlemenDEV** [MinecraftForge/ForgeGradle#607]
I was wondering if there is any way to use Forge Gradle 3 with Minecraft 1.12.2 as 2.3 seems to be a bit outdated? I did not find any example configurations that would work so I am now asking here.

Thank you for your help!

**Comment by LexManos** [comment]
No

**Comment by KlemenDEV** [comment]
Thank you for the feedback!
