### ISSUE TITLE
Gradle 5.5 dependency artifacts resolution feature

### ISSUE THREAD

**Issue by Bluexin** [MinecraftForge/ForgeGradle#609]
Gradle 5.5 was released, with a feature which looks like it could be very interesting to use instead of the hacks currently being used to deobfuscate mc, see [here](https://docs.gradle.org/5.5/release-notes.html#transforming-dependency-artifacts-on-resolution).
The nice part about it would be the use of an official API, which means more forward compatibility guarantees.
(just to make it clear, I'm not demanding a change now, just probing for opinions)

**Comment by LexManos** [comment]
We know about this, it dropped sometime after we built our system.
Feel free to start working on a PR. But I'm not going to. Our system works for now and I am so tired of digging in gradle's shitty ecosystem that I am not going to touch this with a 100ft pole.

On top of that, last I looked 5.5 still had the issue where it'll randomly 'clean' your cache for.you. Just making random libraries and resources dissapear even if actively used by projects/ides that are open.

**Comment by AbrarSyed** [comment]
I saw the new Gradle 5.5 feature, and am considering starting development on FG4 or something that will be built the whole new gradle modules and dependency attributes systems. My only conceptual issue is that it would be difficult to apply arbitrary access transformers (assuming those are still a thing). Also, this would work probably work well for userDev but idk how it would for forge development...

Then again, ive been out of the game for some time, and don't have a clear idea of how stuff works in the current FG3.

**Comment by josephworks** [comment]
BTW, Gradle 5.6 was released.

**Comment by mezz** [comment]
Please see this comment and the one below it for some prior discussion on this topic: https://github.com/MinecraftForge/ForgeGradle/pull/577#issuecomment-485280600

Based on that, I believe we still need to wait for this to be fixed: https://github.com/gradle/gradle/issues/9050

**Comment by mezz** [comment]
cc @Cypher121 on this topic

**Comment by Cypher121** [comment]
Yes, unless something major changed, this gradle bug makes it impossible to select artifacts to transform on anything except their artifact type, so it's either deobfuscate every jar dependency or none of them.

**Comment by SizableShrimp** [comment]
Closing for now until gradle gets their act together. See discussion on #865 for more info.
