### ISSUE TITLE
1.12.2 mcp looking for lwjgl-platform:2.9.2-nightly-20140822

### ISSUE THREAD

**Issue by LeafHacker** [MinecraftForge/ForgeGradle#627]
Using FG `3.0.118`, a [custom userdev](https://github.com/ImpactDevelopment/UserDev/releases/tag/1.12.2-1) and McpConfig `20190912.212240`

I get the following error:

```
A problem occurred configuring root project 'Impact'.
> Failed to notify project evaluation listener.
   > Could not resolve all files for configuration ':_compileJava_1'.
      > Could not find org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
          - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
          - https://jcenter.bintray.com/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
          - https://jcenter.bintray.com/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
          - https://impactdevelopment.github.io/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
          - https://impactdevelopment.github.io/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
          - http://repo.spongepowered.org/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
          - http://repo.spongepowered.org/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
          - https://jitpack.io/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
          - https://jitpack.io/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
          - https://files.minecraftforge.net/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
          - https://files.minecraftforge.net/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
          - https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
          - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
          - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
        Required by:
            project : > net.minecraft:client:1.12.2
   > Could not create task 'createMcpToSrg' (GenerateSRG)
   > Could not create task 'createMcpToObf' (GenerateSRG)
```

Where `net.minecraft:client:1.12.2` requires `org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822` but it can't be found.

The same setup is working fine for 1.13.2 and 1.14.4.

Not sure if this is a MCP, McpConfig or FG3 issue, so reporting here.

**Comment by LexManos** [comment]
You don't need a special userdev for working with Vanilla's codebase. You can just reference the vanilla jars as a library with FG and it'll just work. Launching the game doesn't require any special hacks like it does in Forge as you don't have the modlauncher system to worry about.

As for your issue, yes, if a library is not found in any of the maven repos you specify, then it will indeed break with this error.
This is not a bug, specify the libraries you need correctly.

**Comment by LeafHacker** [comment]
> This is not a bug, specify the libraries you need correctly.

I didn't specify `lwjgl-platform` at all. My interpretation of the error was that either mcpconfig or `net.minecraft:client` was requiring that, hence the bug report.

**Comment by LexManos** [comment]
But you did, or more specifically, Mojang did as it's a dependency of Vanilla.
Welcome to having to actually know what you're doing to work with systems like this.
None of this is a bug, it's just downloading the libraries it's been told to download.

I plan on trying to get Forge 1.12.x onto FG3 just to make my life easier for that branch. But it'll take work and no promises on a timeframe.

**Comment by LeafHacker** [comment]
> or more specifically, Mojang did as it's a dependency of Vanilla.

That's a more helpful response, thank you.

Looking at the 1.12.2 vanilla json it requires [`2.9.4-nightly-20150209`](https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209.jar) which exists, so I'm still unsure where [`2.9.2-nightly-20140822`](https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar) has come from, since it isn't in the vanilla json.

EDIT: vanilla actually specifies _both_, but only one resolves to an actual file.

**Comment by LeafHacker** [comment]
Hackfixed it by doing 

```gradle
configurations.all {
    resolutionStrategy {
        force 'org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209'
    }
}```

Thanks for the pointers.

**Comment by LexManos** [comment]
Protip guys: Don't do this. Hacking new things to do old versions is how you break things.
