### ISSUE TITLE
Reobf not properly working on secondary jars/sourcesets

### ISSUE THREAD

**Issue by pupnewfster** [MinecraftForge/ForgeGradle#629]
I am not positive I am doing this correctly so there is the chance I am just missing a line, but I am running into an odd bug when it comes to reobfuscating my secondary jars for the non main sourceset. I have created a minimal testset that can reproduce this reobfuscation issue here: https://github.com/pupnewfster/TestBrokenFG and I will be linking to various parts in it for showing what I mean rather than to the project I encountered this in as I believe this is easier to see what is going on.

From my understanding for FG3 we need to include a `reobf` block for secondary jars in the build.gradle, which I do here: https://github.com/pupnewfster/TestBrokenFG/blob/master/build.gradle#L181-L186

This works properly EXCEPT for if I have an intermediary class in another sourceset (my main one), that extends a class that needs to be reobfuscated. In my case I ran into this with TileEntities.

In my main sourceset I put this intermediary TileEntity class: https://github.com/pupnewfster/TestBrokenFG/blob/master/src/main/java/com/pupnewfster/testfg/IntermediaryTileEntity.java
And in my secondary sourceset I make a TileEntity that extends this intermediary class: https://github.com/pupnewfster/TestBrokenFG/blob/master/src/secondary/java/com/pupnewfster/secondary/FinalTile.java

As you can see in the comments in the second tile class, by default FG does not recognize what it is supposed to be reobfuscating the method into, but if I force cast `this` to `TileEntity` it is able to resolve it and have it be obfuscated in the output jar.

I believe this is due to a bug in FG, but if I am missing some line that tells it to force check the other sourceset for reobfuscation in the hierarchy then please let me know what it is that needs to be added.

---

Note: I only bothered setting up enough code in the two sourcesets that it can be seen that reobfuscation does not work, but I am not using the tiles nor do I register any blocks so no crash will be experienced.

I initially ran into it in Mekanism with this crash report: https://pastebin.com/DA9a8u33 which points to this line: https://github.com/pupnewfster/Mekanism/blob/1.14.x/src/generators/java/mekanism/generators/common/tile/TileEntityHeatGenerator.java#L179 (Note: Looking at the source of the classes showed me that `getWorld()` did not get reobfuscated where `getBlockstate` and `getBlock` both did two lines down.)

**Comment by MairwunNx** [comment]
If you have problem on this line:

```groovy
reobf {
    secondaryJar {
        dependsOn createMcpToSrg
        mappings = createMcpToSrg.outputs.files.singleFile
    }
}
```

Then i approve it bug. I also have this problem, i stumbled upon your problem with google.

**Comment by JDLogic** [comment]
Not a bug. In this case, you also have to set the classpath for the reobf task to use the compile classpath for the secondary sourceset. By default it is set to the compile classpath for the main sourceset.

```gradle
reobfSecondaryJar {
    classpath = sourceSets.secondary.compileClasspath
}
```

Note: The name of this task is 'reobf' + the name of the jar task, with the first letter of the name capitalized (if it wasn't already).

**Comment by pupnewfster** [comment]
Thank you changing the classpath for the secondary reobf tasks does make it able to reobfuscate it properly.
