### ISSUE TITLE
Installing Eclipse for modding, Minecraft folder missing.

### ISSUE THREAD

**Issue by Mremenar** [MinecraftForge/ForgeGradle#638]
Greetings,
Thank you in advance for reviewing this and my apologies for any noob-ness on my part, I have only recently begun learning Java.
I'm trying to install Eclipse to build mods for Minecraft.  I'm following the instructions at both:
https://blog.usejournal.com/a-beginners-guide-to-modding-minecraft-9a42536495f6
and
https://www.youtube.com/watch?v=0ULz-oCUbEg
In the video I make it 12:01, but have no Minecraft folder to access.  I make it to Step 4 of the first link, but .\gradlew setupDecompWorkspace appears to error out (attached).  I did have two JDKs, and removed the extra one per (http://insidejvmjava.blogspot.com/2015/09/ant-compile-issue-warning-options.html) but that made no difference, even after a full reboot.
My environment variables path (Win10) is currently set to C:\Program Files\Java\jdk1.8.0_111 and my JAVA_HOME is set to C:\Program Files\Java\jdk1.8.0_111.
(I did try my path at C:\Program Files\Java\jdk1.8.0_111\bin but it made no difference).
At first I had 200 errors in Eclipse, until I wiped it clean and made a new install on a drive other than the C: drive (H:).
Now no red X/errors in Eclipse, but I have no decompiled Minecraft folder, I presume (hopefully not errantly) that it has to do with the ".\gradlew setupDecompWorkspace" skipping steps even tho' it says "BUILD SUCCESSFUL" after running.
Again, thank you for your help.
Marc

PS: Hopefully you can see the screen caps that I've included.

[java error.txt](https://github.com/MinecraftForge/ForgeGradle/files/3893958/java.error.txt)

![1 Eclipse main workspace](https://user-imag
![2 Eclipse workspace sub](https://user-images.githubusercontent.com/48491179/69672507-1e979c00-104d-11ea-8d71-668a8cb7c18c.png)
es.githubusercontent.com/48491179/69672501-1ccdd880-104d-11ea-9d1a-40c303f4e0e0.png)
![3 missing](https://user-images.githubusercontent.com/48491179/69672511-222b2300-104d-11ea-9678-91911ac4f9b1.png)

**Comment by Mremenar** [comment]
![2 Eclipse workspace sub](https://user-images.githubusercontent.com/48491179/69672925-f9575d80-104d-11ea-9794-664621c9cc28.png)

**Comment by Mremenar** [comment]
![2 Eclipse workspace sub](https://user-images.githubusercontent.com/48491179/69672942-07a57980-104e-11ea-9170-beac8fb2b1ca.png)

**Comment by DaemonUmbra** [comment]
~~It looks like you missed the step of importing/opening your project.
For further issues please go to the [Forum](https://www.minecraftforge.net/forum/ "MinecraftForge Forum") first.~~
Nevermind, I didn't realize you were targeting 1.7.10.

**Comment by FinnT730** [comment]
And, don't make a mod for 1.7, update to 1.14 or above, or people give help.

**Comment by Mremenar** [comment]
There are a lot of people who play 1.7.10 because of some seriously cool mods that are not available on other versions.  Please re-open this issue and provide help.  Thank you.
