### ISSUE TITLE
i can't build on idea on 1.7.10

### ISSUE THREAD

**Issue by Mairuis** [MinecraftForge/ForgeGradle#643]
I m using forgegradle 1.2 on Minecraft 1.7.10.
but when I click sync, it doesn't work.
Minecraft doesn't have a high version of the server core, this's the only way to write mod for my server.
I m going crazy, what can I do?
please save my life.

![S03F485UL~VCS14IEYW$U{8](https://user-images.githubusercontent.com/29746822/70859249-9588cc00-1f4b-11ea-8054-c505508a297c.png)

build.gradle
```gradle
buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "http://files.minecraftforge.net/maven"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:1.2-SNAPSHOT'
    }
}

apply plugin: 'forge'

version = "1.0"
group= "com.yourname.modid" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "modid"

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "eclipse"
}

dependencies {
    // you may put jars on which you depend on in ./libs
    // or you may define them like so..
    //compile "some.group:artifact:version:classifier"
    //compile "some.group:artifact:version"
      
    // real examples
    //compile 'com.mod-buildcraft:buildcraft:6.0.8:dev'  // adds buildcraft to the dev env
    //compile 'com.googlecode.efficient-java-matrix-library:ejml:0.24' // adds ejml to the dev env

    // for more info...
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html

}

processResources
{
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
                
        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

`

**Comment by Unnoen** [comment]
We do not provide support for outdated versions. Please update.

**Comment by MauveCloud** [comment]
This seems to happen with newer builds of Gradle - I got the same error message with a project I'm involved with, but when I copied the gradle wrapper from an open source mod that had a branch for the 1.7.10 version of the mod, it got past that.  I notice the ForgeGradle project here has a wrapper in the "FG_1.2" branch that is probably safe to use with it, but you might want to avoid performing an "Update Gradle wrapper" command on your project, which I see in the screenshot.

**Comment by FinnT730** [comment]
Yeah, newer versions of FG are not supporting 1.7.10, there are many reasons why to leave that version behind.

Like Unnoen said, we do not provide support for it, even when FG breaks, even with newer versions.

**Comment by jriwanek** [comment]
For people who actually need a resolution, the correct answer is "Don't use gradle versions past 2.14.1 with FG1.2".

**Comment by LexManos** [comment]
Yes, FG is designed for a very specific version of gradle. If you use any version other then the one or mdk uses, it's at your own risk and can screw things up.
