### ISSUE TITLE
Conditionally adding ForgeGradle to Subprojects does not work correctly

### ISSUE THREAD

**Issue by sirati** [MinecraftForge/ForgeGradle#647]
I am using subprojects and I only want to use ForgeGradle is some. Thus i conditionally add it to subprojects that have the property isDepForge = true. In this case however Gradle is then unable to correctly resolve the minecraft dependency.
Here is the gist of what I am doing:
```Groovy
allprojects {
	ext {
		isDepForge = false
		delayedSetup = {}
	}
}
//important to now evaluate children as they might change properties we depend on and we do not want to read the default values!
evaluationDependsOnChildren()

allprojects {
	if (project.isDepForge) {
		apply plugin: 'net.minecraftforge.gradle'
	}
	project.delayedSetup()
	if (project.isDepForge) {
	//omitted some other forge setup 

	dependencies {
		minecraft 'net.minecraftforge:forge:1.14.4-28.1.90'
	}

	minecraft {
		mappings channel: 'snapshot', version: '20190719-1.14.3'
	}
}
```
The subproject then has defined `isDepForge = true`

Results in the following error: `Could not resolve: net.minecraftforge:forge:1.14.4-28.1.90`

If I instead add it unconditionally it works, but then I add the plugin to subprojects where I do not want it.
```Groovy
allprojects {
	apply plugin: 'net.minecraftforge.gradle'
	project.delayedSetup()
	//omitted some other forge setup 

	dependencies {
		minecraft 'net.minecraftforge:forge:1.14.4-28.1.90'
	}

	minecraft {
		mappings channel: 'snapshot', version: '20190719-1.14.3'
	}
}
```

My full configuration can be seen here:
project root:
https://pastebin.com/UUZA7F6y
forge mod example:
https://pastebin.com/LqdkdMj2

**Comment by LexManos** [comment]
we have to apply things before the project is evaluated, so this setup will now work. if you're setting that flag, you can just add fg directly.

**Comment by sirati** [comment]
> 
> 
> we have to apply things before the project is evaluated, so this setup will now work. if you're setting that flag, you can just add fg directly.

are you saying that the plugin has to be added before `evaluationDependsOnChildren()` ?

Well to bad...
