### ISSUE TITLE
Disable test of certificates

### ISSUE THREAD

**Issue by Animaleante** [MinecraftForge/ForgeGradle#663]
I'm trying to build a mod using this plugin, but I need it to not try to validate the certificates. I'm getting a message that says:
"To disable this check re-run with -Dnet.minecraftforge.gradle.test_certs=false"

And I have tried adding this VM option to my runClient configuration, but with no results. I'm using the IntelliJ IDE. Can anyone help me? Should I add that option somewhere else?

**Comment by LexManos** [comment]
It just checks for the system property, add it wherever in your run you set system properties.
But beyond that you SHOULD just use a non-broken JDK that includes the needed certs, as that's the point of the check.
