### ISSUE TITLE
Trouble using FG3 with 1.12.2

### ISSUE THREAD

**Issue by r4v3n6101** [MinecraftForge/ForgeGradle#664]
It seems that [userdev3](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-userdev3.jar) doesn't exist(but [userdev](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-userdev.jar) exists). Why do we need that line? 
https://github.com/MinecraftForge/ForgeGradle/blob/ccf3035ba1f435f0f1a685a70d85df5481ee8b73/src/userdev/java/net/minecraftforge/gradle/userdev/MinecraftUserRepo.java#L341

**Comment by LexManos** [comment]
Because the old userdev isn't in the FG3 format.
There is currently no published way to use <1.13 on FG3.
You're more then welcome to come into discord and help work on the process.
But there are quite a few things until I feel it'd be worth it to backport support.
