### ISSUE TITLE
Gradle does not pass console commands to server

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/ForgeGradle#666]
When I start a server using `./gradlew runServer` the server starts but writing `stop` into the console does not work and is not passed to the server. Using `--no-daemon` does not help. If the server is started from IntelliJ or eclipse it does work and the commands are passed to the server.

gigaherz found this:
![image](https://cdn.discordapp.com/attachments/437001959950778368/695613364562296942/unknown.png)

Unfortunetly the runServer task is ~~not a normal task~~ generated to late, so even using
```
project.afterEvaluate {
    tasks.runServer.standardInput = System.in
}
```
doesnt work.

**Comment by malte0811** [comment]
No idea if this is still relevant for you after 2 years, but I've found a working alternative to the `afterEvaluate` snippet you posted:
```gradle
tasks.withType(Task) {
    if (it.name == "runServer") {
        it.standardInput = System.in
    }
}
```

**Comment by samvv** [comment]
Any reason this is not added yet? This would be a real improvement in UX. Currently, IntelliJ IDEA also doesn't support entering commands, at least not on my machine ...

**Comment by LexManos** [comment]
Because you can fix it yourself, and gradle like to change things. You can also just use the server GUI in your IDE.
