### ISSUE TITLE
I thought this problem was fixed but i got it just now

### ISSUE THREAD

**Issue by MadRatSRP** [MinecraftForge/ForgeGradle#668]
https://github.com/MinecraftForge/ForgeGradle/issues/469

Using 2.0.2 ForgeGradle version 

Console shows this:
A problem occurred evaluating root project 'MinecraftBitcoin'.
> Failed to apply plugin [id 'net.minecraftforge.gradle.forge']
   > MISSING REPLACEMENT DATA FOR RUN_DIR

**Comment by DaemonUmbra** [comment]
ForgeGradle 2 is no longer supported.

**Comment by alexdrean** [comment]
Just got this issue right now too. Built ReplayMod freshly yesterday and it all worked. Doesn't work today, even on the same commit. Seems like it's related to some server being down or not working properly imo.

**Comment by LexManos** [comment]
Nothing on our end has changed, and as Daemon has stated, we have moved away from old versions. And as such you'll get no support.
