### ISSUE TITLE
Intellij Run Configurations aren't being generated properly.

### ISSUE THREAD

**Issue by FireMasterK** [MinecraftForge/ForgeGradle#675]
Hi there,
When I run the command `gradlew genIntellijRuns`, I get the following error:
https://paste.ubuntu.com/p/NTvctc7TXC/

The repo I'm running the command on is https://github.com/kami-blue/client
I was lead here by them: https://github.com/kami-blue/client/issues/802

Any help would be appreciated.

**Comment by FinnT730** [comment]
1.12 is not supported anymore. Update to 1.14.4 or 1.15.2 to receive support.
Also, use the forge MDK from files.minecraftforge.net   since this looks like a hacked client maker...

**Comment by FireMasterK** [comment]
Figured this out, ForgeGradle looks for a RunManager tag in workspace.xml but there isn't one by default. To fix this I had to create a run configuration which fixed the issue.

**Comment by FinnT730** [comment]
Don't make hacked clients...... It is against Mojang's EULA, which you agreed too when you bought the game.
