### ISSUE TITLE
Newest MDK getting stuck  during genEclipseRuns

### ISSUE THREAD

**Issue by lamoyrl90** [MinecraftForge/ForgeGradle#678]
Console log: https://pastebin.com/xLJU61ks

gradle.properties: 

"# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false"

Getting stuck at 88% during the genEclipseRuns command. Increasing the memory from 3G to 8G didn't change anything.

Forge version 31.2.0

**Comment by DaemonUmbra** [comment]
When you say it gets stuck does the timer stop or just the progress bar?

**Comment by lamoyrl90** [comment]
both

**Comment by DaemonUmbra** [comment]
Have you tried pressing a key to poke at it? (I know it sounds silly but I've had console programs stick and wake up on a keypress)

**Comment by lamoyrl90** [comment]
Oh wow. That is a strange bug. The console started reprinting text about a dozen lines back.

Says the build was successful though. Thanks!

**Comment by Pokechu22** [comment]
If you're having weird issues with the console, you can add `--console=plain` to the command-line arguments (you should also be able to add `org.gradle.console=plain` in the gradle.properties file for the same effect).

**Comment by Aeronica** [comment]
Just a note about org.gradle.daemon=false. If your <user home>/.gradle/gradle properties has the org.gradle.daemon=true it will override the local setting in your mod folder. This can cause build issues too.
