### ISSUE TITLE
SpecialSource does not allow java 1.11+ builds

### ISSUE THREAD

**Issue by chris-comes** [MinecraftForge/ForgeGradle#679]
The `sourceCompatibility`, `tartgetCompatibility`, and similar variables by default set the default java version to 8 which is fine. Building also works when setting that value to java 1.9 and 1.10. However, when trying to set that value (or just remove it entirely with Java11 installed) to Java 1.11+ `./gradlew build` fails with the following exception:

![image](https://user-images.githubusercontent.com/39343693/82744381-02a85500-9d67-11ea-86be-153ba0aa660f.png)

The version of SpecialSource used currently is `1.8.3` which includes an outdated version of ASM from 2018 whereas the [latest release](https://github.com/md-5/SpecialSource/commits/master) of SpecialSource `(1.8.6)` updates ASM to support java builds up to 1.14.

However, I do realize that updating dependencies can sometimes be problematic and I'm relatively new to the Forge scene so I could possibly be missing something obvious that would cause problems, but am willing to assist if possible.

_P.S: I know that minecraft/forge support 1.8 because that is what is widely used, but I think it would be better to support higher java versions for whatever reason, especially since forge itself has preliminary support for java13 from the latest [release](https://www.minecraftforge.net/forum/topic/85620-forge-312-minecraft-1152/)._

**Comment by LexManos** [comment]
It could be a fix on their end, but honestly you're the one at fault here.
Minnecraft targets J8, mods should as well.
But yes it would need to update SpecialSource. Which actually you CAN do yourself in your build script.

**Comment by johnsusek** [comment]
@LexManos Any chance you could share how to force SpecialSource 1.8.6 in my build script? I am seeing this error as well when trying to reobfuscate a shaded jar. 

I tried adding this:

```
classpath group: 'net.md-5', name: 'SpecialSource', version: '1.8.6', changing: true
```

to my buildscript dependencies, that didn't seem to fix it. 

I've also tried this:

```
compile 'net.md-5:SpecialSource:1.8.6'
```

in my main dependencies.


Here is my complete config: https://gist.github.com/johnsusek/87c4965d03b2a2cdc2310a0e05efe628

The command `./gradlew build` outputs this:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 55
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:148)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:136)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:237)
        at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:221)
        at net.md_5.specialsource.JarRemapper.remapJar(JarRemapper.java:187)
        at net.md_5.specialsource.SpecialSource.main(SpecialSource.java:273)
```

It seems this is fixed in newer versions of shadow, but those require gradle 6.

**Comment by FinnT730** [comment]
**Unsupported class file major version 55**
Java 11 is class version 55, and that is not supported

**Comment by johnsusek** [comment]
I understand! Just thought Lex could elaborate slightly on what he said:

"Which actually you CAN do yourself in your build script."

If he wanted :) 

Thanks!

**Comment by johnsusek** [comment]
Also note I have this in my config, but it's still using Java 11

`sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.`

**Comment by johnsusek** [comment]
Also:

```
$ java -version
openjdk version "1.8.0_252"
```

**Comment by chris-comes** [comment]
@johnsusek The line you need to edit to get 1.11 builds is this to 1.8.6, leave everything else the same

https://github.com/MinecraftForge/ForgeGradle/blob/4db37f83522e8944a6e88fb4f57709462bb1c3fb/src/common/java/net/minecraftforge/gradle/common/util/Utils.java#L102

Compile and update the buildscript at the top of your plugin's `build.gradle`.

**Comment by LexManos** [comment]
No its not, You don't have to hack around anything to create custom builds of anything.
It's Gradle. It's a Task. You can configure tasks.
https://github.com/MinecraftForge/ForgeGradle/search?q=SPECIALSOURCE&unscoped_q=SPECIALSOURCE

And again, you should not be using J11 bytecode for Minecraft Mods. Mojang ships J8, Use J8.

**Comment by johnsusek** [comment]
Yeah sorry, I just don't know why I would be getting this error even though I'm running openjdk version "1.8.0_252".
