### ISSUE TITLE
Eclipse Run tool Issue

### ISSUE THREAD

**Issue by moha-rh** [MinecraftForge/ForgeGradle#681]
Hi, i am new in modding, and when I try to run the example mod in eclipse I have this error message:
'launching runClient' has encoutered a problem.
Launch configuration runClient references non-existing project VE Project.
Would I have the same problem when I will start running my own mod or this is just happening because it's the example mod ? 
thanks for your help.

**Comment by DaemonUmbra** [comment]
To me it sounds like you used to have something called VE Project that made run configs but VE Project no longer exists, delete your existing runconfigs and run the ``genEclipseRuns`` task.
