### ISSUE TITLE
Access Transforming RedstoneParticle ctor doesn't work

### ISSUE THREAD

**Issue by shartte** [MinecraftForge/ForgeGradle#683]
I have no idea whether issues with AT should be reported here or elsewhere, but this problem might be a part of ForgeGradle's overall process, I simply don't know.

I have the following accesstransformers.cfg:
```
# GUI rendering
#public net.minecraft.client.gui.inventory.GuiContainer func_146977_a(Lnet/minecraft/inventory/Slot;)V # drawSlot
#public net.minecraft.client.gui.GuiTextField func_146188_c(IIII)V # drawSelectionBox

# Reusing RedstoneParticle for ChargedOreFX
protected net.minecraft.client.particle.RedstoneParticle <init>(Lnet/minecraft/world/World;DDDDDDLnet/minecraft/particles/RedstoneParticleData;Lnet/minecraft/client/particle/IAnimatedSprite;Lnet/minecraft/client/particle/RedstoneParticle$1;)V
```

When reloading the gradle project in IntelliJ, I can see in the log that it is rerunning the project setup (access transformers, decompilation, etc.).
It creates the following file: build\_atJar_5\accesstransform.log
which contains the following:

```
[23:58:00] [main/DEBUG]: Transforming class Lnet/minecraft/client/particle/RedstoneParticle;
[23:58:00] [main/DEBUG]: Transforming net.minecraft.client.particle.RedstoneParticle METHOD <init>(Lnet/minecraft/world/World;DDDDDDLnet/minecraft/particles/RedstoneParticleData;Lnet/minecraft/client/particle/IAnimatedSprite;Lnet/minecraft/client/particle/RedstoneParticle$1;)V to access PROTECTED and LEAVE
```

Yet when trying to compile, and in the attached sources as well, the constructor in question is still private.

I have tried deleting the build folder -> no dice.

Any idea what might cause this?

**Comment by shartte** [comment]
I downloaded the latest Forge MDK and used it to make a minimal repro for this issue:
[forge-1.15.2-31.2.0-mdk.zip](https://github.com/MinecraftForge/ForgeGradle/files/4708576/forge-1.15.2-31.2.0-mdk.zip)

**Comment by LexManos** [comment]
You tried to make a constructor.. that takes an anonymous class.. protected so you can use it...
That's not how any of this works.

**Comment by shartte** [comment]
@LexManos Check again please. The constructor does not take an anonymous class.

I fail to see how this conflicts with the raison d'être for access transformers, and why this should be allowed to fail silently.

**Comment by FinnT730** [comment]
It is in an anonymous class
Notice the '$1' ? That is an indicator for an anonymous class

**Comment by Pokechu22** [comment]
> `Lnet/minecraft/client/particle/RedstoneParticle$1;`

That looks like an anonymous class to me.  Though the actual constructor doesn't seem to have that on my end, nor does that show up in the AT suggested by MCPBot:

```
22:20:28     pokechu22 | gm RedstoneParticle
22:20:32 MCPBot_Reborn | === MC 1.15.1: net/minecraft/client/particle/RedstoneParticle.RedstoneParticle (dog.dog) LOCKED ===
22:20:32 MCPBot_Reborn | Name       : dog => func_i51039_ => RedstoneParticle
22:20:32 MCPBot_Reborn | Descriptor : (Lbjt;DDDDDDLgr;Ldpj;)V => (Lnet/minecraft/world/World;DDDDDDLnet/minecraft/particles/RedstoneParticleData;Lnet/minecraft/client/particle/IAnimatedSprite;)V
22:20:32 MCPBot_Reborn | AT         : public net.minecraft.client.particle.RedstoneParticle <init>(Lnet/minecraft/world/World;DDDDDDLnet/minecraft/particles/RedstoneParticleData;Lnet/minecraft/client/particle/IAnimatedSprite;)V # RedstoneParticle
22:20:32 MCPBot_Reborn | Comment    : None
22:20:32 MCPBot_Reborn | SRG Params : World p_i51039_1_, D p_i51039_2_, D p_i51039_4_, D p_i51039_6_, D p_i51039_8_, D p_i51039_10_, D p_i51039_12_, RedstoneParticleData p_i51039_14_, IAnimatedSprite p_i51039_15_
22:20:32 MCPBot_Reborn | MCP Params : World p_i51039_1_, double p_i51039_2_, double p_i51039_4_, double p_i51039_6_, double p_i51039_8_, double p_i51039_10_, double p_i51039_12_, RedstoneParticleData p_i51039_14_, IAnimatedSprite p_i51039_15_
22:20:32 MCPBot_Reborn | Last Change: 2020-01-20 00:42:44.040620-05:00 (_bot_update_)
```

**Comment by shartte** [comment]
I stand corrected and got fooled by the bytecode viewer :|

**Comment by LexManos** [comment]
![](https://i.imgur.com/yw0XXJ2.png)
Looks like an anonymous class to me.
Beyond this, You shouldn't be extending the redstone particle. It's literally just a few line helpers.
Just make your own particle and not rely on asm hacks you have no idea how to use.
