### ISSUE TITLE
New Method of Source Replacement

### ISSUE THREAD

**Issue by elveskevtar** [MinecraftForge/ForgeGradle#691]
I just upgraded my project to ForgeGradle3 and I am wondering if there is any way to do token string replacement in the source files anymore? I relied upon the replace function in the old Minecraft block: https://forgegradle.readthedocs.io/en/latest/reference/mcblock/ but these docs seem outdated.

My use case:
For the @Mod annotation e.g.
@Mod(modid="modid", name="modname", version="@VERSION@")

and then only having to specify/change the version once in my build.properties or my build.gradle.

**Comment by DaemonUmbra** [comment]
Are you using 1.12.2?

**Comment by elveskevtar** [comment]
@DaemonUmbra yes! Just for now but I plan on making the mod compatible with all versions of Forge > 1.12 in the future

**Comment by elveskevtar** [comment]
I tried scouring the source of UserDevExtension and RunConfig and noticed the tokens mapping in RunConfig but I'm not sure that's relevant.

**Comment by DaemonUmbra** [comment]
I'm pretty sure there are ways of doing this using standard Gradle, and 1.12 isn't actively supported anymore.
