### ISSUE TITLE
Does genVSCodeRuns work with 1.12.2

### ISSUE THREAD

**Issue by affanshahid** [MinecraftForge/ForgeGradle#693]
Just wondering if the vscode gen works out of the box for 1.12.2? When I run using the generated files it just doesn't load my mod but otherwise runs fine. I understand 1.12.2 is old and not supported but just wanted to know if it is expected to work.

**Comment by MajsterTynek** [comment]
Short answer: It does not and they don't bother to fix it.
In the newer versions, it works as intended...

You can bypass it by making a symlink in mods within run folder.
However, one thing to note; such solution breaks mixins!
