### ISSUE TITLE
Can't gradle sync when mc version isn't installed locally.

### ISSUE THREAD

**Issue by canitzp** [MinecraftForge/ForgeGradle#708]
I ran over this issue today, when "syncing" the gradle project without the minecraft version installed locally (inside the .minecraft folder) an exception is thrown and the sync is killed.
This comes from the commit 0514fde0e883a06d2e4478f448c6592603060244 .
The problem is here: https://github.com/MinecraftForge/ForgeGradle/commit/0514fde0e883a06d2e4478f448c6592603060244#diff-d945fd726ec97b5ff897937b22623c5dR59-R67
It tries to create the sha1 of the "localPath" Minecraft file, which doesn't exist, except when it is installed locally. For my dev environment this wasn't a problem, because I just installed the minecraft version locally, but the github ci task failed because of this: https://github.com/canitzp/FeederHelmet/runs/983722553

It should be an easy fix however, because you only need to check if the "localPath" exists, before calculating the sha1

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/ForgeGradle/commit/b17c95c9fe35220ce0c86f6462d4d765e6bd6acb
