### ISSUE TITLE
updateMappings task also remaps srg in strings

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/ForgeGradle#714]
When using `gradlew -PUPDATE_MAPPINGS=1.16.2 -PUPDATE_MAPPINGS_CHANNEL=official updateMappings` to move to official mappings, all string references of srg names are also remapped to their official name.
This is a problem, as ObfuscationReflectionHelper still requires srg names. and remapping that to official will cause issues (not in dev, but when running in production)
Example:
Running the command above will change `ObfuscationReflectionHelper.findMethod(LivingEntity.class, "func_70672_c", DamageSource.class, float.class)` to `ObfuscationReflectionHelper.findMethod(LivingEntity.class, "getDamageAfterMagicAbsorb", DamageSource.class, float.class)`

**Comment by LexManos** [comment]
Yes this is why forge uses strings like "func_" + "12345_a". The APPLY side of mappings is just a string replace. Not much we can do about that.

**Comment by Aizistral** [comment]
Okay, this doesn't relate to this the issue, but tell me someone WHERE can I find any documentation on how to use that `gradlew updateMappings` magic. I literally didn't know something as important as this does exist until I beheld this issue, and googling on the matter yields next to no results. Just... why? Why isn't it even mentioned anywhere that this command exists in ForgeGradle?

**Comment by LexManos** [comment]
Because it can cause a crapload of issues if you don't know what you're doing. Its a major automated process, that you should be careful when using.

Also, as with all other tasks in FG. You can see it's existence in our source. Documentation is crowdsourced.

**Comment by Aizistral** [comment]
Understandable, have a good day

**Comment by alcatrazEscapee** [comment]
@Extegral JDLogic has written a small little blurb on the use of the command: <https://gist.github.com/JDLogic/bf16deed3bcf99bd9e1a22eb21148389>

You may find that useful. :)

**Comment by Aizistral** [comment]
> @Extegral JDLogic has written a small little blurb on the use of the command: https://gist.github.com/JDLogic/bf16deed3bcf99bd9e1a22eb21148389
> 
> You may find that useful. :)

Oh thanks, that comes in handy
