### ISSUE TITLE
MCPNames does not correctly handle the possibility of `$` characters in mapped names

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/ForgeGradle#720]
To reproduce:
- Use a mcp mapping export which has a mapped name containing a `$` (such as a recent export for 1.15.1: `20200916-1.15.1`, which contains the mapping `p_212860_1_ => pixelTransformer$factory`)
- Try and import / build a mod dev project, it will fail with the following error:

```
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at net.minecraftforge.gradle.common.util.McpNames.replaceInLine(McpNames.java:201)
	at net.minecraftforge.gradle.common.util.McpNames.rename(McpNames.java:105)
	at net.minecraftforge.gradle.userdev.MinecraftUserRepo.findSource(MinecraftUserRepo.java:1154)
	at net.minecraftforge.gradle.userdev.MinecraftUserRepo.findRecomp(MinecraftUserRepo.java:1169)
	at net.minecraftforge.gradle.userdev.MinecraftUserRepo.findRaw(MinecraftUserRepo.java:542)
	at net.minecraftforge.gradle.userdev.MinecraftUserRepo.findFile(MinecraftUserRepo.java:409)
```

[Full log can be found here](https://pastebin.com/eYPhuQzr)

**What is happening?**

In replacing names, Forge Gradle does a straight regex replacement here:

https://github.com/MinecraftForge/ForgeGradle/blob/3bb06c70617a8f3dfd23975f48b7846fb84b0f07/src/common/java/net/minecraftforge/gradle/common/util/McpNames.java#L201

However, if the *mapped name* contains a `$`, this fails because `$` is a special character in regex replacements, so we get the above error, because a plain `$` usually indicates a group.

**Comment by LexManos** [comment]
Interesting, probably worth fixing sometime. However, I would say that's a bad mapping and should probably be fixed. Most people use that because Fernflower prints inner classes like that. Which I will be changing eventually.

**Comment by Pokechu22** [comment]
This same issue happened in the 20200902 mappings with `p_213204_1_` (as `dimensionData$manager`); it was fixed in the 20200903 mappings.  I agree that it's a bad mapping and people shouldn't be naming things like that.

**Comment by Lanse505** [comment]
Ignore

**Comment by Pokechu22** [comment]
@kashike renamed it about half an hour ago.

```
    pokechu22 | ph p_212860_1_
MCPBot_Reborn | === Method Param History: p_212860_1_ ===
MCPBot_Reborn | [1.15.1, Staged 2020-09-16 18:16:08.953960-04:00] kashike: pixelTransformer$factory => pixelFactory
MCPBot_Reborn | [1.15.1, Staged 2020-09-04 13:37:04.492310-04:00] k9-relay: p_212860_1_ => pixelTransformer$factory
```

**Comment by Lanse505** [comment]
Ah ignore me, I see the issue.
I was assuming this was related to the 20200916-1.16.2 mappings.
But it seems this is related to the 1.15 mappings that kashike has pushed to.
