### ISSUE TITLE
GradleDaemon never exits after running minecraft in dev

### ISSUE THREAD

**Issue by Corosauce** [MinecraftForge/ForgeGradle#732]
In both a forge 1.15 and 1.16 setup, when I run and exit a client instance in dev, the GradleDaemon java instance will remain running, using an extra 1GB of memory until I manually kill it.

```
corosus@Corobox:/mnt/e/git$ ps aux | grep GradleDaemon
/usr/lib/jvm/java-8-oracle/bin/java` -Xmx3G -Dfile.encoding=UTF-8 -Duser.country=CA -Duser.language=en -Duser.variant -cp /home/corosus/.gradle/wrapper/dists/gradle-4.10.3-bin/31t79e2qsceia4mkbojplrgx/gradle-4.10.3/lib/gradle-launcher-4.10.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.10.3
```

Setup:
Forge 1.16.3 - 35.0.18
IDEA 19.2
KDE Neon 5.15

**Comment by nnym** [comment]
The main purpose of the daemon is to keep running in the background in order to prevent Gradle's startup cost for subsequent invocations, so it is functioning as intended.
