### ISSUE TITLE
FG4, Gradle 6.8, Call for Triage people

### ISSUE THREAD

**Issue by LexManos** [MinecraftForge/ForgeGradle#739]
So, thanks to @gabizou, we've updated FG to 4.0, and Gradle 6.8.
This *seems* to be working fine in basic tests.
The data is compatible, so any FG3 workspaces should be able to be upgrade to FG4. {Basically this means old Forge build will work if you wanna upgrade your MDK}

We still need to go through and cleanup all the old hacks and dead code we had in place for older gradle versions/cross version compatibility. Which means that we may be deleting code and doing some binary breaks. So until we hit 4.1, it's recommended that you lock your dependency instead of using 4.0.+

I want to design a new versioning rule as well, to give us the option of making breaking changes more often. So i'm thinking we have the Major version be Gradle version updates. Where we bump the required version of Gradle. And we use Minor versions for minor breaking changes. 

On top of that, this repo has been neglected honestly because I personally hate Gradle and want to break things every time I have to deal with the internals. So if there is anyone in the community who wants to join the triage team specifically dedicated to this repo/gradle issues. Speak up and we can have @tterrag1098, @TheCurle, @mezz pick people and have them do the basic triage.

Edit: @covers1624 has officially become the Gradle Triage team lead. He's in charge of picking whoever he wants to be a triage member. I've also granted him commit access to this repo. So he can pull in PRs and other things.

**Comment by SizableShrimp** [comment]
We are now on FG 5.1.x and Gradle 7.4.2.
To my understanding, we will be incrementing the major version of FG when we must break compatibility with a new major version of Gradle. This does not mean the version numbers themselves will match. We will also be treating even minor versions as areas where we can break existing compatibility in the name of improving FG and removing hacks. This means 5.0.x and 5.2.x are both targets for breaking changes. Whether we get to 5.2.x before 6.0.x / Gradle 8 is yet to be seen. Triaging also seems to be not that big an issue as this repo overall sees little activity, little enough that it can be handled by 1-2 people. Closing for now.
