### ISSUE TITLE
4.1.3 Incompatible with Java 16

### ISSUE THREAD

**Issue by ChloeDawn** [MinecraftForge/ForgeGradle#756]
When setting up a workspace on **[JDK 16](https://openjdk.java.net/jeps/396)**, ForgeGradle encounters the following problem:

`Cause: module java.base does not open java.lang.reflect to unnamed module @598f50f4`
`Could not access Field.modifiers to definalize reflection object. Use Java 8, current version: 16`

Full stacktrace: https://gist.github.com/5f751496f247d7e3b25f95a6cb816c46

I believe this has been caused by **[JEP 396: Strongly Encapsulate JDK Internals by Default](https://openjdk.java.net/jeps/396)**

**Comment by TheCurle** [comment]
Java 16 has been a pain in the butt for us for a while. 
https://github.com/cpw/modlauncher/pull/66
We'd appreciate some help with fixing this, if anyone has the know-how.

**Comment by gigaherz** [comment]
Yes. Java16 will not work without explicitly disabling this new setting. Until a solution is found, try using `--illegal-access=permit` to make it work.

**Comment by zml2008** [comment]
Keep in mind Gradle 6.8 does not support Java 16 yet anyways, so you will have issues there. Gradle 7, which does support Java 16, has not even hit its first RC yet so it probably makes sense to hold off a little while before trying to update FG's internals hacks.

**Comment by ijo42** [comment]
Gradle 7.0 + FG4 crash (JDK 11)
https://gist.github.com/ijo42/73f8433e52a0fa4eea82b46e89e4951e

**Comment by LexManos** [comment]
FG 4 targets 6.8.x and JDK 8-15. Anything beyond that is untested and unsupported.

**Comment by SizableShrimp** [comment]
FG5 targets Gradle 7.1.+ and JDK 8-16. Use FG5 for full support with Java 16 and Gradle 7.
