### ISSUE TITLE
i keep getting an error

### ISSUE THREAD

**Issue by realyusufismail** [MinecraftForge/ForgeGradle#757]
Could not resolve all files for configuration ':_compileJava_1'.
Could not find org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822.
     Searched in the following locations:
       - https://files.minecraftforge.net/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
       - https://files.minecraftforge.net/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
       - file:/Users/YusufIsmail/.gradle/caches/forge_gradle/bundeled_repo/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
       - file:/Users/YusufIsmail/.gradle/caches/forge_gradle/bundeled_repo/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
       - https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
       - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
       - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
     Required by:
         project : > net.minecraft:client:1.12.2

**Comment by TheCurle** [comment]
1.12 is no longer supported. You were told this on Discord.

**Comment by realyusufismail** [comment]
then were can i get help

**Comment by TheCurle** [comment]
From a community that does support it. We don't have the will, time, or energy.

**Comment by realyusufismail** [comment]
cant you help me
