### ISSUE TITLE
Suggestion: Replace custom run config generation with JetBrains' supported mechanism for defining run configs

### ISSUE THREAD

**Issue by hakanai** [MinecraftForge/ForgeGradle#759]
For some number of years now, it has been possible to define run configurations in Gradle code using a plugin very tightly bound to IDEA:

https://github.com/JetBrains/gradle-idea-ext-plugin

This plugin does a better job of keeping run configurations up to date,  and has even published a stable release.

**Comment by LexManos** [comment]
Cool let me know when it's a standard feature in gradle that also works for eclipse.

**Comment by hakanai** [comment]
Poor reason to turn down a good suggestion.

Par for the course for this project though, to be honest.

**Comment by ravenbuilder934** [comment]
I agree tbh. If it doesn't work on Eclipse, what would eclipse-users do?

**Comment by hakanai** [comment]
They would run the same task they have always run. I only proposed changing it for the IDEA run configs.

**Comment by LexManos** [comment]
IntelliJ has and always will be second-class/unofficially supported in FG.
Eclipse is the only thing we target.
If you don't like that. Too bad.
I am not writing complex bespoke shit for IntellJ.
We've already gone through about 20 itterations of trying to get that shit to work correctly. We have a system right now that does so i'm leaving it at that.

As for your suggestion. It was "Throw out your current shit and implement something thats IntelliJ specific" Which is not gunna happen. So again, let me know when Gradle decides to do something useful for the communty and implement a run config standard that we can hook into. Until then I don't care at all for IntelliJ.
