### ISSUE TITLE
Why is forgegradle doing this?

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/ForgeGradle#773]
I run `gradlew genEclipseRuns` and everything turns out fine, build successful with no warnings.
I import the project into Eclipse and...
I get a load of errors from the examplemod along with a gradle error:
`Unresolved dependency: net.minecraftforge:forge:1.12.2-14.23.5.2855_mapped_snapshot_20171003-1.12`
I'm using recommended version of Forge MDK (1.12.2-14.23.5.2855), and Java JDK 8 update 231, 64 bit.
I can't import anything from Forge or net.minecraft.
Please help!

**Comment by SizableShrimp** [comment]
ForgeGradle 1 and 2 are currently unmaintained. There are plans to make an update fixing the issue with the updated Forge maven endpoint, along with adding a warning to update to FG3/4 or help in the efforts to get older versions working on the modern toolchain. See #gradle for more info in the [Discord](https://discord.gg/UvedJ9m). Note: Only 1.15 and 1.16 are supported on the Forge discord and forums, so you will need to go somewhere else for support.

**Comment by ghost** [comment]
Would you know if ... patch would have this same error?

**Comment by SizableShrimp** [comment]
This github is not the place for support.

**Comment by DaemonUmbra** [comment]
We do not advocate using third party hacks, 1.12 has a FG3 version of the MDK available as a courtesy despite 1.12 being out of support.
It is your choice to update to FG3 or not, just don't blame us for things breaking when we've already provided a way to keep things working.
