### ISSUE TITLE
classes and resource configuration of ModConfig will be ignored

### ISSUE THREAD

**Issue by anatawa12** [MinecraftForge/ForgeGradle#787]
With config like below, the ForgeGradle passes `auto_closer%%/<rootproject>/1132/build/resources/main:auto_closer%%/<rootproject>/1132/build/classes/java/main` in `MOD_CLASSES` envionment variable
```
minecraft {
    runs {
        server {
            mods {
                auto_closer {
                    classes sourceSets.main.output.classesDirs
                    resource rootProject.sourceSets.main.output.resourcesDir
                }
            }
        }
    }
}
```
**EXPECTED BEHAVIOR**
passes `auto_closer%%/<rootproject>/build/resources/main:auto_closer%%/<rootproject>/1132/build/classes/java/main`

**Comment by SizableShrimp** [comment]
Fixed by ed208677be58388176fd168bdf84c1f74456250e and 5665f587843bb299ab3ceee2e22042c1c2960547.
