### ISSUE TITLE
Official Mojang Mappings not working

### ISSUE THREAD

**Issue by warjort** [MinecraftForge/ForgeGradle#795]
Using mappings channel "official" doesn't generate classes with the official mojang mappings.

Steps to reproduce:
* Download the mdk, I used forge-1.16.5-36.1.0-mdk.zip
* Verify it has:  mappings channel: 'official', version: '1.16.5'
* Build the project
* Notice the forge jars don't have the official mappings, e.g. in the gradle cache

````
$ jar -tf forge-1.16.5-36.1.0_mapped_official_1.16.5.jar | grep AbstractBlock
net/minecraft/block/AbstractBlock.class
net/minecraft/block/AbstractBlock$AbstractBlockState$Cache.class
net/minecraft/block/AbstractBlock$1.class
net/minecraft/block/AbstractBlock$AbstractBlockState.class
net/minecraft/block/AbstractBlock$OffsetType.class
net/minecraft/block/AbstractBlock$Properties.class
net/minecraft/block/AbstractBlock$IExtendedPositionPredicate.class
net/minecraft/block/AbstractBlock$IPositionPredicate.class

$ jar -tf forge-1.16.5-36.1.0_mapped_official_1.16.5-recomp.jar | grep AbstractBlock
net/minecraft/block/AbstractBlock$1.class
net/minecraft/block/AbstractBlock$AbstractBlockState$Cache.class
net/minecraft/block/AbstractBlock$AbstractBlockState.class
net/minecraft/block/AbstractBlock$IExtendedPositionPredicate.class
net/minecraft/block/AbstractBlock$IPositionPredicate.class
net/minecraft/block/AbstractBlock$OffsetType.class
net/minecraft/block/AbstractBlock$Properties.class
net/minecraft/block/AbstractBlock.class
````

In the official mappings AbstractBlock is called BlockBehaviour and is in a different package.

You might need to clear this part of your gradle cache to reproduce this problem.

**Comment by ChampionAsh5357** [comment]
Class names are not applied in 1.16.5 to maintain binary compat with other versions of 1.16 becauce of how MCPConfig was designed. They will be changed in 1.17.

**Comment by warjort** [comment]
Ok thanks, maybe you can update the docs to say it doesn't work, yet...?

**Comment by ChampionAsh5357** [comment]
The omnibus PR is already aware and has documented this, it just hasn't been reviewed yet.
