### ISSUE TITLE
Cannot invoke method describe() on null object

### ISSUE THREAD

**Issue by smartcreeper192** [MinecraftForge/ForgeGradle#807]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\WYB\Downloads\ForgeGradle-FG_4.0\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'ForgeGradle'.
> Cannot invoke method describe() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 57s
![png](https://user-images.githubusercontent.com/53931065/124685668-51319800-df04-11eb-8277-05489d7f4496.PNG)

**Comment by LexManos** [comment]
You have to clone the repo correctly. Also this is not a support channel. This is for reporting issues.
