### ISSUE TITLE
[FG5.0] Could not get resource 'https://raw.githubusercontent.com/SizableShrimp/Forge-Class-Remapper/main/classremapper.gradle'.

### ISSUE THREAD

**Issue by AlbusSparrow** [MinecraftForge/ForgeGradle#818]
When I was building MDK1.17 workspace, the bug on the title appeared. Though I can download the file on https://raw.githubusercontent.com/SizableShrimp/Forge-Class-Remapper/main/classremapper.gradle, the CLI could not get any information from the website.

**Comment by TheCurle** [comment]
This is an issue with SizeableShrimp's instructions, not ForgeGradle. Open an issue on the repo you linked.
