### ISSUE TITLE
MCP Source und Target updaten

### ISSUE THREAD

**Issue by masterphil1** [MinecraftForge/ForgeGradle#829]
Hallo zusammen , ich bin gereade dabei mit mcp ein 1.8 client zu coden doch bei mir ist das problem da bei mir teht da ich source und target updaten . Kann mir jemeand sagen wie man das machst ?

**Comment by TheCurle** [comment]
Writing custom clients to give you an advantage in PVP is not supported here.
1.8 itself is not supported here, either.
Please stick to English for future reference.
