### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by CaptainAhmed18** [MinecraftForge/ForgeGradle#832]
Minecraft keeps Crashing several times. Needs to be fixed urgently. Version 1.12.2.

[crash-2021-12-14_15.38.10-client.txt](https://github.com/MinecraftForge/ForgeGradle/files/7711696/crash-2021-12-14_15.38.10-client.txt)

**Comment by FinnT730** [comment]
Forge 1.12 is not supported anymore.
Please update to a modern version (1.16.5 or 1.18.1)

**Comment by marchermans** [comment]
1.12.2 is out of support.
