### ISSUE TITLE
Refmap doesn't generate

### ISSUE THREAD

**Issue by rastiqdev** [MinecraftForge/ForgeGradle#834]
Hi, I created this issue because when I test my tweaker client created with forgegradle and mixingradle, I get this warning :

`[10:06:12] [main/WARN]: Reference map 'mixins.arkemys.refmap.json' for mixins.arkemys.json could not be read. If this is a development environment you can ignore this message`

Then I get this error : 

`[10:06:12] [main/FATAL]: Mixin apply failed mixins.arkemys.json:client.MixinMinecraft -> ave`

Then my client crashes.

I think it is coming from the fact that my refmap isn't generating. I tried applying many fixes but it didn't solve my problem.

By the way here is my build.gradle :

https://pastebin.com/LF7Fx9bd

**Comment by TheCurle** [comment]
This is in no way related to ForgeGradle, nor is the issue tracker a support forum.

Ask in the Sponge discord server.
