### ISSUE TITLE
Gradle sync error

### ISSUE THREAD

**Issue by phant0m2290** [MinecraftForge/ForgeGradle#837]
When i sync gradle it gives this error
`Gradle sync failed: Could not find net.minecraftforge:forge:1.18.1-39.0.9_mapped_official_1.18.1.`

**Comment by AterAnimAvis** [comment]
This issue tracker is for feature requests and complete bug reports.

This seems more suited for the [forums](https://forums.minecraftforge.net/) or the [discord](https://discord.gg/forge)

Saying that, the error you provided isn't the actual error:
> Dependencies that have names ending in \_mapped_[stable/snapshot/official]_[Mapping Version] are NOT hosted anywhere, they are generated by ForgeGradle on the fly and inserted into Gradle through a fake repository, when one of these dependencies is reported missing it is a sign that errors occurred generating them.
Please look higher in the Gradle log for the actual error.
