### ISSUE TITLE
Should `@SubscribeEvent` automatically apply `@SuppressWarnings("unused")

### ISSUE THREAD

**Issue by a2435191** [MinecraftForge/ForgeGradle#839]
Title. Since Forge's event handler accesses the `@SubscribeEvent`-annotated methods of a mod class in a way most static analysis tools can't see, would it make sense to have it apply @SuppressWarnings("unused") to its method?

**Comment by TheCurle** [comment]
It's a good idea in theory, but IDEs are known to be picky about how they detect something being used.
It needs some testing, but I think it'd be worth a shot.

**Comment by LexManos** [comment]
If you care about the warning, you can suppress it yourself easily enough. Adding extra processing on our end will just cause more  of a maintenance nightmare then it's worth. Not to mention, it hides unused warnings inside the methods. Which I wouldn't want to do.
