### ISSUE TITLE
No gradle actions available in eclipse after setting up the project.

### ISSUE THREAD

**Issue by ThatsNasu** [MinecraftForge/ForgeGradle#841]
I followed the "Gettings Started"-Guide from https://mcforge.readthedocs.io/en/latest/gettingstarted/, downloaded the MDK from the link to the files side provided, copied the gradle.build, gradlew, gradlew.bat, and the gradle folder over into my Project folder, started Eclipse and imported it as a gradle project. After letting Eclipse process everything, on my Project appears a red "x", since Eclipse does not give me a lot of information what went wrong, i tried to run gradlew from commandline myself, which resulted in a very nasty error log.

Error Message: FAILURE: Build failed with an exception.
What went wrong:
Could not resolve all files for configuration ':runtimeClasspathCopy'.
Could not find net.minecraftforge:forge:1.18.2-40.0.13_mapped_official_1.18.2.

My guess is that gradle cannot find the maven central / forge maven repositories (i tried looking it up on maven central and could not find it)

OS: Windows 10 x64
JDK Version: 17.0.2 (2022-01-18 LTS)
Eclipse Version: 2021006 (4.20.0) / Build ID: 20210612-201
[gradlelog.txt](https://github.com/MinecraftForge/ForgeGradle/files/8240507/gradlelog.txt)
1

**Comment by sciwhiz12** [comment]
:wave: We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/). Please create a new topic on the support forum with this issue, and the conversation can continue there.
