### ISSUE TITLE
genIntellijRuns minecraft client run not loading resources

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/ForgeGradle#853]
```java
Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("my-resource.png"));
```
^ this line should bind a texture but it throws NullPointerException if i run it in minecraft client run that was generated by forgegradle's genIntellijRuns (if i build it and then run in minecraft everything works fine).

**Comment by TheCurle** [comment]
This is not a ForgeGradle issue, this is a basic misconception of how the game works.
You're also using an unsupporrted version of Minecraft.
This is also not a support forum, this is an issue tracker.

Please vacate our repositories.
