### ISSUE TITLE
Forge 40.1.20/IntelliJ "java.lang.IllegalStateException: ProjectScopeServices has been closed." error and "Could not resolve all files for configuration ':runtimeClasspathCopy'." error

### ISSUE THREAD

**Issue by leapordtank** [MinecraftForge/ForgeGradle#854]
![image](https://user-images.githubusercontent.com/86417296/168526427-0348e348-2122-4f6a-9a0d-2283aac5763f.png)
![image](https://user-images.githubusercontent.com/86417296/168526490-4ab3f1de-1a08-4c25-a6b4-4a6be1dc27a5.png)

**Comment by SizableShrimp** [comment]
This is not a ForgeGradle bug, and this issue tracker is not for tech support. Use the Forge discord or Forge forums for help.
