### ISSUE TITLE
Group runConfigurations with the same prefix

### ISSUE THREAD

**Issue by ApexModder** [MinecraftForge/ForgeGradle#870]
Would be nice to have ForgeGradle group runConfigurations that get given the same auto generated prefix, this is most helpful in multiproject workspaces

All of the runConfigs in the provided image have the same `taskName` but ForgeGradle automaticly gives them a prefix based on what project they belong to.

Would be nice for conveince & organizational pruposes to have ForgeGradle throw these in groups (or what Intellij calls "folders" in the runConfig editor) named after the project (auto given prefix)

<details>
<summary>Example</summary>

![](https://cdn.discordapp.com/attachments/313125603924639766/988913829872275456/unknown.png)

</details>

**Comment by Matyrobbrt** [comment]
FG6 introduced the `folderName` property which can now be used to group configurations into folders.
