### ISSUE TITLE
GradleRepositoryAdapter error after Artifactural update.

### ISSUE THREAD

**Issue by bconlon1** [MinecraftForge/ForgeGradle#897]
Upon trying to set up a new workspace, I receive this Gradle error: https://gist.github.com/bconlon1/b3d4fa28133c7a252b3bc32ca619c2df. From what I've gleaned from the Forge Discord and this repository, this was an issue caused by 3af3c5cea609107e5b35f9da49af87677bdaf4f7, was reverted by 4bcfd49f7df21e4a633a1b11956ce2265b063795, and was meant to be fixed by 9a1a9781e329427e5daea299abeef867991340dd. However, the issue seems to still be occurring despite that.

**Comment by SizableShrimp** [comment]
Ended up being a cached bad ForgeGradle version. The fix is `./gradlew --refresh-dependencies`
