### ISSUE TITLE
Error "Cannot mutate content repository descriptor"

### ISSUE THREAD

**Issue by henkelmax** [MinecraftForge/ForgeGradle#912]
Since version `5.1.70` ForgeGradle fails to set up with the error `Cannot mutate content repository descriptor 'BUNDELED_-1284700514' after repository has been used`.
Version `5.1.69` works perfectly fine.

https://gist.github.com/henkelmax/f26c23724486c418e2ed58c24a811df9

**Comment by SizableShrimp** [comment]
Please provide your build.gradle

**Comment by henkelmax** [comment]
> Please provide your build.gradle

https://github.com/henkelmax/simple-voice-chat/blob/1.19.4/forge/build.gradle

**Comment by marchermans** [comment]
You seem to be applying the plugin twice. Although I am unsure what is causing the issue in your case, I would start with fixing that.

**Comment by henkelmax** [comment]
> You seem to be applying the plugin twice. Although I am unsure what is causing the issue in your case, I would start with fixing that.

Yeah, doesn't make a difference.

**Comment by Matyrobbrt** [comment]
The eager `all` and resolution of the recursive shadow copy configuration in https://github.com/henkelmax/simple-voice-chat/blob/1.19.4/forge/build.gradle#L33-L36 is the most likely to cause this issue. You should instead use the `minecraftLibrary` configuration as described [on the wiki](https://github.com/MinecraftForge/ForgeGradle/wiki/Dependencies#non-minecraft-dependencies). It's also recommended you avoid using eager configuration methods and instead use lazy ones such as `configureEach`. 
For further debugging though, please join the [Forge Discord server](https://discord.gg/UvedJ9m) in the `#gradle` channel.

**Comment by henkelmax** [comment]
That worked, thanks for the help @Matyrobbrt
