### ISSUE TITLE
setupDecompWorkspace not working.

### ISSUE THREAD

**Issue by Koigokoro123** [MinecraftForge/ForgeGradle#932]
![image](https://github.com/MinecraftForge/ForgeGradle/assets/139644329/ac1b5abf-9c14-4ff3-a102-00502d322d09)
Wanted to start coding a minecraft mod for 1.8.9 and came across this issue. I put this issue into ChatGPT and tried out the various methods that it proposed. One of these was to run `gradlew.bat setupDecompWorkspace`. After running this command, I got the above message. ChatGPT also told me to verify that the gradlew version I had even contained this command and I did but to no avail. The README file just told me to run this exact same command (`gradlew setupDecompWorkspace`). ChatGPT also told me to cconfirm the path was set correctly and that build.gradle and gradlew.bat were both in the folder (they are and I verified the path in command prompt by simply running path, it was the correct path). The changelog contained some info but all it pointed to was cpw's issue in 2016 by saying that the issue was there but it was planned to be fixed. I tried looking online but couldn't find anything.

**Comment by LexManos** [comment]
1.8.9 is not supported, but there are plenty of tutorials out there for it.
ChatGPT is know to lie and give false information, you shouldnt rely on it for anything functional.

**Comment by Koigokoro123** [comment]
I'm currently following a tutorial by [CJMinecraft](https://www.youtube.com/watch?v=N4CGw-qnwSU) and he did this exact step. However, it does not seem to be working for me. As for why 1.8.9, I'm creating a mod for hypixel (only for personal use though) and all my other mods (not created by me just other ones I've downloaded) are on 1.8.9 so my other mods wouldn't work if it wasn't 1.8.9
