### ISSUE TITLE
LWJGL3 ????

### ISSUE THREAD

**Issue by colrobloxkid69420** [MinecraftForge/ForgeGradle#957]
I wanted to run some forge mods natively on wayland. The usual way to do it now is through using GLFW 3.4+, unfortunately LWJGL2 doesn't use GLFW. Vanilla minecraft seems to use/support LWJGL3 already. Could we get support for that?

I'd like to add that I am not a programmer or anything and thus barely know anything about what this implies, so tell me if this is unreasonable.

**Comment by Jonathing** [comment]
First of all, this is an issue tracker for ForgeGradle, not Forge itself. So you made an issue on the wrong issues repo.

Anyways, this is a duplicate issue that's already been talked about. Factors like the Minecraft version and such come in to play. We have an issue discussing this here: MinecraftForge/MinecraftForge#10062

**Comment by colrobloxkid69420** [comment]
thank you!
